### ISSUE TITLE
Provide new (and round) icons

### ISSUE THREAD

**Issue by julian-klode** [julian-klode/dns66#10]
We currently do not really have a source for the icon that we can modify. It would be great to have an icon with an SVG source that we can actually reasonably modify.

Android 7.1 also introduces round icons, we should have one too.

**Comment by relan** [comment]
Just saw this app on F-Droid and decided that it would be cool to stylize the icon this way:

<img src="https://cloud.githubusercontent.com/assets/8256809/19797724/da0cf8b6-9cfd-11e6-8058-e92f24ea81d6.png" width="50%">

<img src="https://cloud.githubusercontent.com/assets/8256809/19797808/63b57002-9cfe-11e6-87cc-66e69778fe8d.png" width="50%">

No idea what story is behind the name, but it fits the famous route 66 sign perfectly. If you like this idea, I can make a pull request updating the icon (with SVG version of course).

**Comment by julian-klode** [comment]
@relan The crowd seems to love the icon. There is no real story behind the name. I needed a number, but DNS42 was already used, so I ended up with DNS66.

That said, there are a lot of trademarks on route 66 icons, and there was a route 66 routing (gps) app. So I'm not sure it's a sensible choice, although I like it.

**Comment by relan** [comment]
All this legal nonsense can be a problem, that's for sure. I understand your concern.

**Comment by julian-klode** [comment]
Just for the record: We also need an icon for quick settings tile.

**Comment by Steve2Go** [comment]
A thought on icons. The shield icon used in the interface would make a great notification tile icon, but have you considered using it as the app icon as well?

This was a quick concept I came up with, happy to work it further to your liking Julian if I'm on to something.

![shield](https://user-images.githubusercontent.com/18142571/33202807-9a4198fa-d149-11e7-9b19-3b6dbea4783b.png)

**Comment by julian-klode** [comment]
Indeed, I should just pass it through the adaptive icon generator.
