### ISSUE TITLE
DNSCrypt resolvers for #11

### ISSUE THREAD

**Issue by zero77** [julian-klode/dns66#102]
Can you add a subscription to this DNS server list as these DNS servers are safe and secure as some of them don’t log data and they are encrypted.

https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv

Thanks

**Comment by julian-klode** [comment]
That depends on #11

**Comment by zero77** [comment]
This is a bit different to #11 but it is based on that, and I did not no that DNS Crypt was not currently supported.

So, until it is supported this would be a waste of time as it wouldn’t fully work.

**Comment by Sak94664** [comment]
@julian-klode 
How about integrating a feature that allows users to select the specified port of dns server.(like port 5353 on 127.0.0.1) so it can allow users to run dnscrypt-proxy on 127.0.0.1 without root and forward dns request to dnscrypt-proxy.

**Comment by julian-klode** [comment]
Probably going to use DNS over TLS instead, so closing this. Adding the list to #11, though.
