### ISSUE TITLE
Integration with OrBot

### ISSUE THREAD

**Issue by gappleto97** [julian-klode/dns66#103]
It would be nice if you could proxy traffic through OrBot. At the moment you cannot use both without root, as they would each like to use the VPN slot. However, if you could either use their API, or allow a SOCKS5 proxy, then they could work together quite well.

**Comment by julian-klode** [comment]
I don't think we'll ever see this happening. You cannot send DNS packets via Tor SOCKS5 (and Java has no support for proxying UDP packets via SOCKS5 either). Tor provides its own protocol for DNS; but I'm not sure if that is accessible some way via Orbot.
