### ISSUE TITLE
Filter out apps without internet permission

### ISSUE THREAD

**Issue by lheckemann** [julian-klode/dns66#107]
DNS66 is displaying applications like oandbackup and SolitaireCG which have no internet access permission. I think it would make sense to leave these out of the list, if possible?

**Comment by julian-klode** [comment]
Shell also has no INTERNET permission, but can still access the internet, so that's weird. There might be other corner cases.

**Comment by julian-klode** [comment]
This is not going to happen due to the complications mentioned.
