### ISSUE TITLE
Request to add Adguard DNS which block ads, trackers, phishing or/and adult websites

### ISSUE THREAD

**Issue by SMed79** [julian-klode/dns66#119]
Hi, 

the default primary **Adguard DNS** are useful to block ads, trackers, phishing websites and the secondary keep your family safe by blocking adult websites and enable safe search.

It's will be helpful if you add them to the custom DNS servers list in **DNS66**.

**Default mode**

> Use these servers to block ads, trackers and phishing websites

```
176.103.130.130
176.103.130.131
```

**Family protection**

> Blocking adult websites + safe search + block ads, trackers and phishing websites

```
176.103.130.132
176.103.130.134
```

Source: 
- https://github.com/AdguardTeam/AdguardDNS
- https://adguard.com/en/adguard-dns/overview.html

Thank you.

**Comment by julian-klode** [comment]
Not going to happen. Let's see why:

1. It directly conflicts with host filtering, leading to a suboptimal UI when you need to unblock something (it becomes impossible).
2. It's only free for "personal" use.
3. "Family protection" is nonsense. The VPN service can be turned off by anyone effortlessly.

**Comment by SMed79** [comment]
Thank you for taking the time that you did to give me answers.

**Comment by julian-klode** [comment]
Note that there a various "family protection" host files. We could probably add some of these:

https://github.com/Clefspeare13/pornhosts
https://github.com/Sinfonietta/hostfiles

Not really sure about the safety that gives anyone for "family" stuff.
