### ISSUE TITLE
Refresh Daily on mobile data

### ISSUE THREAD

**Issue by jiang-qian** [julian-klode/dns66#122]
I am in version 0.5.0 and I am very happy that the addition of "refresh daily" option for automatically updating the blocked host list!

Right now, the update will happen "when charging, idle and on an unmetered network". Usually "metered network" in android refers to wifi.

My mobile data is pay per MB. Will the update happen on mobile data? If so, perhaps there could be an option to stop updating on mobile data? If mobile data are always counted as "metered network", perhaps the text on the option could be clearer: "...idle and on an unmetered wifi"?

**Comment by julian-klode** [comment]
The 4 options that are available to schedule a job are:

* Any network
* No network
* Not roaming
* Unmetered

If you pay per MB, your network is metered. Metered replaced WiFi as it's clearer and more accurate. It might very well only be WiFi in effect, but there might be other forms. Clearly, mobile data you pay per MB is metered. (Not sure if metered hotspots are considered unmetered, kind of weird stuff - it's not like Android can detect if the network is metered or not).

**Comment by jiang-qian** [comment]
My question is how does android know my mobile data is metered or not?
(Here in US, a lot of people have "unlimited" mobile data, and people like
me who use pay-per MB is very rare). Is there an option in Android to set
the mobile data to be "metered"? I only see an option to mark wifi network
metered, but no option to mark mobile data "metered".

If there is no way to inform android that my mobile data is metered, does
that mean all I could do is to turn off update to when on mobile?

In any case, this is a small issue. Thank you for making this very useful
app!

**Comment by julian-klode** [comment]
I think data is always metered in Android terms, and WiFi is usually unmetered (though, maybe it detects some portals?), but WiFi network can be set manually to metered from the Data usage settings as outlined in https://android.stackexchange.com/questions/143694/metered-wi-fi-connection-on-android-tablet (for example).

All existing WiFi options became Metered with N, so it really is just a different way to say WiFi (excluding networks marked as metered) at the moment. It's definitely more future proof, though

**Comment by jiang-qian** [comment]
I know that wifi can be set to be metered. I didn't realize that data are
always considered metered. Thank you for explaining this, and for making
this really useful app!
Regards
Jiang
