### ISSUE TITLE
Is IPv6 support working?

### ISSUE THREAD

**Issue by gatokichi** [julian-klode/dns66#129]
All IPv6 packets are blocked on Wi-Fi with IPv6 support "ON".
I don't know IPv6 on 3G and LTE. I don't have IPv6 APN.

**Comment by julian-klode** [comment]
Yes, if you have IPv6 DNS servers, it enables IPv6 support. If you do not have IPv6 DNS servers, you don't get IPv6 support (in >= 0.5, in 0.4.something you do, but that crashes on some phones...)

**Comment by gatokichi** [comment]
Thank you very much. It works very well with custom DNS servers "On".
By the way, why are all IPv6 packets rejected when the switch is off?
It is strange that packets that do not need resolvers do not pass.

**Comment by gatokichi** [comment]
Conversely, when switching from Wi-Fi to LTE, dns66 will not work with IPv6 support "On".
WiFi (IPv6+IPv4) --> LTE (IPv4)
