### ISSUE TITLE
App for Play Store

### ISSUE THREAD

**Issue by XtremeCoder109** [julian-klode/dns66#130]
Not really a big issue, but it would be much simpler and easier to publish to Play Store. And that way, it seems more secure for most people, but I know it's not a virus or malware. You don't have to do this, just consider it for ease of accessing and updating the app.

**Comment by julian-klode** [comment]
Well:

1. It needs $25 registration fee
2. Google will either reject it immediately or remove it later on. Well, maybe not if I remove the ad blocking filter lists from the default settings - but then it's not really immediately useful to most people, right?

**Comment by FernandoMiguel** [comment]
@julian-klode they might also entirely kill you google account and any other account related to the account you use for dev account.
be careful

**Comment by SMed79** [comment]
https://github.com/julian-klode/dns66/issues/82

**Comment by julian-klode** [comment]
Closing
