### ISSUE TITLE
No internet access in chrome when switching from mobile to wifi right after boot

### ISSUE THREAD

**Issue by kartur** [julian-klode/dns66#132]
Hi,

When restarting my phone DNS66 also starts and works fine, but after some seconds my phone automatically connects to the Wi-Fi and then chrome doesn't get any connection anymore unless I disable and enable DNS66 again. Alternatively disabling and enabling wi-fi also works.

It seems only Chrome is effected by this. And I can only reproduce it right after the boot, afterwards switching between Wi-Fi and mobile works fine for chrome.

I am on Android 6.0.1 (LinageOS 13.0-20170323)

**Comment by julian-klode** [comment]
Boot is tough (well, reconnect in general, boot just has lots of them). The watchdog is supposed to take care of connections that stop working, but it just crashes on some phones (works just fine in 7.1.1 most of the time). Stupid Android bugs everywhere.

**Comment by kartur** [comment]
It also happened when I was just picking up my phone after some time. I have to admit I didn't use the "watch connection" option. I didn't want to activate it since it sounds like it would add additional battery drain.

When activating it, it seems to fix that problem.

**Comment by julian-klode** [comment]
I think the additional drain is manageable. The watchdog configures time outs basically, so instead of waiting indefinitely for a new DNS request it waits:

1s, 4s, 16s, 1m4s, 4m16s, 17m4s, 1h8m16s   (that's exponents of 4 seconds!)

(increasing the time out for each succesful packet, so after the first twenty minutes of a (re)connect, it only checks connectivity about once an hour).

**Comment by julian-klode** [comment]
Make sure to exempt DNS66 from power saving if it just randomly stops working, see #36

**Comment by kartur** [comment]
I'm not sure the exception for power saving is really necessary on my phone, but I did it anyway. Thanks for your help and the app ofc. 👍
