### ISSUE TITLE
Can we have the old design back please? The new one is just cluttered

### ISSUE THREAD

**Issue by uncertainquark** [julian-klode/dns66#133]
The old design was simple, clear and intuitive to understand. This one is only confusing for most users and doesn't have distinct indicators for actions.
For example, the red, green and grey colors in the pld design

**Comment by uncertainquark** [comment]
In the old* design were very intuitive to understand.

**Comment by julian-klode** [comment]
A lot of people were utterly confused by the colors in the old design ("green blocks, right?", "what do the colors mean?"). I grew tired of this. So let's hope it's really just you and we don't see the same shit again with shields. Not to mention that for some people, there is literally no visible difference between red and green.

The new design employs several indicators for the item state:

* Ignored items have lower opacity, making them standout less than active items. They are also just shield outlines, aka "there is a big hole in the middle, that's useless".
* Blocked items have shields, which makes sense, as shields protect you.
* Then there's the striked out shield. That clearly follows the "not a shield" semantic, as in: You are not protected.
