### ISSUE TITLE
dns66 is stopped after few minutes 

### ISSUE THREAD

**Issue by 28446** [julian-klode/dns66#134]
Hi,
the app keeps on stopping (I' don't know if by another app or by it self) after few minutes.
The app rest in background whit the START button active, though wile is running it work perfectly.
No other apps in background, no other VPN connections (I've orbot but is turned off). 

[my config](https://github.com/julian-klode/dns66/files/974139/66.txt)

0.5.1 from F-Droid@flymeOS 5.1 (Android 5.1).

**Comment by julian-klode** [comment]
There's a reason the watch dog is turned off by default. It does not work on 5.1.
