### ISSUE TITLE
Seems to be blocking TeamViewer even with exceptio 

### ISSUE THREAD

**Issue by twiz-ahk** [julian-klode/dns66#137]
With DNS66 on, i am unable to fully connect to my computer via TeamViewer. I have added the app as an exception, and rebooted my devices (galaxy s6, and Nook HD+) but neither will fully connect with DNS66 running.

The TeamViewer app will connect to my IP and ask for a password, as expected, but after entering will not show the computer.
The desktop WILL 'switch' into remote controlled mode (screen flicker, and notification of a valid connection) and stay there.

**Comment by craigalan** [comment]
FYI - I I'm running TeamViewer on multiple devices, and never had any difficulty connecting to any of them. Also have never had any difficulty connecting to my phone running the TeamViewer Quick Support app. 

I didn't have to add the TeamViewer application as an exception either

**Comment by twiz-ahk** [comment]
Im not sure, ive done a bit more testing with it and i thibk i can rule all the block lists out. I disabled all the hosts lists, disabled the whole hosts tab, turned off DNS66, cleared cache for both DNS66 and TeamViewer, and restarted my phone.
After starting up, without DNS66 running, TV connected fine.  After enabling DNS66, with all hosts still off, the connection problem happens again.

The last thing i can think to do is try to make a 'generic' vpn connection and see if the problem still happens. But i used another vpn-based blocker in the past, and i dont recall having an issue.

**Comment by twiz-ahk** [comment]
Still not sure of the 'why', but it seems to be a problem with any VPN and TV, probably a setting on my desktop.
