### ISSUE TITLE
Host list update errors on Wi-Fi

### ISSUE THREAD

**Issue by craigalan** [julian-klode/dns66#138]
I searched the issues and can't seem to find anything related to this, but does anyone else have issues with the hosts auto updating on Wi-Fi? They seem to randomly time out. Works fine on mobile Network but not Wi-Fi, regardless of the WAP I'm connected to.

Other than that minor issue, everything is great for me :)

**Comment by julian-klode** [comment]
Well, time outs can happen, that's how networking works. I think trying 10 seconds to make progress is enough, everything else seems too much. Some of the servers are a bit overloaded, I think.
