### ISSUE TITLE
Possibility to use knox firewall on Samsung devices

### ISSUE THREAD

**Issue by Steve2Go** [julian-klode/dns66#139]
Love the app, but on Samsung devices the VPN notification is quite obtrusive.
Would you consider hijacking the DNS using Knox in a similar manner to adhell?
https://github.com/adhell/android.

Essentially with the correct permission it's able to set rules in the Samsung firewall.

**Comment by julian-klode** [comment]
I don't think that's legally possible - because the Samsung SDK seems proprietary and the app is GPL, they can't be combined. Also the whole Samsung thing seems to require enrolling in some sort of developer program there. This does not seem all that useful.
