### ISSUE TITLE
Feature Request: Selective Proxy

### ISSUE THREAD

**Issue by gappleto97** [julian-klode/dns66#141]
My end goal here is to be able to have this app engaged *and* allow for Orbot to work on some apps which do not support proxies.

There are two possible routes for this. One would be to allow another VPN app to hook in after this. I'm pretty sure that's not feasible.

The other is to allow this app to send traffic from specific apps on a proxy. I know it can filter traffic because it already does so to select which apps to block ads on.

Is this feature in scope?

**Comment by julian-klode** [comment]
This is basically tracked in #96, apart from the selective thingy.
