### ISSUE TITLE
Constant reboots

### ISSUE THREAD

**Issue by Akojen83** [julian-klode/dns66#148]
Hi,

I'm getting constant reboots on my LG G5 @ Android 6.0.1.
Independent of whether it's in autostart or whether I start it myself.

Any way to resolve this on my part? Doesn't seem like a known issue.

**Comment by julian-klode** [comment]
So your phone is rebooting and you think DNS66 is causing it? I've heard that with Android TV before #126

**Comment by Akojen83** [comment]
Correct, my phone reboots super rarely on its own. But running DNS66 (even without touching the phone otherwise) is a sure way to get it to reboot in short span of time. So it's def. a deterministic problem.

I've got one more VPN service on my phone to my home network (established through Android, no extra app), but obviously it's inactive when DNS66 runs.
Mainly I'm trying to combat redirect apps on http://neogaf.com/forum/ with your app.

**Comment by craigalan** [comment]
Interesting that you say this.  I have installed DNS66 on my girlfriends LG G4 and recently updated to the current version and she has been complaining to me that her phone as been rebooting constantly as well.  I didn't put two and two together until I saw this post.  I am not 100% sure its related, but a big coincidence for sure.  

The G series is notorious for reboots and boot loops, but she never had an issue before.  I am going to try to revert back to the previous version for her to see if things change.

BTW - the latest version has been running just fine on my LG V20

**Comment by craigalan** [comment]
Follow up to my last post..... In my case the reboot is NOT a DNS66 issue, it's just the darn G4. As I stated the G line is notorious for reboots and boot loops, perhaps it the case for Akojrn83s G5 as well.

Akojrn83s have you tried rolling back DNS66 to the previous version to see if you still have the issue?

**Comment by julian-klode** [comment]
Closing this.
