### ISSUE TITLE
"https://hosts-file.net/ad_servers.txt" timeout

### ISSUE THREAD

**Issue by codeseven58** [julian-klode/dns66#149]
June 3rd - June 5th, "https://hosts-file.net/ad_servers.txt" has been down and preventing me from updating my host files. I set it to ignore and the app begins working regularly. 

Do with this information as you wish.

**Comment by SMed79** [comment]
You can report the issue at https://forum.hosts-file.net/viewforum.php?f=31
or via e-mail http://scr.im/itmatecouk

**Comment by julian-klode** [comment]
OK, two things to consider:

1. The file is not enabled by default
2. It does not prevent updating host files, the other host files are updated.

So, I'd say let's wait and see what happens.

**Comment by SMed79** [comment]
FYI, the `http:` version works fine http://hosts-file.net/ad_servers.txt

**Comment by jebeld17** [comment]
This happened with me exactly two days ago, as well... both on my Unlocked HTC 10 (USA Edition) and Google Nexus 9 (WiFi) running all the latest system updates.

**Comment by julian-klode** [comment]
I don't think I'm going to do anything about that. We should give it a few weeks and see if it works again, otherwise I'm dropping it from the defaults (I don't want to add another unencrypted source).

**Comment by SMed79** [comment]
The [https:](https://hosts-file.net/ad_servers.txt) version works again.
