### ISSUE TITLE
It does not block any ads

### ISSUE THREAD

**Issue by Angristan** [julian-klode/dns66#15]
The DNS option works fine, but even if I enable all the lists in the settings, ads are still visible.

![screenshot_20161023-162436](https://cloud.githubusercontent.com/assets/11699655/19626987/9bb1d2ee-993d-11e6-9c44-4fc1dd9fab6e.png)

**Comment by julian-klode** [comment]
Did you refresh the hosts file with the refresh button and restarted the service afterwards?

Currently some automation for that is missing, see other issues I created (I'd point you to them, but I'm on mobile now...)

You might also need to turn off some data saving feature in your browser, depending on its implementation

**Comment by Angristan** [comment]
Okay, I refreshed the hosts files, and it works now. I thought it would be working out of the box.

Thanks for this great app !

**Comment by Angristan** [comment]
BTW, "Peter Lowe's Ad server list" does not download

**Comment by julian-klode** [comment]
Yeah, seems like it's currently having issues. I'd expect it to be back soon though, as it is a very popular hosts file
