### ISSUE TITLE
[Request] More Block Lists

### ISSUE THREAD

**Issue by zero77** [julian-klode/dns66#150]
can you add these lists in.
Thanks

https://easylist.to/easylist/easylist.txt
https://easylist.to/easylist/easyprivacy.txt
https://secure.fanboy.co.nz/fanboy-problematic-sites.txt
https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt

**Comment by zero77** [comment]
If they need to be host only, can you add the lists from hear that are not all ready added.
Thanks

https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant

**Comment by julian-klode** [comment]
Oh, there are a lot more now. The current default values were picked by merging uBlock and uMatrix and StevenBlack's host file sources (and the SB one being enabled by default).

I think we want to simplify things and by default only offer the Unified hosts file, with checkboxes for the variants.

**Comment by julian-klode** [comment]
Wait, let's merge that in #63
