### ISSUE TITLE
IDEA: DNS66 for Multi-Platform

### ISSUE THREAD

**Issue by jebeld17** [julian-klode/dns66#151]
I already have DNS66 on my Android phone and tablet, but to have it on all devices (such as my Windows PC or work iOS devices) would be even better! :)

Please bring DNS66 to Windows, (& Mac, iOS, and Linux!)

**Comment by julian-klode** [comment]
I have neither Windows nor Mac nor iOS, nor any interest in doing anything for that. And in the Linux, Mac, and Windows case you can use a host file, or just directly use uBlock Origin in the web browser.
