### ISSUE TITLE
Enhancement: Crowdsourced blacklist/whitelists

### ISSUE THREAD

**Issue by jebeld17** [julian-klode/dns66#152]
As I stated in #89, 
[DNS66] is blocking some ads, but not a whole ton... not nearly as many as a paid app like AdGuard.
### I think a good way to help implement better ad-blocking is to have a "crowdsourced" mode that enables collection of user-consented blacklists and whitelists to add to future updates for everyone.

_As stated and implied_, a feature like this would be _consented-into on the user-end,_ in order to maintain the same level of user-anonymity in current releases and meet similar security-of-identity standards that other open source projects go by.

**Comment by smichel17** [comment]
I'm confused how this is different than the current operation. DNS66 doesn't contain any hard-coded hosts lists. It has links to community-maintained lists that it downloads; you can enable or disable those lists; and you can add new lists.

**Comment by SMed79** [comment]
There is a difference between a **DNS filtering** app and an **adblock**¹ app which has more 
[advanced filtering](https://adblockplus.org/filters) options but doesn't block ads in any other apps.

[¹] [Adblock Browser](https://adblockbrowser.org/), [Adblock Plus Samsung Internet](https://play.google.com/store/apps/details?id=org.adblockplus.adblockplussbrowser), [Adguard](https://play.google.com/store/apps/details?id=com.adguard.android.contentblocker)...

**Comment by julian-klode** [comment]
@smichel17 I believe the submitter wants to be able to directly contribute to a list maintained somewhere central from inside DNS66.

In any case, this requires a lot of administrative effort. I'm not going to do this.

**Comment by julian-klode** [comment]
@jebeld17 If you want to contribute hosts, you could do that on the AdAway hosts file: https://github.com/AdAway/AdAway/issues

**Comment by jebeld17** [comment]
Isn't DNS66 advertised as an adblock?

**Comment by smichel17** [comment]
Readme says

> This is a DNS based ad blocker for Android.

**Comment by julian-klode** [comment]
@smichel17 Yeah, that is unfortunately imprecise. I improved the wording a bit in 8e3f6c1d6254dae969cdf9279a7d2fac47c9aea4 

While I think we all use DNS66 for ad blocking, it is a versatile DNS-based host blocking solution.

**Comment by julian-klode** [comment]
@jebeld17 While it blocks ads, that's not the only way it can be used and it would not be helpful to reduce it to just an ad blocker, especially given that it's not the best ad blocker (but likely the most power-efficient one).

**Comment by SMed79** [comment]
> I think we all use DNS66 for ad blocking

Also to Improve security and [privacy](http://tinyurl.com/yblur7fg) by blocking tracking and [malware domains](https://adblockplus.org/blog/blocking-malicious-sites-with-adblock-plus) for example.

**Comment by aggsol** [comment]
>> I think we all use DNS66 for ad blocking

>Also to Improve security and privacy by blocking tracking and malware domains for example.

I also block complete service domains I do not use like Facebook, Flattr, Spotify and font CDNs.
