### ISSUE TITLE
Hosts file not working

### ISSUE THREAD

**Issue by supriyo-biswas** [julian-klode/dns66#154]
I'm trying to use [this](https://github.com/supriyo-biswas/hostsfiles/blob/master/facebook.txt) hosts file, and unfortunately none of the domains here get blocked.

I'm really not sure what the problem is, because other hosts files that I've enabled are working.

**Comment by julian-klode** [comment]
DNS66 does not accept 0.0.0.1, only 0.0.0.0, 127.0.0.1, and no IP.

**Comment by supriyo-biswas** [comment]
I see. I changed my hosts files to 127.0.0.1 and it works now.
