### ISSUE TITLE
Host Files Disappear?

### ISSUE THREAD

**Issue by tvoa90** [julian-klode/dns66#155]
I'm not sure if this issue has been addressed, but I find that after a couple of days, the host files will be deleted and I have to turn off DNS66, re-download the host files, and then turn back on DNS66. I am on 7.1.2 and am unsure if it's the device or if it is the app that is causing the host files to be deleted.

**Comment by julian-klode** [comment]
I have not seen that in 0.5, which replaced the downloader with a new one. They are just internal files now, so if anything deletes files of other apps, well, that's not good.
