### ISSUE TITLE
Drop or update Chinese translation

### ISSUE THREAD

**Issue by julian-klode** [julian-klode/dns66#157]
The translation to Chinese by @KevinSJ is severily outdated and scheduled for removal for this weeks release.

**Comment by julian-klode** [comment]
Deadline for an updated translation is likely Saturday 18:00 CEST (in 41 hours from now).

**Comment by KevinSJ** [comment]
I will try to see if I can make it up to date by Saturday.

**Comment by KevinSJ** [comment]
Have updated Chinese translation #158
