### ISSUE TITLE
Dns66 not working in S6 edge plus on Nougat.

### ISSUE THREAD

**Issue by babuonline83** [julian-klode/dns66#159]
Dns66 is not blocking any of the ads. I just installed it today and tried many apps. Same result.

![screenshot_20170625-164237](https://user-images.githubusercontent.com/29691260/27517476-63364c94-59c5-11e7-9fb6-95dd0659b8c1.png)
![screenshot_20170625-164254](https://user-images.githubusercontent.com/29691260/27517477-6336838a-59c5-11e7-9d02-e700e19782f3.png)
![screenshot_20170625-164241](https://user-images.githubusercontent.com/29691260/27517478-6336f2b6-59c5-11e7-8f69-24887e5a5e06.png)
![screenshot_20170625-164246](https://user-images.githubusercontent.com/29691260/27517479-63387776-59c5-11e7-94c2-c797c7090e49.png)

**Comment by julian-klode** [comment]
The VPN service seems to be working. In-App ad blocking is spotty, nothing to be done about that.
