### ISSUE TITLE
Is it possible redirect blocked host(url) to specific ip address 

### ISSUE THREAD

**Issue by Babar-Bashir** [julian-klode/dns66#161]
I wanna show specific message page(html) to users instead of "This site can't be reached" on chrome

**Comment by SMed79** [comment]
Yes, If you have your own domain with it own ip address.

For example, I use my hosts file to redirect unwanted search engines to [startpage.com](https://www.startpage.com/)
```
145.131.132.84 www.bing.com
145.131.132.84 search.yahoo.com
145.131.132.84 www.ask.com
145.131.132.84 www.baidu.com
...
```

**Comment by julian-klode** [comment]
No it's not. And it's not going to work anyway in a lot of cases these days. For example, the bing and yahoo domain @SMed79 mentions use HTTPS with HSTS, meaning that they cannot be downgraded to HTTP again if they have been visited once. Which means if you offer HTTPS, all they'd see is a certificate validation or; and if not, a connection error.

In any case the "redirect" feature is tracked in #86.
