### ISSUE TITLE
Breaks the Xperia update mechanism

### ISSUE THREAD

**Issue by 0rAX0** [julian-klode/dns66#163]
I've been using DNS66 since I got my Xperia and it always prevents system updates as well as stock applications' updates (handled internally, not the ones from the Play store).

Is there anything I'm missing, and what can I do to help diagnose the issue.

Thank you for your work!

**Comment by julian-klode** [comment]
They should work in the "allow system apps to bypass" setting, which is the default since 0.5 (IIRC). If they don't that's bad, but that means it's not solvable - it just does not work with (partial) VPNs then.

**Comment by 0rAX0** [comment]
I have enabled the setting, I'll wait until I get some update to test with and report back. Thanks!

**Comment by 0rAX0** [comment]
I confirm that enabling the setting works. Thank you very much! 👍🏻
