### ISSUE TITLE
How to uninstall DNS66 and get WiFi working again?

### ISSUE THREAD

**Issue by q2apro** [julian-klode/dns66#164]
First of all, I tried DNS66 and it could not block ads. Not sure if it really works on Android 5, Tab3 7 Essential. 

Today the Wifi stopped working. DNS66 said "Reconnection problem" (or alike). I deinstalled it but still cannot get the Wifi to work, it always states `Authentication problem`. Password is correct (works on another smartphone). I also tried the tablets with another Wifi, the same problem. Have two tablets, different software, both have the problem. That's why I am quite sure it's DNS66 (VPN/proxy?). 

How to get back the state that was before? How to make the default Wifi work again? I also tried "forgetting" the connection and reconnect, does not work...

**Comment by julian-klode** [comment]
If you uninstall it, it's gone completely. That's not a DNS66 problem. You might want to reboot of course, maybe something got weird in memory somewhere.

**Comment by q2apro** [comment]
Found the cause of the problem. Indeed it was the router (the repeater) who just did nonsense.

Sorry for accusing DNS66. Was just the exact time.
