### ISSUE TITLE
Can't update hosts files

### ISSUE THREAD

**Issue by 32bituser** [julian-klode/dns66#165]
Hi there!
v.0.5.x can't to update no one of the hosts file 
with the very same error "open failed: EACCESS (Permission denied)
Same time v.0.4.1 works like a charm.
(CM-based Android 5.1.1, root etc.)

[logcat.txt](https://github.com/julian-klode/dns66/files/1173363/logcat.txt)

![screenshot_2017-07-25-16-40-46](https://user-images.githubusercontent.com/30438228/28575216-f79be2b8-7158-11e7-8ad5-c6e624bfb24b.png)

**Comment by julian-klode** [comment]
Well, then your phone is broken. Since KitKat, no external storage permission is needed anymore. I suggest you try reinstalling DNS66 and/or re-setup your phone. In any case, this is not a DNS66 bug.

**Comment by 32bituser** [comment]
Weird. So why v.0.4.1 works as it should?
I've tried to install v.0.4.1 and all 0.5.x several times with the very same results each time: 0.4.1 is Ok and 0.5.x is not.

**Comment by julian-klode** [comment]
0.4.1 has the old updater which needed external storage permission (on older ROMs, like yours). Anyway, this is something your ROM or you messed up. I'd suggest updating to something that is not 2.5 years old.

**Comment by 32bituser** [comment]
Could You please to implement some smart mechanism to work around this ROM differences, depending on the ROM's version request?
Any way, I'm definitely can use v.0.4.1 for my purposes.

**Comment by elpreto** [comment]
I have the same problem and this information might be useful for you.

If I click on refresh, the download task for Adaway starts, but stays 0%. I have been waiting for hours and nothing happens, just stays there forever.
I uninstalled the app and as soon as is uninstalled, the download task (still active) starts and downloads everything in a few seconds.

I'm using a Minix U1 TV Box with Android 5.1.1.

I hope this information helps to resolve the issue.
