### ISSUE TITLE
'Watch connection' feature stuck in loop [MIUI]

### ISSUE THREAD

**Issue by mvdklip** [julian-klode/dns66#166]
Enabled the 'watch connection' feature and found my phone overheating and dns66 constantly stopping and starting the vpn. Cause: I moved my phone to an area with low to no reception and wifi disabled. Please add protection against this scenario. Maybe increasingly longer intervals in trying to restore vpn as well?

**Comment by julian-klode** [comment]
There are no loops, and it exponentially backs off the sending attempts with base 4, starting at 5 seconds up to 1 hour 8 minutes.

Likewise, the reconnect loop also has an exponential back off (base 2), first trying after 5 seconds, then 10, up to 2 minutes.

So I'm not sure why you think that either of them causes the problem. Unless I see some actual hard evidence I have to close this, as I don't see the situation you describe to be possible.

**Comment by julian-klode** [comment]
Grr, wrong button clicked.

**Comment by mvdklip** [comment]
Hmm, hard evidence would mean footage of the app misbehaving I guess. Not
sure how to do that. Will try to describe once again.

Grabbed freaking hot phone from bag, turned it on and it warned me that it
was overheating. I noticed that it had lost about 20% of battery while
being in standby for an hour.

Opened the status bar and saw dns66 continuously reconnecting. No pauses,
status changed twice a second or so.

Noticed that I had almost no cellular service so data probably was dead.
Stopped dns66 through its interface and everything was back to normal.
Disabled 'watch connection' as I believed that was the cause. Half an hour
later the same thing happened again though with mentioned feature disabled.

Can try to reproduce but would like to know first what kind of data you
need further.

**Comment by mvdklip** [comment]
Happened again. This time dns66 was active on cellular data and working
fine with wifi disabled. Enabled wifi which connected to protected hotel
wifi. Login was automatic. Dns66 however starting looping through
'stopping', 'starting' and 'reconnecting' statuses again with no pauses.

It seems I cannot have dns66 active reliably while switching network
connections.

**Comment by mvdklip** [comment]
Found a workaround. I'm on MIUI on a Xiaomi phone and found that disabling
battery restrictions for the app fixed the problem. With (default) battery
restrictions in place I could open the android status bar, disable and see
dns66 to start misbehaving immediately.

Added an exception for dns66 to have no restrictions, did the same thing
with the wifi a couple of times and no problems. Removed the exception =>
problems again. Readded the exception => no problems.

**Comment by julian-klode** [comment]
I should add that the watch connection feature is off because it can randomly just stops working and times out. That's of course not my fault, but a bug in Android.

**Comment by mvdklip** [comment]
I found that 'NetGuard' (kind of similar app) includes a warning of some sort that power saving should be disabled for it to function properly. Haven't had any trouble with DNS66 since disabling battery restrictions in MIUI. Ofcourse power saving implementations will differ per specific vendor...
