### ISSUE TITLE
Ad Issue

### ISSUE THREAD

**Issue by arijitirf** [julian-klode/dns66#169]
![screenshot_2017-08-06-23-06-20](https://user-images.githubusercontent.com/30778594/29005610-5810c3fa-7afc-11e7-9eb7-34e2deb7191d.png)

This ad is not filtered by your app though this type of ad did not display on the prevois version of this app. Thanks in advance.

**Comment by CHEF-KOCH** [comment]
Some apps are pre-hardcoded which means they even appear without internet access and can't be blocked via a simple hosts file.

Besides this, please share more information like which app, which device, which dns66 version, which filter lists or a log. 

Normally filtering related topics belong into the filter list discussions, cause this is not a bug.

**Comment by julian-klode** [comment]
In general, failure to block some ads is most likely never a bug, but something that just can't be blocked or can't be blocked by the chosen model (only with more battery use)
