### ISSUE TITLE
"Connected to Ad Buster"

### ISSUE THREAD

**Issue by waqas** [julian-klode/dns66#17]
Shows this VPN Notification on my device.
Was this forked from https://github.com/dbrodie/AdBuster ?

**Comment by julian-klode** [comment]
The core is a derivative of that (ported from Kotlin to Java to increase community engagement), yes, as basically mentioned everywhere in the docs :)

Anyway, fixed that for you!

**Comment by waqas** [comment]
Thanks. That was quick :)
