### ISSUE TITLE
block internet access for certain apps

### ISSUE THREAD

**Issue by 9001** [julian-klode/dns66#170]
would it be possible to add a blacklist for apps that should be totally blocked from internet access? would be convenient for apps that use internet access for no other purpose than metrics, instead of polluting the hosts files with entries that aren't strictly advertisement

**Comment by passwort123** [comment]
As i understand the Android VpnService API, this is not possible.
One can only select which apps should be using the VPN, and there can't be multiple VPNs.
Also I don't think its possible to infer the sending package name from the received network traffic.

So it's either Dns-blocking OR Internet-access blocking, for all / selected apps.
Correct me if i'm wrong.

**Comment by hackel** [comment]
No, it's not possible.  For that, get an actual firewall like AFWall+.  A host filter serves a very different purpose.

**Comment by noxarivis** [comment]
Im for this feature

**Comment by julian-klode** [comment]
See #30
