### ISSUE TITLE
Telegram stuck on "connecting" when DNS66 is enabled on Sprint LTE connection

### ISSUE THREAD

**Issue by aidenxy** [julian-klode/dns66#179]
Not sure if this is related to IPv6, but Telegram is unable to connect when DNS66 is turned on while only on mobile. 

It has worked on T-Mobile LTE, but the moment I connect on my Sprint phone to the LTE network (and turn on DNS66), Telegram is stuck on connecting. 

When I switch off DNS66 on Sprint LTE, Telegram connects just fine.

Is this a Telegram issue or a DNS66 issue?

**Comment by julian-klode** [comment]
Whitelist Telegram, and add it to https://github.com/julian-klode/dns66/wiki/BrokenApps. Some apps just don't work correctly with a (partial) VPN service.
