### ISSUE TITLE
Option to disable the notification banner

### ISSUE THREAD

**Issue by EZTEQ** [julian-klode/dns66#18]
An option to disable the notification banner would be great.
It takes up a lot of space that i could use for more important notifications.

**Comment by julian-klode** [comment]
The problem is that without the notification, Android might just kill the service under memory pressure:

https://developer.android.com/reference/android/app/Service.html#startForeground(int, android.app.Notification)

It's questionable if we want to take that risk.

**Comment by EZTEQ** [comment]
Ah, didn't know. This is a good reason not to change anything.

**Comment by julian-klode** [comment]
Let's still keep this open. I have not seen Android kicking out Opera VPN yet, and that has no notification, so perhaps it's acceptable enough on modern devices (then again, my phone has 6 GB ram...).

**Comment by niclasdh** [comment]
It would make sense for Android to keep Apps active which extends VpnService (https://developer.android.com/reference/android/net/VpnService.html). But there is no documentation how this influence Lifecycle. So we could double check that.

**Comment by julian-klode** [comment]
@niclasdh That would be nice. As I said, it tends to work fine for me with Opera, so it's probably half-way sane to provide such an option in any case.
