### ISSUE TITLE
[Request] Quick tiles to activate/desactivate DNS66

### ISSUE THREAD

**Issue by paulccci** [julian-klode/dns66#180]
Hi,
It would be really handy if there was a possibility to add a DNS66 quick tiles to activate or desactivate adblocking.
There is a lot of case where DNS66 is making something not work being able to quickly desactivate and reactivate it would be far easier than starting the app.

Thanks a lot for the app by the way. It's awesome !

**Comment by julian-klode** [comment]
Already discussed in #62

**Comment by julian-klode** [comment]
And of course, if you stop it from the notification, you get a new notification allowing you to start it again. So most of the problem (temporarily disabling) is dealt with that already :D
