### ISSUE TITLE
Signal calls are blocked when DNS66 is active

### ISSUE THREAD

**Issue by bernandosoares** [julian-klode/dns66#181]
Calling someone or receiving calls through the Signal private messaging app is completely impeded when DNS66 is active, even without any actual host lists enabled.

**Comment by julian-klode** [comment]
Whitelist signal.

**Comment by julian-klode** [comment]
Also, add it to https://github.com/julian-klode/dns66/wiki/BrokenApps so we can collect that.

**Comment by stef204** [comment]
@julian-klode 
Julian, thanks for this great app. I am posting here as I am experiencing, as well as others, issues with Signal Calls **even** when I have whitelisted the app.  The calls are at times garbled, at other times perfectly clear.  The whitelisting seems to have some sort of issue where it is unstable with regards to this messenger app.  Is there anyway this on/off whitelisting problem can be looked at again and addressed?
(I have no problems with a SIP client which I have whitelisted, by the way.)
