### ISSUE TITLE
Third-party connections filtering

### ISSUE THREAD

**Issue by uBlock-user** [julian-klode/dns66#186]
Hey there! 

I have been using this app for quite a while now and I have noticed that it's missing a feature which could immensely benefit users, which is allowing them to block third-party connections when they're browsing on Android via any browser(Chrome, Firefox)

Currently, the app relies on Hosts File to allow/deny connectivity however adding an option to block third-party connections would further help the cause. 

Thanks and I hope you consider it.

**Comment by julian-klode** [comment]
All we can do is block names, we have no context where the request was coming from (apart from _maybe_ an app).

**Comment by uBlock-user** [comment]
Webguard is able to do it in Android. I'm sure you will be able to do it too.
