### ISSUE TITLE
Battery Drain

### ISSUE THREAD

**Issue by akhilsanil** [julian-klode/dns66#189]
It wats up battery a lot and fails to block ads in Torrent apps

**Comment by akhilsanil** [comment]
Eats up*

**Comment by craigalan** [comment]
Never had issues with battery drain...ever.  Perhaps it's something else causing your issue.

**Comment by julian-klode** [comment]
Do you have the connectivity watch dog thing enabled? That misfunctions (well, Android does) sometimes and might cause trouble.

**Comment by julian-klode** [comment]
Closing due to unresponsiveness.
