### ISSUE TITLE
Yahoo Mail blocked

### ISSUE THREAD

**Issue by zilexa** [julian-klode/dns66#190]
I have used DNS66 for a few months now. Since yesterday however, Yahoo Mail is blocked with the default settings. I tried adding a filter for Yahoo.com, but whether I choose "allow" or "ignore" it is still blocked. I have to disable DNS66 entirely.

**Comment by julian-klode** [comment]
I don't think there's anything I could do about that. Did you try whitelisting the app in the apps tab?
