### ISSUE TITLE
Mobile Hotspot

### ISSUE THREAD

**Issue by HeidiElyas** [julian-klode/dns66#191]
DNS not applied while using mobile hotspot. When viewed in the browsers on other devices,    such as in my notebook, I can see my ISP DNS (tested on https://ipleak.net. Therefore I have to manually set the DNS in Control Panel. Already switched off and on or rebooted my phone but still no charm.

**Comment by julian-klode** [comment]
Unfortunately Android does not allow tethered devices to use the VPN connection.

**Comment by HeidiElyas** [comment]
Oh, that pity. Btw, thank you for the reply. 😊
