### ISSUE TITLE
Many ads not blocked

### ISSUE THREAD

**Issue by thany** [julian-klode/dns66#192]
Trying to move to another solution than AdAway because that one requires root. If DNS66 aims to block the same things, simply based on a hosts file, then it oftenly doesn't work. A couple of apps now started showing ads, while they didn't with AdAway in place. AdAway is now disabled in favour of DNS66, but it's not looking well atm...

In both apps I had set to their defaults and applied and everything. I don't believe I have done anything wrong in setting up DNS66. I let it update its files, and just hit the start button.

(looking at the list of sources, AdAway and DNS66 should be using identical hosts files, and yet, the results are so different...)

I'm on a (as of yet rooted, but not for long) Galaxy S7, Android 7.0.
DNS66 is at 0.5.4, downloaded via F-Driod a few days ago.

**Comment by julian-klode** [comment]
Try having no apps bypass DNS66 by default in the apps tab. By default it excludes system apps (some apps are horribly broken with a VPN).

**Comment by thany** [comment]
I've been using Tunnelbear successfully, even with system apps. So I suppose in my case it might be safe to include system apps then... But, it wasn't system apps that I was testing DNS66 with. They were apps installed by me.

However, having tried it, it does seem to help. Maybe "system apps" is not what I think it is :)

**Comment by julian-klode** [comment]
It's definitely odd, they might have moved ad download to play services or something, I don't know.

**Comment by thany** [comment]
Either way, it seems fixed. After a couple days of use, the ads stay away. I suppose you may close this issue if you wish.
