### ISSUE TITLE
Alternative DNS doesn't work

### ISSUE THREAD

**Issue by monkeymagic29** [julian-klode/dns66#195]
I set it up to listen to dnscrypt on localhost (setup on termux), but it doesn't do anything. It still listens to either 8.8.8.8:53 or mobile ISP's one. Can you find out why? Provided logcat isn't that helpful. Non-root system btw, but I still should've been able to listen to port 53535 or something normally. I can even dig via 53535.

**Comment by julian-klode** [comment]
Only port 53 is supported.

**Comment by julian-klode** [comment]
I assume if you specify host:port, it will just try to parse that as an IP (which fails) and ignore it and log it.

**Comment by monkeymagic29** [comment]
Aw. Is it possible for you to provide that functionality? A lot of mobile ISPs implement transparent proxying now, and this workaround should enable many users bypass censorship. Port 53 going to external servers is a futility here.

**Comment by julian-klode** [comment]
On Mon, Sep 11, 2017 at 04:39:48PM +0000, monkeymagic29 wrote:
> Aw. Is it possible for you to provide that functionality? A lot of 
> mobile ISPs implement transparent proxying now, and this workaround 
> should enable many users bypass censorship. Port 53 going to external 
> servers is a futility here.

Yes, it's possible.

**Comment by julian-klode** [comment]
Oops, that's already tracked in #22, so I'm closing this.
