### ISSUE TITLE
Add additional block lists

### ISSUE THREAD

**Issue by ion-storm** [julian-klode/dns66#196]
Please add all lists from pi-hole:
Lists used to generate Pi-hole's Gravity
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts 

https://mirror1.malwaredomains.com/files/justdomains 

http://sysctl.org/cameleon/hosts 

https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist 

https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt 

https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt 

https://hosts-file.net/ad_servers.txt

**Comment by julian-klode** [comment]
Eventually it will be reworked to just use StevenBlack's host file by default I guess. Anyway, new defaults don't roll out to users anyway, so there's not really much point in adding tons of lists there, it's just for providing a sensible set of defaults.

**Comment by kevinchugh** [comment]
I added these manually and I have almost 100% coverage. I would ask you reconsider this and add these to the default list. Made a huge improvement for me. Thanks the the great app!

**Comment by julian-klode** [comment]
Closing this. If you find anything worthwhile adding by default, ask for it to be added to StevenBlack's hostfile IMO, and use that.
