### ISSUE TITLE
Add pi-hole features or implement localhost pi-hole

### ISSUE THREAD

**Issue by ion-storm** [julian-klode/dns66#197]
How viable would it be to locally host pi-hole dns server on our phones and implement an interface to their awesome gui with graphs and statistics?  If this isn't possible I'd love to see stats of what sites we're blocked with a whitelist and blacklist function.

**Comment by julian-klode** [comment]
You could forward to an on-device DNS server once #22 is resolved, or if you a rooted. Statistics is tracked in #35
