### ISSUE TITLE
not restarting on S8

### ISSUE THREAD

**Issue by Jostian** [julian-klode/dns66#199]
when my phone is woken from sleep the DNS66 not running any longer (no key icon in status bar), seems like a bug.

**Comment by LabAviator** [comment]
I'm having the same issue. Also using a S8 running on Nougat. I used to work in the past.

**Comment by julian-klode** [comment]
For me it's usuallly the "could not reconnect" kind. In any case, make sure that DNS66 is "Not Optimized" in Android's battery saver settings (Settings -> Battery -> *something*)

**Comment by winnieXY** [comment]
already did that

**Comment by winnieXY** [comment]
the next time this happens I'll send you the log. this happens today at least 3-4 times

**Comment by winnieXY** [comment]
--------- beginning of main
09-27 20:40:10.371 11929 11963 I AdVpnThread: Exiting
09-27 20:40:10.371 11929 11929 I AdVpnThread: Vpn Thread stopped
09-27 20:43:01.784 11929 11945 I Adreno : QUALCOMM build : a9083cf, Iaf618d42e3
09-27 20:43:01.784 11929 11945 I Adreno : Build Date : 03/14/17
09-27 20:43:01.784 11929 11945 I Adreno : OpenGL ES Shader Compiler Version: XE031.09.00.04
09-27 20:43:01.784 11929 11945 I Adreno : Local Branch : 
09-27 20:43:01.784 11929 11945 I Adreno : Remote Branch : 
09-27 20:43:01.784 11929 11945 I Adreno : Remote Branch : 
09-27 20:43:01.784 11929 11945 I Adreno : Reconstruct Branch : 
09-27 20:43:01.929 11929 11945 I HAL : loaded HAL id=gralloc path=/system/lib64/hw/gralloc.msm8937.so hmi=0x0 handle=0xde8fec45badc4c5f
09-27 20:43:01.976 11929 11945 I OpenGLRenderer: Initialized EGL, version 1.4
09-27 20:43:01.976 11929 11945 D OpenGLRenderer: Swap behavior 1
09-27 20:43:03.903 11929 11929 W art : Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView

**Comment by winnieXY** [comment]
this is right after the key symbol and the dns66 entry in the drop down list have vanished.

**Comment by julian-klode** [comment]
Well it says it stopped, nothing else, so it's not particularly helpful.

**Comment by julian-klode** [comment]
Closing this, since there's not sufficient information to further debug it.
