### ISSUE TITLE
Regularly fetch new hosts files

### ISSUE THREAD

**Issue by julian-klode** [julian-klode/dns66#2]
We should update host files on a regular interval. It might make sense to write a SyncAdapter for that.

**Comment by z751** [comment]
Will there be a toggle switch to disable this and/or manually update it instead?

**Comment by julian-klode** [comment]
@z751 Sure, it would be kind of rude to just force that on everyone. Maybe something like

Automatic updates: Off / On Unmetered Connections / Always

**Comment by julian-klode** [comment]
We basically want to be able to configure:

- Connection types to run on (metered vs unmetered)
- How often to run (never/12 hours/24 hours - more options?)

JobScheduler seems to be the preferred way of doing these kind of things, so that's what we'll do :)

**Comment by julian-klode** [comment]
Oh, and re #41 we might also want a toggle to automatically upload new DNS66 builds if a github apk file is installed.

**Comment by julian-klode** [comment]
OK, so what we can configure:

- How often to run, proposed values (but we can use any amount of milliseconds, basically):
  - Daily
  - Weekly
- Network types:
  - Any
  - Not roaming
  - Unmetered
- Only when idle ON/OFF
- Only when charging ON/OFF

Now, UI:

- Replace the host file location in the host file list with a "last updated" stamp
- Modify the top bar so it can be pulled out / expanded and then show the settings in there?

Not sure about the latter.

**Comment by julian-klode** [comment]
And well, how often should also have 'Never' as an option, and the host file list should show a refresh symbol for host files currently being refreshed.
