### ISSUE TITLE
Add dns.watch DNS servers to default set?

### ISSUE THREAD

**Issue by julian-klode** [julian-klode/dns66#20]
https://dns.watch/ seem to be non-logging uncensored DNS servers making them a great addition to the default list. Opinions welcome!

**Comment by ethanhunt123** [comment]
why not google's dns? https://developers.google.com/speed/public-dns/

**Comment by FernandoMiguel** [comment]
@ethanhunt123 my understanding is to avoid data and users to be tracked by google

**Comment by julian-klode** [comment]
Yes, as @FernandoMiguel wrote. Including Google's DNS servers would be sort of counter productive.
