### ISSUE TITLE
Whitelist specific sites

### ISSUE THREAD

**Issue by godey4me** [julian-klode/dns66#202]
I would like to know how I can disable dns66 only for specific sites, like espn.com so I can get the videos to play on the phone.

Also for sites like slickdeals.net, is it possible to redirects from the site? So when I am on that site I will be able to got to links from the site.

Thanks

**Comment by julian-klode** [comment]
You cannot disable DNS66 for specific sites, you can only disable specific ad domains. DNS66 does not know which site causes DNS requests only which domain is to be looked up. So if you visit foo.example.com and that embeds bar.example.com, all DNS66 sees is the request for bar.example.com (well it first sees the foo.example.com request, but it has no way to connect them with each other, like you could have just loaded foo.example.com and then switched to bar.example.com).

**Comment by godey4me** [comment]
Thanks for the response. 
How do I disable dns66 for specific domains? I tried adding the list of redirect domains in a text file I found online to the host list (see attached file ) and choose "allow" and then refresh. But all still were blocked.

Also with espn.com the ads are embedded as part of the video (I think). There seems to be no way of allowing that. I tried again adding *espn* to the host list to no avail.


[adaway-export.txt](https://github.com/julian-klode/dns66/files/1327680/adaway-export.txt)

**Comment by julian-klode** [comment]
A host file has a specific format. The first word of a line must be 127.0.0.1, 0.0.0.0, or ::1. The second word must be a complete, fully-qualified domain name such as www.example.com, or foo.example.com. There cannot be any wildcards like *.

**Comment by godey4me** [comment]
@julian-klode Thanks I will create my own host file for whitelist.
