### ISSUE TITLE
Clicking logcat crashes the app

### ISSUE THREAD

**Issue by Sarkie** [julian-klode/dns66#206]

**Comment by julian-klode** [comment]
Well, I need a logcat to see why. That said, yes, I can make it not crash the app and output the error in a toast or something.

**Comment by Sarkie** [comment]
I'm not rooted if that matters, I know they restricted logcat access in newer releases

**Comment by julian-klode** [comment]
Well, it now errors out with a toast in 0.5.6 / 0.5.7, so why don't you find out? Works fine on Oreo for moe.

**Comment by Sarkie** [comment]
It now works. Thanks.
