### ISSUE TITLE
Cannot update hosts

### ISSUE THREAD

**Issue by Sarkie** [julian-klode/dns66#207]
Certain hosts have a long load time, if it hits this timeout it'll fail to load and an error will occur.

Loading the hosts file in browser shows the link works.

**Comment by julian-klode** [comment]
So, we currently have timeouts for reading a packet and establishing a connection. Both are 10 seconds. 

If the read is timing out, reading a 1 MB file would take about 2 hours, given an average packet size of 1.5 kB. That's obviously not what we want.

Now, establishing a TLS connection involves 2 round trips, so 5 seconds per round trip. AKA pinging the server is more than 5 seconds if that times out. We could extend that to like 20 seconds or so, but who waits 20 seconds before exchanging data?

There is another 10 second timeout for the executioner (it waits 10 seconds for _all_ downloads to complete) which means it might exit too early, but should not cause any warning AFAICT.

**Comment by Sarkie** [comment]
I can provide the link when my phone charges.

See if there's anything funky going on

**Comment by julian-klode** [comment]
Well, how does it work for you now? I increased the connect time out to 30 seconds, that's unreasonably high now.

**Comment by Sarkie** [comment]
Emailed you the logcat and screenshots.

Cheers

**Comment by musici** [comment]
Maybe it's helpful in this context if for each host file to show when it has been updated last time, It would add confidence that each host file has been loaded at least once.
