### ISSUE TITLE
pls add option to not update hosts

### ISSUE THREAD

**Issue by tortino** [julian-klode/dns66#209]
Hi,
please can you add an option to stop auto updating hosts files?
I usually keep it off, and turn on only when needed, but I sometimes get the warning about updating hosts files.
Thanks.

**Comment by julian-klode** [comment]
It's off by default, even. The setting is in the Hosts tab in this expandable top bar.

**Comment by tortino** [comment]
well... I occasionally see a little warning in the notificaton area saying it cannot download the hosts, even if dnd66 is disabled, and I have activated the option to not load at startup.
Next time it happens I'll take a screenshot. Maybe it has to do with me activating and deactivating the 3g network?

**Comment by julian-klode** [comment]
Well, host updating is completely independent of DNS66 running or not.

**Comment by tortino** [comment]
ah! I was wrong. I thought I had deactivated it... I even remember doing it but no, I was wrong :-)
Maybe I did it on another device. sorry for the spam.

**Comment by julian-klode** [comment]
OK, no problem.
