### ISSUE TITLE
feature request: querry adlist & statistics

### ISSUE THREAD

**Issue by larcado** [julian-klode/dns66#210]
Hi, I would very much appreciate if there was a way to **check whether a particular domain is currently blocked or not**. This could be in the form of a search field, where the domain to be checked is entered and then all the hits are displayed.
In addition, I would find it great, if one could see which domains are the most blocked (number of queries). So a **top 10 blocked domains**. And possibly a top 10 allowed domains.

**Comment by julian-klode** [comment]
That's tracked in #35
