### ISSUE TITLE
ad banners not getting blocked in some rss threads

### ISSUE THREAD

**Issue by Jostian** [julian-klode/dns66#211]
not sure why but on my rss threads I often have a banner when I tap the thread link, it then opens up the following page (see picture), would be great if DNS66 could block these, thanks
![screenshot_20171019-133542](https://user-images.githubusercontent.com/32001018/31769209-fae04d16-b4d2-11e7-9f9b-b4821a95bd86.png)

**Comment by julian-klode** [comment]
Failure to block ads is not a bug. It's not guaranteed to work 100%, and the ad blocking host lists are operated by 3rd parties.
