### ISSUE TITLE
Dose block conversations connections on wifi

### ISSUE THREAD

**Issue by treakiandroid** [julian-klode/dns66#212]
I guess, please test it, that this app blocks conversations even if it is white listed within dns66. See:

https://github.com/siacs/Conversations/issues/2660

Maybe you could improve the white listing but I would guess that it is more an error in conversations connection availability checks...

Tested with both dns66 and conversations from fdroid.

Thanks in advance and keep up the good work

**Comment by julian-klode** [comment]
It was completely broken in 0.5.5, but it works fine now. Without whitelisting the app, if you whitelist it, it seems to break.

But then you are hitting a Conversations bug - Conversations is added to the VpnService's disallowedApps list.
