### ISSUE TITLE
On MIUI 9 Global v7.10.19 crashes every time

### ISSUE THREAD

**Issue by TJL73** [julian-klode/dns66#213]
On my Xiaomi Mi5, after last MIUI 9 Global update to v7.10.19 (released Friday 20 October 2017), DNS66 don't reconnect anymore, not even manually, and crashes when I try to reconnect it the second time.

Let me know if you need Logcat or any other information.

Regards,
TJL73

**Comment by julian-klode** [comment]
Yes, I need a logcat, I don't have that phone :)

**Comment by TJL73** [comment]
I sent you the logcats by mail.
;o)

**Comment by julian-klode** [comment]
Seems MIUI messed up and requires INTERACT_ACROSS_USERS for the VPN configuration somehow (do you use multi-user?). That permission is only available for system apps and apps signed with the system key, so we can't do anything here.

Same problem as https://github.com/AdguardTeam/AdguardForAndroid/issues/173 basically.

**Comment by TJL73** [comment]
After last update of MIUI Global (v7.11.3) all works again like a charm.

Many thanks for your time.
