### ISSUE TITLE
YouTube Android App Unblocked Adds

### ISSUE THREAD

**Issue by zero77** [julian-klode/dns66#214]
YouTube Android App Unblocked Adds
The you tube android app is full of adds video and other.
I have looked at the packets sent by the YouTube app but was unable to spot anything, is there any way to block them.

**Comment by julian-klode** [comment]
Can't be blocked on a network level. I think you'd have to root and use some frameworks for that or something.

**Comment by zero77** [comment]
What prevents adds from being blocked at a network level.

**Comment by julian-klode** [comment]
They are not distinguishable from normal videos IIRC

**Comment by zero77** [comment]
What about the non video adds.

**Comment by julian-klode** [comment]
I've never seen any non video ads. Anyhow that's all encrypted traffic even if we were blocking stuff past DNS level.

**Comment by zero77** [comment]
ok, thanks
