### ISSUE TITLE
Crashes when visiting YouTube in Chrome

### ISSUE THREAD

**Issue by alleluia20** [julian-klode/dns66#215]
DNS66 stops when visiting YouTube in Chrome. So far, It has happened to me at all times (I mean, the first time I open the Youtube web after switching on the phone).

**Comment by julian-klode** [comment]
Send me a logcat (for example, from the menu, as an email) directly after it crashed and I can have a look. Mention the bug report in the subject. Thanks!

**Comment by julian-klode** [comment]
I don't think I received a logcat for that crash, so I'm closing this now.
