### ISSUE TITLE
YouTube in Chrome, desktop view: stuck in ad video

### ISSUE THREAD

**Issue by alleluia20** [julian-klode/dns66#216]
I sometimes visit YouTube in Chrome in Desktop view, in order to be able to play the video in the background.
In Desktop view, the ad video cannot be played (as the play button does not respond), so I cannot get through to the real video (I mean, I would watch the ad video in order to get to the real video, but the ad video does not play).

**Comment by julian-klode** [comment]
Well, problems can be expected when doing ad blocking, especially on a host level. I'm not proving the host files, so there is not really anything I can do about this.

That said it does work for me.with the default host files.
