### ISSUE TITLE
Unchecking "show notification" does nothing

### ISSUE THREAD

**Issue by alleluia20** [julian-klode/dns66#217]
I unchecked "show notification", and confirmed it at the warning window, but the notification is still showing.

**Comment by julian-klode** [comment]
Did you restart DNS66? Are you using one of these Samsung things? The notification shown by the app says that DNS66 is running and has a button to temporarily disable it. Some vendors (um Samsung) add in other notifications for running VPN services, and Oreo adds the background process notification.

**Comment by alleluia20** [comment]
Stopping DNS66 and resuming it seems to work. You may want to close the bug (but adding a warning to restart would make no harm...).
(Anyway, just one minute after disabling the notification, DNS66 stopped. My phone has 3GB RAM and I am not using any heavy app right now).

**Comment by julian-klode** [comment]
Well, then keep the notification on and see if that keeps it running. On the other hand, if it's crashing, send a logcat (the menu has an option for that).

I guess I could show a toast once during the app life time (or rather during a visible part) after changing a setting.
