### ISSUE TITLE
No access to attachments in Gmail app (unless whitelisted)

### ISSUE THREAD

**Issue by alleluia20** [julian-klode/dns66#219]
Attachments in Gmail (in the Gmail app) cannot be accessed (with the Gmail app not whitelisted): no preview is shown and, if you tap on them, download never starts.
In case the only solution is to whitelist the Gmail app (and see a few ads there from time to time), you may close this bug (and excuse me for the inconvenience...). I am submitting it because it does not happen with Adaway, so there may be a solution...

**Comment by julian-klode** [comment]
No, there is not. AdAway does not use a VPN service, and the VPN service is what causes the issue.

**Comment by julian-klode** [comment]
* partial VPN service, if you run a full VPN I think it works fine, but that eats up battery.

**Comment by saloid** [comment]
Same issue occurs with me. Gmail file attachment downloads works only if I bypass DNS66 for Gmail app (or when I'm temporarily disabling it)
