### ISSUE TITLE
Back button of browser sometimes not working

### ISSUE THREAD

**Issue by alleluia20** [julian-klode/dns66#220]
Using Chrome on Android (and under DNS66's VPN). When I do a search in Google, follow the link to one of the results, and I then press "back", it often fails.
The URL bar briefly shows "google" but then (after less than one second afterwards) it forwards to the current page. In practice, it is as though the back button were reloading the current page.
This always (or almost always) happens when the search result is a video on YouTube or a tweet on Twitter. The only way to actually reach the previous page is to double tap (quickly) the back button, and sometimes it may be necessary to triple tap.

**Comment by alleluia20** [comment]
I noticed that inside an incognito tab in Chrome, and choosing to open the YouTube video inside Chrome (not in the YouTube app).

**Comment by gkaklas** [comment]
This probably doesn't have to do with DNS66 since it has to do with browser caching (?). Do you still have this problem? Does it happen _only_ when you are using DNS66? Have you tried opening a bug in your browser's issue tracker?

**Comment by julian-klode** [comment]
Not a DNS66 issue.
