### ISSUE TITLE
[Oreo] Not started on boot

### ISSUE THREAD

**Issue by owensgithub** [julian-klode/dns66#222]
On Android 8.0.0 the app is stopping everytime I restart the phone. I have to manually restart even though I have 'Resume on system start-up' swtiched on. Anyone else having this issue?

**Comment by Hummel95** [comment]
Yes, I'm experiencing exactly the same issue (Pixel, 8.0.0).

**Comment by taiyangc** [comment]
Same on 8.0.0.

**Comment by julian-klode** [comment]
Well, I mean, no other app seems to be starting on boot either, so it's a new Oreo feature? I don't know.

**Comment by julian-klode** [comment]
Unfortunately, someone seems to have messed up USB debugging on the OnePlus 3's Oreo beta - I can only get adb to connect after switching to MTP mode, so I can't start adb during boot, and it's too late afterwards.

**Comment by julian-klode** [comment]
From my reading, it seems no longer possible to use `startService()` in the background. But it did not work with `startForegroundService()` either. In fact, the broadcast receiver does not appear to be started at all.

**Comment by julian-klode** [comment]
Commit 0b13579b2ce68e84d513f734524da62bc914f7dc fixes the starting of the service (and it really requires enabled notifications), but since the broadcast receiver calling this code is never started by Android, it does not really help.

I'm not sure what's going on - I have a feeling receiving BOOT_COMPLETED has been restricted to system apps.

**Comment by julian-klode** [comment]
So I just found out that it crashes for one user on boot, so I'm not sure why it's not starting for all of us here, but is for that user. Weird stuff.

**Comment by kermitoo** [comment]
@julian-klode It starts at boot just fine for me, I just had to de-optimize the app in Settings > Battery otherwise it was crashing at boot. I'm using a OnePlus 3 on Oreo, hope it helps.

**Comment by julian-klode** [comment]
@kermitoo It really should be crashing according to the docs, you are probably lucky and OnePlus screwed up :) - I don't see any crashes in Open Beta 27, but it does not start either.

**Comment by alleluia20** [comment]
For me, with Android 7, DNS66 often fails to autostart. I then noticed that it was installed in the SD card and, although the card is formatted as internal storage, apps in the card may still have problems autostarting. 
Yesterday I moved DNS66 to the (real) internal storage, and it has auto started today. I will continue watching it.

Regarding Oreo, do you really mean that non-system apps, such as DNS66, but also WhatsApp or an email app, will not auto start?

**Comment by julian-klode** [comment]
Background services cannot start automatically when compiled against the latest target version. Foreground services (with notification) can. WhatsApp does not have to, it uses push. E-Mail was always a bit borked.

**Comment by julian-klode** [comment]
This works for me since some time now, seems OnePlus fixed the 3 in the latest Open Beta. I suggest everyone else with problems remaining with autostart of apps talk to their phone vendors.

**Comment by alleluia20** [comment]
I then guess that the notification in DNS66 should be mandatory, shouldn't it?

**Comment by julian-klode** [comment]
Well, only if you want to autostart it.

**Comment by LLParse** [comment]
Regardless of notification state, auto start at boot doesn't function on my phone.

Moto g6 play
Android 9/Pie
