### ISSUE TITLE
New feature: Log DNS requests made 

### ISSUE THREAD

**Issue by cherryleafroad** [julian-klode/dns66#223]
A feature to log DNS requests from apps would be invaluable to help track down specific DNS queries from apps, which will help users determine which ad servers to block.

My idea of the feature implementation:
- Log all DNS queries from apps (or only from specific selected apps)
- Able to view logs on a per app basis
- Users can long click a domain and easily add it to the apps user blacklist (or whitelist) 

As it stands, there's no easy alternative program that has this kind of functionality (especially good nonrooted devices)

**Comment by julian-klode** [comment]
It's still in #35.

Why does this kind of feature request duplicate pop up every month or so? I don't understand it, but it gets a bit annoying.

**Comment by julian-klode** [comment]
It's still in #35.

Why does this kind of feature request duplicate pop up every month or so? I don't understand it, but it gets a bit annoying.

**Comment by julian-klode** [comment]
It's still in #35.

Why does this kind of feature request duplicate pop up every month or so? I don't understand it, but it gets a bit annoying.

**Comment by cherryleafroad** [comment]
Well, I'm sorry if I annoyed you. :) I do hope you can understand the rationale however. :)

**Comment by cherryleafroad** [comment]
Well, I'm sorry if I annoyed you. :) I do hope you can understand the rationale however. :)

**Comment by cherryleafroad** [comment]
Well, I'm sorry if I annoyed you. :) I do hope you can understand the rationale however. :)

**Comment by cherryleafroad** [comment]
Well, I'm sorry if I annoyed you. :) I do hope you can understand the rationale however. :) 

As that issue you mentioned doesn't feel related to me (different their) I missed it. My bad

**Comment by julian-klode** [comment]
You're right. The other issue's description does not actually say that. Maybe that explains it. I can't edit it at the moment though, github has gone weird.
