### ISSUE TITLE
TEL:+xxxxx

### ISSUE THREAD

**Issue by didiasku** [julian-klode/dns66#224]
I have a note8 and s8+, when running DNS66 and googling a business, the web browser shows the normal results with the option of "call/directions/save/website" etc...When I click call, i get the error page of 
"this site can't be reached, the webpage at tel:+xxxxx (where xxx is the phone number)."

I assume this is due to the DNS not resolving, is there a way to bypass or add a custom filter?

**Comment by 13scoobie** [comment]
Hey didiasku, I also use dns66 and have a gs8+ but am able to call business through chrome and Firefox. Which web browser are you using?

**Comment by julian-klode** [comment]
Closing, since no further information has been provided for triaging.
