### ISSUE TITLE
DNS66 stops working when cell service changes, even on WiFi.

### ISSUE THREAD

**Issue by kigero** [julian-klode/dns66#225]
I live in an area with very spotty cell coverage - my connection will vary quite often between 1x, 3g, 4g, and no service throughout the day.  I have good WiFi though, so it hasn't been an issue.  With DNS66 running though, it seems when the cell connection changes the DNS stops working; whatever app I'm using starts getting connection errors until a minute or two passes (presumably the "watch connection" working) or I restart the service.  During this time the WiFi connection is unbroken.  Any idea why this would be happening and how I can prevent it?

**Comment by 13scoobie** [comment]
Have you tried turning on watch connection or turning off ipv6? Also, which phone are you using?

**Comment by kigero** [comment]
I've got an LG v20. I did have watch connection turned on already, but turning off IPV6 did seem to help. I'm currently traveling, but over the last several days I haven't noticed any connection errors that I can attribute to DNS66. I'll keep an eye on it over the next few weeks when I'm back home and reopen if I start seeing errors again. Thanks!

**Comment by z0m8i3** [comment]
I have the same issue; DNS66 works with data, but once I switch to wifi it stops the connection - can't browse the web, until I disable DNS66.

Is there a switch in DNS66 to disable ipv6?

Using Moto G4 Play with Lineage OS.
