### ISSUE TITLE
consider adding Quad9 resolver

### ISSUE THREAD

**Issue by juzam** [julian-klode/dns66#227]
As you may already know there is a new resolver named Quad9, aimed at privacy and malware blocking

[About Quad9](https://www.quad9.net/#/about)

The resolver is available via ipv4 and ipv6, (9.9.9.9, 149.112.112.112, 2620:fe::fe ) and also supports DNS over TLS.

I'm using it already in dns66 because I've added the two ipv4 addresses manually, but would you consider adding Quad9 to the list of default resolvers?

Thank you.

**Comment by julian-klode** [comment]
No. Quad9 shares a ton of data with partners, blocks sites, and will in the future redirect sites to their own fake sites if blocked. It's contrary to everything the defaults are supposed to be.
