### ISSUE TITLE
Localhost proxy option instead of VPN

### ISSUE THREAD

**Issue by jebeld17** [julian-klode/dns66#229]
There really should be a secondary way users can use DNS66, in case they already have a VPN set up for other things.

One good solution would be to add a Localhost Proxy option that redirects system data without the need of a VPN.

**Comment by julian-klode** [comment]
I assume you mean something like a HTTP or SOCKS proxy. That's out of scope for the project (which is all about having the most lightweight ad-blocking possible) - it would be very inefficient.

There's a reasonable proposal in #188 to expose a local DNS server. You could then configure that, provided your VPN supports a custom DNS server on a custom port.

There's also another proposal in #96 to add support for an upstream SOCKS proxy for DNS66 to send DNS requests over.
