### ISSUE TITLE
Mobile data firewall

### ISSUE THREAD

**Issue by Dondrejohnson5** [julian-klode/dns66#232]
This small feature world be very beneficial to me in DNS66: Blocking select apps from using mobile data, and when using the blocked app, send a notification that will allow the app to use data temporarily.

I would've used AdClear, but, especially for the Cartoon Network Video app, videos take longer to load, compared to DNS66.

**Comment by gkaklas** [comment]
I think this feature is out of scope for this app, since it only wants to provide DNS features. If you need firewall features there are other apps (e.g. [AFWall+](https://f-droid.org/en/packages/dev.ukanth.ufirewall/)) that specifically provide a firewall service. :thinking:

**Comment by uli42** [comment]
I am using "Firewall without Root" for this. And as this is also using VPN technology it unfortunately cannot be combined with DNS66. So a combined tool would be perfect!

**Comment by julian-klode** [comment]
Firewall stuff is tracked in #30, but likely won't happen.
