### ISSUE TITLE
Mobile Malware Domain List FAILS TO UPDATE

### ISSUE THREAD

**Issue by jebeld17** [julian-klode/dns66#235]
I am adding this as a new issue, even though it's been reported before, because the previous issues have been closed out and/or discredited by the moderators.
_____
ISSUE: DNS66 is reporting to the user that the Mobile Malware Domain List is timing out.
Even if it is the server that's the problem, it shouldn't be included as a default server in the app then, because it interferes with the working quality of the app.

Why not replace the Mobile Malware Domain List Server with a known good mirror or cloud storage link instead?

**Comment by jebeld17** [comment]
[--------- beginning of.txt](https://github.com/julian-klode/dns66/files/1549057/---------.beginning.of.txt)
LOGCAT

**Comment by julian-klode** [comment]
Well, I don't have an alternative.

**Comment by Hoi-Polloi** [comment]
The list https://www.malwaredomainlist.com/hostslist/hosts.txt seems to be provided over http only. Editing out the s manually solves the issue for me.

**Comment by jebeld17** [comment]
@julian-klode why don't we make a self-maintained mirror hosted on Google Drive, OneDrive, or the likes? It's just a simple text file :)

**Comment by jebeld17** [comment]
Then why not fix the default list in the app for everyone so users don't
need to go in and manually edit the "s" out?

**Comment by julian-klode** [comment]
So, changing the default only affects _new_ installs. But here's the thing:

* I won't add any unencrypted sources or downgrade any connection to unencrypted.
* Mirroring is ineffective, and the file does not have a license, so not really redistributable.

I'll probably eventually remove all the lists and switch them to use the integrated hosts file of StevenBlack. Then we'll have a simple mode and a custom mode or something.

**Comment by jebeld17** [comment]
That's a lot more logical :)

**Comment by RoestVrijStaal** [comment]
I wonder if you want to use MDL at all since domains of victim sites are also in the list. And there is no distinguishing between the evil domains and victim domains.

Blocking compromised sites is a good approach for a short time. But they still need to be treated different than malware domains.

**Comment by julian-klode** [comment]
I don't know really. I probably want to switch to easier defaults anyway, with just https://github.com/StevenBlack/hosts
