### ISSUE TITLE
Copyright violation

### ISSUE THREAD

**Issue by Poussinou** [julian-klode/dns66#238]
Hi @julian-klode 

I found [this app](https://play.google.com/store/apps/details?id=org.OrangeRed.dns66) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

By the way, [all his apps are open source software he copied](https://play.google.com/store/apps/developer?id=Vu+Viet+My+Team)...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove the false app from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by azumukupoe** [comment]
this too
https://play.google.com/store/apps/details?id=com.junta.dns66.dnschanger

**Comment by theel0ja** [comment]
That developer is now gone from Google Play.

![image](https://user-images.githubusercontent.com/5832930/35533449-41d0da06-0546-11e8-9706-2d57247d9c1a.png)
![image](https://user-images.githubusercontent.com/5832930/35533434-35a1d6fe-0546-11e8-94d4-ec9f62a37d82.png)

**Comment by julian-klode** [comment]
It's good that the copier was taken down. I don't think I can do anything about the imposter app with the same name, as I did not register a trademark. If somebody figures out a way, please let me know, though.
