### ISSUE TITLE
Dns66 is not working with UC browser

### ISSUE THREAD

**Issue by Babar-Bashir** [julian-klode/dns66#243]
Host files aren't working with [UC Browser](https://play.google.com/store/apps/details?id=com.UCMobile.intl)

According to the [Wiki/UC](https://en.wikipedia.org/wiki/UC_Browser) they are using  **cloud acceleration and data compression technology**. Is there any way to bypass data compression in UC?

Dns66 blocked the dns request but sites are opened in uc browser
09:56:40.046 13612-5074/? I/DnsPacketProxy: handleDnsRequest: DNS Name www.xnxx.com Blocked!
09:56:40.056 13612-5074/? I/DnsPacketProxy: handleDnsRequest: DNS Name www.xnxx.com Blocked!

Thanks 
Regards,
-Babar Bashir

**Comment by sonho666** [comment]
This is not an DNS66 issue, UC Browser is, probably, force feeding you their own DNS. So you should either find the option to disable it in UC Browser or, my suggestion, find a better browser without this shady  behavior.

**Comment by julian-klode** [comment]
If DNS66 blocks the requests, it's working correctly. As @sonho666 said, your best bet is to use a different browser that does not ignore that.
