### ISSUE TITLE
Give option for daily refresh of servers "at any circumstances"

### ISSUE THREAD

**Issue by alleluia20** [julian-klode/dns66#244]
Currently, the daily refresh of servers only takes place with the device plugged in, idle, and on a WiFi connection. But some people (like me) usually charge the phone when it is switched off.
Given that refreshing the servers take (I guess) very little battery, very little memory, and very few data, I propose the three conditions not to be mandatory.
For example, one option for the user to enable (or disable) would be: "refresh daily"; and a second option (that the user would choose to enable or disable) would be: "only with the device plugged in, idle, and on a WiFi connection".
I am aware that I can manually update, but I (and other users) may tend to forget to do that...

**Comment by julian-klode** [comment]
See #112
