### ISSUE TITLE
Disable DNS on WiFi

### ISSUE THREAD

**Issue by mrdrogdrog** [julian-klode/dns66#248]
One of the most useful features for me is the custom DNS server. But when I'm at home or some other trusted locations I want to use my own DNS server to reach specific devices. Can you add a toggle to disable the custom DNS on WiFi?
Bonus: disable the DNS on specific WiFi's

**Comment by sonho666** [comment]
This option would be lovely as, at home, I have adblocking through router DNSmasq.
I believe that opening DNS66 to tasker (#146 ), so it can stop/start the VPN service, would suffice as it can apply to any user case. And (maybe?) is easier to implement.

**Comment by mrdrogdrog** [comment]
That would work for me too.

**Comment by julian-klode** [comment]
I will not provide such a feature, but I'm open for tasker support in #146.
