### ISSUE TITLE
Handcraft hosts files doesn't work?

### ISSUE THREAD

**Issue by dragonxtek** [julian-klode/dns66#249]
I created a hosts file with the dns queries from [Ampere](https://play.google.com/store/apps/details?id=com.gombosdev.ampere&hl=es) application (I got them with tcpdump on my router). These are the following entries from hosts file:
```

# [Ampere]
127.0.0.1 pagead2.googleadservices.com
127.0.0.1 pagead2.googlesyndication.com
127.0.0.1 pagead46.l.doubleclick.net
127.0.0.1 googleads.g.doubleclick.net
127.0.0.1 analytics.liftoff.io
127.0.0.1 haggler-doubleclick296-us-e-ec2.liftoff.io
127.0.0.1 haggler-doubleclick257-us-e-ec2.liftoff.io 
```

When I re-run the application, also I tested rebooting Android, ads still there

<p href="url"><img src="https://user-images.githubusercontent.com/10552658/35993411-0f7050fc-0cec-11e8-9fcf-b5d79b08cb1a.png" align="center" height="240" width="200" ></p>

Why the app can bypass it?

**Comment by julian-klode** [comment]
Apps generally cache the ads and reuse them.

**Comment by dragonxtek** [comment]
But, if the app used his cache, why I see the dns query again?

**Comment by Atavic** [comment]
Is Ampere whitelisted?
Re: https://github.com/julian-klode/dns66/issues/245

**Comment by Atavic** [comment]
Try blacklisting *liftoff.io* as a whole and not only subdomains.

**Comment by dragonxtek** [comment]
I added this entry:
127.0.0.1 liftoff.io
and activated Deny access to hosts in this file, but Ampere again calls to analytics.liftoff.io dns query

**Comment by julian-klode** [comment]
Well analytics.liftoff.io is not the same as liftoff.io

**Comment by julian-klode** [comment]
Anyhow apps are difficult, some have more luck if system apps are not whitelisted. Nobody really knows what's going on there.

**Comment by SvobodaJakub** [comment]
@dragonxtek Maybe https://github.com/julian-klode/dns66/pull/185 will be able to help - the extensive matching feature implies a wildcard in front of every whitelisted & blacklisted URL, so that blacklisting `liftoff.io` will automatically blacklist also `analytics.liftoff.io` and all other similar subdomains.

**Comment by dragonxtek** [comment]
I tried it (I mentioned it on my last post) but without lucky

**Comment by julian-klode** [comment]
Figuring out how to block specific ads is out of scope for this bug tracker.
