### ISSUE TITLE
Cellular internet connection stopped working without DNS66.

### ISSUE THREAD

**Issue by trafium** [julian-klode/dns66#251]
I had problems downloading via mobile network anything through Google Play and I started to disable/uninstall apps which might have caused it. When i uninstalled DNS66 I got stuck with internet connection not working in Chrome app and some other places at all (every request fails with ERR_CONNECTION_TIMED_OUT). I still could use other apps which use internet, like Spotify and Facebook and they seem to work just fine except for some images not loading here and there. So I installed it back and everything (except for Google Play) works again. 
Any chance I can stop using this app and still get the internet working? ^^
I'm on OnePlus 5T with Oreo 8.0

**Comment by trafium** [comment]
So I tried different toggles in app to see if anything works and now i'm stuck in a loop Active -> Reconnecting error. Reinstalling application and loading default settings did not help.
Uploaded logcat here:
https://drive.google.com/file/d/1d2ugABKhDjOP8CmRf3eVg7oYRxbqq8VP/view?usp=sharing

**Comment by f1vefour** [comment]
Try toggling airplane mode.

**Comment by janereigytasuda** [comment]
@julian-klode i have same issue. with mobile data,
i use latest v060 , all apps can open, but download app play store not work.
when i stop dns66, all apps no have internet working.

pls ur help Sir :smiley:

**Comment by trafium** [comment]
To anyone wondering I did not find any solution, just kept using it with those problems for about a yeah until my phone updated to Android 9.0 and IIRC problem resolved itself (probably because all DNS related configuration on a device got reset) and I never used dns66 again. I guess phone factory reset might work, but never tried it myself.

**Comment by julian-klode** [comment]
Not a DNS66 bug here.
