### ISSUE TITLE
DNS66 has zero effect since last update (Pixel1, WiFi and Cellular)

### ISSUE THREAD

**Issue by zilexa** [julian-klode/dns66#252]
Even after updating all hosts files, starting and stopping the service, rebooting several times, I get to see ALL ads while DNS66 is running. Behaviour was normal before the update.

Let me know what you need to investigate. Logcat?

**Comment by piz333** [comment]
Also, the service won't run continuously - it's stops regularly. (The latest version as of this comment is my first, so I can't speak to changes since previous versions).

I'm on a Pixel XL running the latest Android version as of this comment.

**Comment by Matmo10** [comment]
It stops constantly for me too. Pixel 2 XL, Android 8.1

**Comment by Sjonesgb** [comment]
I've got the same problem. Works fine then turns off. No problem restarting. Using Huawei p8 lite 2017. Problem only recently started occurring but I really appreciate gherkin developer's time that had been spent on this app.

**Comment by julian-klode** [comment]
I'm afraid that Android is a mess, and it might not be working for everyone. Note that in-app ads are essentially out of scope, only browser ads can be blocked reliably. Things will likely get worse in P, too.

If you have a logcat, check if DNS66 sees any DNS requests. If there are any errors forwarding or something, that would be an error in DNS66. If it does not see any, however, I'm afraid there's not much that can be done.

Regularly stopping is an entirely different issue. Your phones might just be too fast, and you experience an Android bug where VPNs stop working if they reconnect too quickly. That's a shitty answer, I know, but I'm not sure what to do with that. Adding random sleeps everywhere can't be the solution, right?

**Comment by zilexa** [comment]
Just an update: on my Pixel 1 with Android 8.1.0, lot's of browser ads (I would say all of them but I might not pay attention that much) are definitely being blocked. Even after 14 days without rebooting my phone. So DNS66 is running fine and restores itself while switching from WiFi to mobile network (or even to airplane mode).
Within apps, lot's of ads are being blocked as well but not all. 

The issue of regular/randomly stopping is therefore solved for me.

**Comment by Sjonesgb** [comment]
Thank you I'll try it on my Honor 9.

Best regards

Steve Jones
+44 (0)7767 611295

**Comment by zilexa** [comment]
@Sjonesgb you should remove your phone number!

**Comment by julian-klode** [comment]
@zilexa I edited his comment

**Comment by Sjonesgb** [comment]
Thank you
