### ISSUE TITLE
Google ads not blocked

### ISSUE THREAD

**Issue by pm1111** [julian-klode/dns66#255]
As you know Google ads don't get blocked properly. I found the following information:
If the problem of ads slipping through isn't caused by DNSSEC it might be caused by DNS over TLS invented by Google and implemented on their name servers. It uses port 853 and is described in RFC 7858.
Can it be that you missed the dns requests by Google because they do it via DNS over TLS?

**Comment by lramage94** [comment]
This might explain why I am still getting ads when watching videos on webtube (youtube frontend).

**Comment by pm1111** [comment]
Julian Klode still hasn't answered, do maybe I've written rubbish. I just wanted to make a suggestion why Google manages to place ads past dns66

**Comment by julian-klode** [comment]
DNS66 does not block any apps from using other DNS servers. It just configures new ones and puts them at the top of the list. Google's ad implementation may very well be using DNS over TLS over DNS over https to gather hostnames, or just use other host names not blocked by host files.

YouTube is completely different, as YouTube ads are essentially just videos, they don't stream from a different ad-specific host name.
