### ISSUE TITLE
Works GREAT! one minor issue and suggestion

### ISSUE THREAD

**Issue by beng2beng** [julian-klode/dns66#256]
After playing with the settings I think DNS66 is pretty darn good. blocks most if not all ads that would normally show up. 
 sometimes however; even though its active; it doesn't block anymore. I have realized I could stop and start it and it works again ( although once I needed to restart the phone )

my only suggestion (if this is even possible)
a self health check and or an auto restart of itself (user configurable interval)

**Comment by julian-klode** [comment]
there is a "self health check". (the monitor connection thingy). That said, Android is super buggy and it breaks a lot and then goes into restart loops...

**Comment by beng2beng** [comment]
any chance to add a feature to stop and start dns66 whenever the phone display goes from off to on?
or even an interval stop/start (user configurable; like X minutes) or idle to active; 

i manually do the stop/start on a regular basis but sometimes i forget and get hit with an unexpected AD

sorry dont know whats possible with android. just would love something to keep dns66 working without having to do it myself each time.

**Comment by julian-klode** [comment]
Restarting DNS66 is a terrible idea, as it will wake up a ton of applications which will try to reconnect and sync stuff. Hence I don't provide an option to do that on screen on/screen off, as it would very likely have a bad effect on battery life with common usage patterns.
