### ISSUE TITLE
Allow configuring lock screen behavior

### ISSUE THREAD

**Issue by rboyer** [julian-klode/dns66#266]
In AdGuard (similar app to DNS66) there is a notification configuration that lets you control whether or not it shows up in the list of lock screen notifications. 

This is separate from the setting that shows it persistently in the notification bar when unlocked, and does not negatively impact the app's uptime.

Could you expose this setting in DNS66?

It shows up under:

$app > info > app notifications > on the lock screen > $choices

Where $choices are:

* Show all notification content
* Hide sensitive notification content
* Don't show notifications at all

For reference I'm on Android 8.1 on a Pixel 1.

**Comment by julian-klode** [comment]
The option to hide notifications will likely go away completely on Oreo. You can configure individual notification channels by long pressing on the notification. To show the notification on the lock screen, set the priority of the active notification higher and then configure lock screen.

**Comment by rboyer** [comment]
I can provide more details about Oreo if you do not have access to a device with that version.
