### ISSUE TITLE
Still showing Ads On YouTube Videos

### ISSUE THREAD

**Issue by GKid94** [julian-klode/dns66#267]
Can you please fix the ad blocking on videos because there are still ads on videos in the YouTube app?

**Comment by JRLS** [comment]
i'm running it on nvidia shield pro.

2 problems:
- i still have ads in youtube add on
- the hostfiles fail to download. I get a message that old lists are used. If i click the refresh buttons, nothing seems to happen, and i get no message

I got the following settings in dns66:
-watch connection : ON
- IPv6 : OFF
- Filter HOSTS : ON
- hpHosts's Ad and tracking servers : ON
Then i click "START" button, i get the VPN connection request, i click "OK"

Then i start youtube app on nvidia shield, but still get ads :(

how can i solve this?
Thanks :)

**Comment by julian-klode** [comment]
That won't work. It's not possible to block them at a host level.

**Comment by Ch1llb0** [comment]
The issue is still present... Youtube ads are not blocked at all with the standard settings.

**Comment by GKid94** [comment]
Just download AdClear from Google, it also blocks YouTube ads

**Comment by julian-klode** [comment]
This is not an issue. YouTube cannot be supported, as they serve ads like any other videos.

Other apps work fairly well AFAICT with the latest build on XDA (or just switching to StevenBlack's host file in current releases).

I suggest you use NewPipe or another YouTube client for ad-free youtube watching.
