### ISSUE TITLE
Option To Remove The On Going Notification And The VPN Icon

### ISSUE THREAD

**Issue by GKid94** [julian-klode/dns66#268]
Can you please add and option to remove the on going notification and the VPN key icon?

**Comment by julian-klode** [comment]
There is an option to remove the one notification we create. And that will go away soon for Oreo.

Other stuff like apps running in background, or the key icon we cannot influence.

**Comment by GKid94** [comment]
Why only for Oreo? Why not for Android 4,5,6 and 7?

**Comment by GKid94** [comment]
I was talking about the on going notification in the Status Bar that says "DNS66 Active" and the VPN key icon, can you add an option to hide them?

**Comment by julian-klode** [comment]
The DNS66 Active notification has an option to hide it in the menu. That option will go away on Oreo as it's broken.

The VPN key icon (or the "running the background" notification, or vendor-specific notifications) I cannot control - they cannot be removed.

**Comment by GKid94** [comment]
When I disable the "Show notification" option the "DNS66 Active" notification is still there

**Comment by julian-klode** [comment]
You have to restart the service.

**Comment by GKid94** [comment]
I did, it's still the same
