### ISSUE TITLE
does not filter specific URL

### ISSUE THREAD

**Issue by Benman2785** [julian-klode/dns66#270]
hi,
i want to filter "www.skygo.sky.de/sg/multiplatform/android_tablet/json/editorial/customerCommunication_v2.json"
so i set up a custom filter like: http://benmanshafen.de/sky.txt

but it didnt work
when i block it in my router it do work

**Comment by julian-klode** [comment]
It's a DNS filter it can only block host names, not URLs.

**Comment by Benman2785** [comment]
sry to get on your nerves - but do you know a way to block this specific URL without root - on a FireTV?

oh and i could also need a way to fake a device-modell-number without root - would be awesome if you could help with that - even i know that i should ask on xda

dennoch einen schönen Freitag den 13ten ;)
