### ISSUE TITLE
MX player app ads

### ISSUE THREAD

**Issue by ghajini** [julian-klode/dns66#271]
Using dns66
I see MX player ads......Seem to be by Google AdWords, Adsense,admin
![screenshot_2018-04-13-20-07-52-543_com mxtech videoplayer ad](https://user-images.githubusercontent.com/20338483/38741350-49ae590c-3f29-11e8-944a-82b441343bfb.png)

![screenshot_2018-04-13-20-06-50-183_com mxtech videoplayer ad](https://user-images.githubusercontent.com/20338483/38741389-61c29418-3f29-11e8-9c28-89752ba77e18.png)

Same with other apps like wps office, culprit here seems to be Google ads

**Comment by julian-klode** [comment]
Blocking in apps generally does not work well with DNS-based blocking solutions. You need the more resource-intensive full VPN solutions for that (that proxy all traffic through a VPN).

**Comment by Robiul2022** [comment]
Mx player pro link please

**Comment by Robiul2022** [comment]
Mx player pro link please
