### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by mayowadavid** [julian-klode/dns66#274]
Hello,
I found your application and i love the features integrated in the application, then i thought to make a logo that communicate the name of the application and also the app function. Since DNS66 allows blocking host names via DNS, which will give room to block ads.

The name **DNS66** & **Privacy** are the two major consideration while designing the logo, i hope you like, if you can use it on your application.
Cheers!

Here is the link to all the files 
https://drive.google.com/folderview?id=1b6u1VwJb7POevj58MPvdiUa3CBmNI-rQ

 ![DNS66 Logo.png](https://steemitimages.com/DQmQGF9qnGCwTcmSobge5FC4yug1jzCeYtb7YBHqSLrkbpS/DNS66%20Logo.png)

**Comment by mayowadavid** [comment]
Hi @julian-klode/dns66 , do you like the logo i proposed for your project?

**Comment by julian-klode** [comment]
Thanks for your work, but I'm afraid I don't see it fit.
