### ISSUE TITLE
Not auto starting at boot

### ISSUE THREAD

**Issue by ghost** [julian-klode/dns66#275]
I have a Moto E4 that does not automatically start back up even though it was running before.

--------- beginning of main
05-01 16:26:02.559  5940  5940 W System  : ClassLoader referenced unknown path: /mnt/expand/e1a12da6-9a39-4141-b5bf-382b2a691c1c/app/org.jak_linux.dns66-1/lib/arm
05-01 16:26:02.728  5940  5940 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
05-01 16:26:02.910  5940  5940 D DbUpdateJobService: scheduleOrCancel: Cancelling Job
05-01 16:26:02.997  5940  5940 D DbUpdateJobService: scheduleOrCancel: Cancelling Job
05-01 16:26:03.137  5940  5940 I ViewConfigCompat: Could not find method getScaledScrollFactor() on ViewConfiguration
05-01 16:26:03.176  5940  5986 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build:  (Iaf618d42e3)
05-01 16:26:03.176  5940  5986 I Adreno-EGL: OpenGL ES Shader Compiler Version: XE031.09.00.04
05-01 16:26:03.176  5940  5986 I Adreno-EGL: Build Date: 03/14/17 Tue
05-01 16:26:03.176  5940  5986 I Adreno-EGL: Local Branch: 
05-01 16:26:03.176  5940  5986 I Adreno-EGL: Remote Branch: 
05-01 16:26:03.176  5940  5986 I Adreno-EGL: Local Patches: 
05-01 16:26:03.176  5940  5986 I Adreno-EGL: Reconstruct Branch: 
05-01 16:26:03.180  5986  5986 W RenderThread: type=1400 audit(0.0:209): avc: denied { read } for uid=10162 name="gpuclk" dev="sysfs" ino=20909 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
05-01 16:26:03.180  5940  5986 I OpenGLRenderer: Initialized EGL, version 1.4
05-01 16:26:03.180  5940  5986 D OpenGLRenderer: Swap behavior 1
05-01 16:26:03.182  5940  5986 W Adreno-ES20: <get_gpu_clk:229>: open failed: errno 13
05-01 16:26:14.800  5940  5940 E RecyclerView: No adapter attached; skipping layout
05-01 16:26:14.811  5940  5946 I art     : Do partial code cache collection, code=19KB, data=30KB
05-01 16:26:14.812  5940  5946 I art     : After code cache collection, code=19KB, data=30KB
05-01 16:26:14.812  5940  5946 I art     : Increasing code cache capacity to 128KB
05-01 16:26:22.541  5940  5946 I art     : Do partial code cache collection, code=44KB, data=62KB
05-01 16:26:22.542  5940  5946 I art     : After code cache collection, code=44KB, data=62KB
05-01 16:26:22.542  5940  5946 I art     : Increasing code cache capacity to 256KB
05-01 16:26:22.606  5940  5940 W art     : Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView

----------------

Would making dns66 a device administrator be a foolproof way of forcing this feature to work on all devices all the time?

**Comment by julian-klode** [comment]
Are you doing app2sd or something? Boot stuff is generally awfully flaky.

**Comment by julian-klode** [comment]
Also not sure if that applies, but on Oreo, the notification needs to be enabled

**Comment by soaringowl2145** [comment]
No.  I did enable adaptable storage though.

**Comment by tomchiverton** [comment]
Have you tried manually setting "always on" in the main Android settings?

**Comment by soaringowl2145** [comment]
Where is that?

**Comment by tomchiverton** [comment]
Settings, connection, vpn, (long press)

Your Android may label them differently. 
-- 
Tom

**Comment by soaringowl2145** [comment]
The always on setting gets reset back to off from a cold boot.

However I moved the app from adopted storage to internal storage and this solved the issue.

**Comment by soaringowl2145** [comment]
As far as more information is concerned I know that when my Android boots, apps that are on the external storage such as Instagram take longer to display on my home screen/launcher and are unavailable I guess until the system recognizes that there is adoptable storage.

**Comment by soaringowl2145** [comment]
Thank you.

**Comment by chuck43105** [comment]
Tried everything referenced within the above comments. Nothing has changed. I still must restart DNS66 after every boot. Wish I could figure out why it's happening. Maybe it won't do it with a higher Android O.S. 

Can anyone tell me if there is a way to turn on verbose logging on the Android Phone in order to see if any errors are displayed when this app attempts to start on boot? Note that I don't have a rooted phone.

**Comment by julian-klode** [comment]
Shit happens, it's not super reliable to start stuff at boot.
