### ISSUE TITLE
Only update host lists on unmetered connections

### ISSUE THREAD

**Issue by riQQ** [julian-klode/dns66#277]
Could you please add an option to only update the host lists on unmetered connections.

**Comment by julian-klode** [comment]
That's what it currently does. We need an option to always do it, though, but that's tracked in another bug I think

**Comment by julian-klode** [comment]
As in, currently you need to be all of

* Unmetered
* Charging
* Idle

in order for automatic host file updates to happen.

**Comment by riQQ** [comment]
The Android system data metering apps shows dns66 having used the metered connection even though I haven't manually updated the host lists.

> We need an option to always do it

What do you mean by that?

**Comment by julian-klode** [comment]
Are you sure the data metering app does not show you just the traffic for DNS requests? We definitely set the requirements:

                .setRequiresCharging(true)
                .setRequiresDeviceIdle(true)
                .setRequiredNetworkType(JobInfo.NETWORK_TYPE_UNMETERED)


What I meant wiith "an option to always do it" is that you cannot configure it at all, and it requires these settings now. There should be three checkboxes so you can manually configure which requirements you want, as documented in #112.

**Comment by riQQ** [comment]
Is there any way I can analyze this if this happens again?

**Comment by MalikKillian** [comment]
Almost every day I see the update notification seemingly stuck while I'm on a metered connection. It may be that the host list begins updating when the above conditions are met but the notification _persists_ when the state changes. If this is true then the scheduler could use some better logic.

**Comment by riQQ** [comment]
It just started at 0:00 o'clock without charging, but idle and unmetered.

**Comment by julian-klode** [comment]
As said, I set the correct options, so if it does not work for, get a proper device.
