### ISSUE TITLE
Mobile data with 1.1.1.1 set as DNS doesn't load (or loads incredibly slowly)

### ISSUE THREAD

**Issue by eugf** [julian-klode/dns66#278]
I initially tested this when Cloudflare launched their new DNS on 1.1.1.1 and it worked fine. However, in recent weeks it has been loading extremely slowly for me or not at all sometimes. It gave various DNS_Proxy related errors on Chrome, sometimes saying the DNS changed or error resolving. It worked immediately once I turned off DNS66. And I just tried changing the DNS to Google's 8.8.8.8 and comparing that with 1.1.1.1 on https://www.dnsleaktest.com/ to confirm. It works with other DNS just not 1.1.1.1 There's no problem on Wifi with 1.1.1.1, and after around 5 minutes it may eventually load some things on data like email, but when it doesn't work on a webpage it just throws an error message. I want to reiterate that changing the DNS to anything else or turning on Wifi immediately resolves the issue and that this odd behavior has been going on for weeks. Any idea what's causing this or how to fix it? I'm using Google DNS for now

**Comment by julian-klode** [comment]
That's not a DNS66 bug.
