### ISSUE TITLE
Allow blocking apps from using data

### ISSUE THREAD

**Issue by scj643** [julian-klode/dns66#279]
I've been using Datally and was wondering if the app data blocking functionality could be implemented

**Comment by jawz101** [comment]
Android already has controls to do so.

**Comment by JollyPanda** [comment]
Most Android ROMs don't. The Nokia phones, which use stock Android, only allow users to block background data use but if the app is opened then it can use data.

**Comment by deevro** [comment]
+1 👍

Im using NoRoot Firewall for years, and now im switching to Dns66, what i miss about NoRoot Firewall is option to block/allow data connection on every app, which is great for people with very limited data plan (like me). It would be nice if Dns66 have that option too :)

**Comment by julian-klode** [comment]
Tracked in #30
