### ISSUE TITLE
Could be some issue by using L Speed? 

### ISSUE THREAD

**Issue by davidzam12** [julian-klode/dns66#282]
Hi. I'm a user of the app L SPEED, and I was wondering if there could be some issue if you use DNS666 at the same time, whit the dns. That app (L Speed) have an option that tweaks the dns and force the device to use the Google DNS, yes I'm using a rooted device, and no I'm not using xposed, my setup it's stock firmware 6.0.1, under Magisk 16 (I want safety net integrity) . I'm asking because I'm noticing that not all ads are removed, from apps and also from browsers. I'm using all the host setup you set on the app, and also have all the settings on the app's "inicio" or "star" section ipv6, etc, it seems that is connected and also it's updated. Thanks in advance for all the help you can offer me guys.

**Comment by julian-klode** [comment]
no
