### ISSUE TITLE
0.5.8 does not block any ads on Android P Developer Preview 3

### ISSUE THREAD

**Issue by MerdaFit** [julian-klode/dns66#289]
The app runs and downloads hosts and everything as normal, but once turned on it does not block any ads on DP3. The app worked perfectly fine on DP2 so Google must have changed something between the two releases.

Is it possible to get a fix for this or will you be waiting until Android P is finalized and the full version is released later this fall?

**Comment by julian-klode** [comment]
I'm not testing P. Once there is a stable (well, open beta) P for the OnePlus 6, I'll look.

**Comment by MerdaFit** [comment]
Don't have a OnePlus 6, but I thought it had a P Beta? [beta out](https://www.oneplus.com/developer-preview/)? I don't know how stable it is.

Anyway, Developer Preview 4 was released this week and the same issue exists. Other VPN style apps appear to still work, but I have other issues with them, none of them ever worked as seamlessly as DNS66.

Happy to patiently wait, thanks for your hard work!

**Comment by julian-klode** [comment]
There is a beta of P, but it's not really daily driver material I think. I could try an emulator at some point, too. 

Or once there's a build for the OnePlus One, I could try it on that too.

**Comment by schmaun** [comment]
Also not working on the P Prereleases for me. But maybe it's not a Problem of P but off a new Chrome Feature: asyncdns
https://www.androidsage.com/2018/01/25/how-to-fix-adhell-2-not-working-chrome/

After disabling that flag, the Ads are blocked in Chrome.

**Comment by MerdaFit** [comment]
Oh man, I'm dumb. I never even considered it was just a Chrome issue. I don't really use other browsers, but sure enough I open up Firefox and DNS blocks ads. Changing that flag got Chrome working again.

**Comment by jir5024** [comment]
Yes. This works for me:
Enter the URL “chrome://flags”, without quotes, into the address bar. 
Search "dns"
Set the “Async DNS” option to “Disabled” and close the tab.

**Comment by mchelen** [comment]
Thanks for the tip! Remember to clear the DNS cache as described in https://github.com/julian-klode/dns66/issues/289#issuecomment-406501453

**Comment by WizardShotTheFood** [comment]
That doesn't work. Still getting ads.

**Comment by julian-klode** [comment]
FWIW, I'll be upgrading to P in a few weeks, and then I'll see if it works or not.

**Comment by some-guy-23** [comment]
Same as above, this worked until Chrome just updated the other day. 69.0.3497.86 seems to have changed something with DNS?

**Comment by julian-klode** [comment]
Does not work for me either in Chrome on P. No DNS requests are sent to the VPN, so chrome _probably_ talks to its own DNS servers.

**Comment by julian-klode** [comment]
Ah no, I had data saver enabled. Turned it off, works again.

**Comment by PHLAK** [comment]
@julian-klode I just confirmed I *do not* have data saver enabled and it's still not blocking ads for me. As noted above I also ensured `asyncdns` was disabled.

**Comment by some-guy-23** [comment]
Can confirm I also have data save and asyncdns turned off, and ads are still not blocked. For other apps, blocking still works fine, just Chrome has the issue.

**Comment by mchelen** [comment]
Can you all confirm that you have cleared DNS cache:
1. Enter “chrome://net-internals”, without quotes, into the address bar.
2. Select the DNS tab, and tap on “Clear Cache”.
3. Restart Chrome.

Source: https://www.androidsage.com/2018/01/25/how-to-fix-adhell-2-not-working-chrome/

**Comment by some-guy-23** [comment]
@mchelen - even after clearing DNS cache, no joy. I'm on Pixel 2 XL, if it makes any difference.

**Comment by PHLAK** [comment]
@mchelen I can also confirm clearing the DNS cache had no affect.

**Comment by WizardShotTheFood** [comment]
Also not working for me after clearing the DNS cache. Apparently the current version of Chrome doesn’t respect the asynchronous DNS setting in chrome://flags, so this may not be a fixable bug right now.

**Comment by singlerider** [comment]
I tried Chrome for Android and Chrome Beta. Both versions have ads. Ads are blocked in Firefox, however.

Ads were blocked in Chrome after switching the flag (as described above) until a few days ago.

**Comment by xilduq** [comment]
issue appears to be with chrome v69 and can be verified via chrome://net-internals/#dns where you'll see "Internal DNS client enabled: true" regardless of the async dns flag setting.

reverting to chrome v68 and disabling async dns flag now shows "Internal DNS client enabled: false" and ad blocking is again working.

**Comment by PHLAK** [comment]
Is there somewhere we can report that @xilduq ?

**Comment by xilduq** [comment]
@phlak, i saw someone report it as a Google chrome bug the high level response seemed to be one indifference since the async dns flag is "experimental"...

**Comment by pzuccarelli** [comment]
I downgraded to v68 as xilduq recommended and it works again. Of course, I disabled upgrades from chrome. Please let us know in this thread if someone detects that chrome fixed its experimental imbecility. TIA

**Comment by akrawchyk** [comment]
I switched to Blokada v3.5 which successfully blocks ads on Android Pie for me.

**Comment by kuro68k** [comment]
Blokada seems to have the same issue. https://github.com/blokadaorg/blokada/issues/257

**Comment by streaml1ne555** [comment]
Switched to Blokada and it appears to be working despite reports from the above. We'll see how long it lasts.

**Comment by PHLAK** [comment]
Confirmed that Blokada is working for me as well with Chrome v69.0.3497.100

**Comment by jakommo** [comment]
It works again on Chrome Dev (v71), so probably just a matter of time until it works again in Chrome stable

**Comment by farmerbb** [comment]
I can confirm that manually entering in the [AdGuard DNS addresses](https://adguard.com/en/adguard-dns/overview.html) into DNS66, then turning off host blocking, works for blocking ads on Chrome 69 and Android Pie.  It also looks like Chrome Beta 70 properly respects the Async DNS setting in chrome://flags, so disabling that should get DNS66 working again out of the box on Chrome 70+.

**Comment by farmerbb** [comment]
@randomhobo130 You can add the two IP addresses 176.103.130.130 and 176.103.130.131 on the DNS tab of DNS66.  That having been said, this fix only seemed to work for a few days and no longer works for me anymore on Chrome 69.  Guess I'll just wait a couple weeks for Chrome 70 to fix disabling Async DNS.

**Comment by randomhobo130** [comment]
Thanks for the info. I decided to try downloading the beta for Chrome 70 and initially ad blocking seems to be working.

**Comment by phoerious** [comment]
I can't get it to work. Neither with Chrome beta, nor with Canary.

**Comment by mirkoole** [comment]
The solution is to disable private dns mode in Android Pie Settings -> network -> extend -> private dns -> off.

**Comment by jiteshsingh** [comment]
Works on android P and latest chrome version at the moment 75.0.3770.67
I needed to disable async dns from chrome flags and clear dnc cache from net-internals.

**Comment by silenteve** [comment]
Working well on my p20 pro android pie
you have to disable dns
