### ISSUE TITLE
Reconnecting error in 0.1.2

### ISSUE THREAD

**Issue by tburn76** [julian-klode/dns66#29]
Hi, 
i am having a  bug that was previously reported and closed where starting dns66 gives a recconecting error. I've uninstalled and reinstalled the app but the problem persists.

**Comment by julian-klode** [comment]
You can try getting a logcat (see http://forum.xda-developers.com/showthread.php?t=1726238) or generate a bug report [which contains a logcat] via Developer Options -> Generate Bug Report (or whatever it's called, should be around the top). Optimally around the time this happens to be reasonably sure that the cause for it is logged in there. Then, send it to me via e-mail (or link in email).

There might be some personal data in there, like which hosts your phone looked up, so while I will respect your privacy, I'd advise you not to share it publicly.

**Comment by phil0sophic** [comment]
Greetings,  I'm experiencing the same issue with 0.1.3 (GPLv3) , running 7.0 on Nexus 5X, default configuration. Very intermittent, tried power suggestion,  didn't help.

**Comment by jerryn70** [comment]
@julian-kode

I'm facing this issue on the latest version. When everytime i boot the phone I'm getting the error

**Comment by julian-klode** [comment]
Let's close that in favour of #83 and #36 - it's been a while, there's been a lot of changes (and a lot more are coming in 0.4).
