### ISSUE TITLE
Clicking the paperclip button on any page soft errors - Android 7.1.2

### ISSUE THREAD

**Issue by CurbsidePharmacist** [julian-klode/dns66#298]
Hello I'm new here and would like to report and issue I'm having and maybe find a way to set a custom list. Your app runs perfectly fine except for this one error I'm having with 2 of the same devices.

Any instance of the paperclip button I click on either cancels my entry or crashes DNS66 completely.
I am able to title my entry and such but as soon as I click the paperclip to add the hosts file it bugs.

I noticed another bug topic that might possibly be linked to the same problem.
https://github.com/julian-klode/dns66/issues/262
0.5.8 crashes when adding DNS servers (java.lang.NullPointerException) 

I'm curious if there is a way to implant settings data to the directory of my device to force that entry into my block-lists? Even trying to import settings from one of my other 2 working devices (Galaxy J7 - Android 6.0.1 / Dolamee D5 Android 5.1) fails to work as it crashes the menu as soon as I try to interact with the button.  Can I copy data from the working setups and manually overwrite that data to my bugged one?

I noticed people obtained crash logs I would be willing to submit one myself on this issue if someone could send me in the direction of how.

I also will add my device and specs as best I can to maybe help.
A5X Max 
RK3328 quad-core ARM Cortex-A53 CPU. With 4GB DDR3 RAM and 16GB eMMC ROM
Android 7.1.2
Kernel Version: 3.10.104
DNS66 Version 0.5.8/0.5.7 I tested both versions same result.

[edit]
Another thought that came to me was an error with my version of the file browser that's built into android.

**Comment by julian-klode** [comment]
#262 is a known issue on some devices that delete the main activity while you are editing an item, and thus the receiver registered in there does not work and stuff fails with a null pointer exception. I have no doubt that your problem is the same.
