### ISSUE TITLE
Not working on Xiaomi Redmi Note 4

### ISSUE THREAD

**Issue by AmrIKhudair** [julian-klode/dns66#299]
This app doesn't work with Xiaomi Redmi Note 4 (MIUI 9.6.1.0, Android 7.0 Lolipop)

What I have attempted:
1- Enable DNS changing
2- Adding OpenDNS Family Shield dns servers and enabling ONLY them
3- visit OpenDNS testing page

What I've got:
1- The testing page doesn't recognize the change in DNS
2- Adult sites are not blocked

Please FIX

**Comment by julian-klode** [comment]
Also, MIUI is generally is not a good choice, as it does not support basic Android functionality such as opening/closing files, thus preventing you from even exporting or importing settings.
