### ISSUE TITLE
No longer blocking on Pixel 2 XL after update to Android 9 Pie

### ISSUE THREAD

**Issue by inkobject** [julian-klode/dns66#303]
On Pixel 2 XL. Was working fine on Oreo 8.
After update to 9, ads started showing up.

Stopped and restarted DNS 66 several times but no joy.

Installed different app, Blokada, but it doesn't work either.

Wow, the ads the make the phone nearly unusable.

**Comment by julian-klode** [comment]
See #289

**Comment by WizardShotTheFood** [comment]
This does not fix it. I still get ads with async DNS disabled.
