### ISSUE TITLE
feature request: Automatic start/top based on time of day or specific wifi connection

### ISSUE THREAD

**Issue by Xytrios** [julian-klode/dns66#311]
Hi, 

I would like to start by saying a **big thanks** for making this great app possible.

I would very much appreciate if we could start/stop the app based on the time of day

ex: start app at 8:00 and stop at 18:00.

OR

start the app when specific wifi connection is detected.

ex: wifi connection "work" detected then start app, wifi connection "home" detected then stop app.

Maybe this is not possible or you have no plans of ever implementing such thing but it would be an awesome feature. Using apps like ifttt don't cut it as many of them don't respect your privacy.

Thanks

**Comment by nicobo** [comment]
I've the same request, but I would like to add that providing an Intent to start/stop the app would probably be enough for me as I already managed to start the app on specific events with [Easer](https://github.com/renyuneyun/Easer). I couldn't find a way to stop it however.

**Comment by Xytrios** [comment]
In my case i want to avoid the use of another app but if they can fulfill your request that would be good. My request might not make sense but it could help blokada differentiate itself from dns66

**Comment by julian-klode** [comment]
Not interested in complex rules.

**Comment by lgwapnitsky** [comment]
> I've the same request, but I would like to add that providing an Intent to start/stop the app/service would probably be enough for me as I already managed to start the app on specific events with [Easer](https://github.com/renyuneyun/Easer). I couldn't find a way to stop it however.
> 
> Edit : just found a request for Tasker support, which is similar to Easer : #146

What intent did you use?

Thanks
