### ISSUE TITLE
hpHosts's Ad and tracking servers

### ISSUE THREAD

**Issue by xonxoc** [julian-klode/dns66#312]
When I update the host I receive this error. hpHosts's Ad and tracking servers. unexpected error: java.io.EOFException: source exhausted prematurely

**Comment by iamtpage** [comment]
The URL for that host entry is down, disabling the host entry resolves this issue.

**Comment by ilBEastli** [comment]
It's up. Just switch from "http" to "https" in the URL.

**Comment by julian-klode** [comment]
Works fine. Sometimes it does not, but there's a reason it's not enabled by default.
