### ISSUE TITLE
Dns66 crash on importing/exporting/ or using hosts from disk. 

### ISSUE THREAD

**Issue by Hunter1212** [julian-klode/dns66#318]
The app crashes when accessing files from the storage even though the hosts update fine and the storage permissions are given to the app. What can I do to resolve this?

https://www68.zippyshare.com/v/wkesLctg/file.html

(Sorry I'm on my phone and pastebin hangs when I try to paste the data there)

**Comment by Hunter1212** [comment]
Wow 22 days and nothing.

BUMP please. Anyone I really need to export my list.

**Comment by julian-klode** [comment]
This is a bit unfortunate. Sounds like you are running Xiaomi's MIUI? Their system is broken, they do not provide the dialogs to open/save files.

**Comment by Hunter1212** [comment]
@julian-klode

Hey Julian. No I'm not running Xiaomi's MIUI, I don't have a xiaomi phone at that. Running Dirty Unicorn 12.5.2 16/10 build on my oneplus one.

And also it used to work before on the same rom. I've exported and imported multiple times and used custom host text file from storage. Just suddenly out of nowhere it started to do that. 

Even uninstalling and installing it again doesn't help. Neither older versions. Storage permissions are given to the app successfully it just crashes. Idk if you took a look at the logcat or not. I tried cleaning dalvik cache and cache either that didn't help. Idk what broke it or how it got to that state there's no app I haven't used before with dns66. Magisk xposed I have used them all together.

Help me out, right now I'm not using it others prefer or suggest using blokada but I prefer dns66 over it more. Also, I wonder when would be the next update, it's been an year since the last one.

**Comment by julian-klode** [comment]
Now that's more scarry, ugh. I've only tested things on AOSP and on OxygenOS, both Oreo based, and recently on the Pie-based OxygenOS; on the OnePlus 3 and OnePlus 6. I could dig out my One and see if I can reproduce it with your rom, but I'm not sure I'll find the time in the near future.

I hope to get a fix out for the missing notification in Android Pie after resume #320 soon, together with the stuff queued up in master, some DNS server changes and filter list URL updates. But I gotta install Android Studio on this machine first so I can build and test it. I don't do any Android development except DNS66, and suffice it to say, it's been a bit neglected the past year(s).

I'll try to get more regular bug fix releases out, and maybe even small features, but I don't expect there to be any considerable big new features coming from me. Of course, pull requests are welcome, but I don't spend as much free time in front of computers these days as I did when the project started.

**Comment by Hunter1212** [comment]
Ahh oh man, what do you propose I should do in the meantime? I love dns66 more than any other apps, can't see any other app being better than it blokada as some say is but doesn't come near to it than dns66 to me at least.

Hope to see some resolution to it so I can use it properly once again. If there's anyway I can help I'll try to.

If there's a way to see what changed or what's blocking it to access storage now and before I can try and make a comparison, I still have my old nandroid backup when the app worked fully.

**Comment by Hunter1212** [comment]
Well, no comments from the dev. Anyways, @julian-klode it's fine you don't have to look into it anymore. I found the problem although idk why it actually occurred or maybe I removed the file manager from my phone afterwards and never used the import export feature until now.

The issue was due to me having de-bloated the file manager from the phone using magisk, and that's how it was crashing. I got it back and it got resolved afterwards so no issues there anymore. Thanks for the support, I'll close this issue now.

**Comment by julian-klode** [comment]
I guess this makes sense - if you have nothing to open/save files, nothing can work, so we could show a warning in that case ("No file manager installed")

**Comment by Hunter1212** [comment]
Hey @julian-klode I got a question for you, it's a random one not regarding to this issue. You can delete it and I can open another ticket for it or if there's any other means to talk I could ask you there again. But here it goes.

So after I ran into the this issue with dns66 I started using blokada for that matter. Sorry off topic and talking about another app here, if it violates the rules please tell me I'll remove the question.

So just ran into something and got into a huge discussion with the dev who told me that the lists are loaded into the ram and thus doesn't advise to use big lists which can cause serious issues and give oom errors repetitively. I was wondering if dns66 does the same too and I was loading huge files into it. Was it ever using all files and entries within them or just doing the same as blokada. 

Another discussion point was the dns66 blocks ads at dns level whereas blokada doesn't. Although they both still use lists to block ads. I can't load cosmetic filters in both and both use VPN connection so my point was that they both work similarly and exactly the same and since I never ran into the issue that my lists weren't getting used fully with dns66. Although I have no proof of that and was wondering if you could shed some light over it a little.

**Comment by Hunter1212** [comment]
So let me ask this question then, let's say my device has 3 gigs of ram from which I get about 1.5 gigs or ram which keeps fluctuating which we all know, depends on the usage of the apps.

If I were to load a huge hosts file let's say about 30mb or more or multiple files like 8 to 10 hosts file with 2 to 4 huge files like that, between 10 to 30 mb each what issues can I face while using the phone. Just a general question, would I be facing any issues like my phone crashing or as such at any given time except for the time when my phone certainly goes out of memory due to me running several apps at the same time.
