### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by Musky80** [julian-klode/dns66#319]
I have dns66 0.5.8 with default settings. Dns66 active, all filter hosts is active and set as deny. No custom dns servers active. Ip6 no change on block, no block when is on or off. I refresh hosts source, dns66 off -> on and nothing. I visible ad still.

**Comment by itsnottakenme** [comment]
I wonder if this is related to your device. I installed this on a Samsung s9 and didn't appear to work either. OTOH it has worked fine on my xiaomi redmi note 3 although there seems to be a dns issue these days as sometimes dns66 causes sites to load really slow

**Comment by Zehirmahn** [comment]
Chrome uses it's own DSN resolver by default so it bypasses DNS66. It must be disabled:

Search "chrome://flags" in Chrome search bar
Search "DNS" in flags search bar
Disable "Async DNS resolver" flag

**Comment by Musky80** [comment]
thank you, problem is solved
