### ISSUE TITLE
0.5.8 Notification icon disappears after use - Pie 9

### ISSUE THREAD

**Issue by kadaamen** [julian-klode/dns66#320]
I just got the Android 9 (Pie) update on my Nokia 8.
DNS66 works just fine after reboot.
After pausing and resuming the service through the icon in the notification bar, the icon disappears. It reappears after stopping/starting the service through the app.

**Comment by Zehirmahn** [comment]
I have the same issue and also have Android 9

**Comment by julian-klode** [comment]
FWIW, me too. Gotta love Android.

**Comment by kadaamen** [comment]
Thanks for the response!
A (probably connected) issue:
I set my phone to 'Airplane Mode' at night. When I wake up in the morning the service is stopped as well. I have to press start manually in the app to restart it.

**Comment by julian-klode** [comment]
I don't know what the problem is. I tried starting the service from the notification the same way I start it from the activity, but I can't get it working. Notifications just hang until the service is started again, and then the notification disappears.

**Comment by julian-klode** [comment]
Nevermind, found the issue.
