### ISSUE TITLE
Not blocking websites in chrome

### ISSUE THREAD

**Issue by splyd36** [julian-klode/dns66#321]
So I'm light of recent news release some apps sending data to Facebook I set about installing DNS66.

I added Facebook.com
Graph.facebook.com
M.facebook.com

To a local hosts file which I pointed DNS66 to.

However when I tested simply by trying to visit facebook in chrome, I am.still able to visit the site.

Am I doing something wrong or is this a bug

Device: Note 9 with latest updates
DNS66 installed using F-Droid.

**Comment by itsnottakenme** [comment]
I still see ads on Facebook too. Some sites use the same ip's for ads as they do for content. If that is so then ip blockers like dns66 are of no use unfortunately

**Comment by Zehirmahn** [comment]
Chrome uses it's own DSN resolver by default so it bypasses DNS66. It must be disabled:
- Search "chrome://flags" in Chrome search bar
- Search "DNS" in flags search bar
- Disable "Async DNS resolver" flag

**Comment by julian-klode** [comment]
What Zehirmahn wrote
