### ISSUE TITLE
Works great until it's killed

### ISSUE THREAD

**Issue by nmyshkin** [julian-klode/dns66#322]
Running 0.53. Everything is good except it dies in about 5-10 minutes and I have to "Start" again. I have every thing checked, have turned off power-saving and power optimization, deep hibernation, etc. for the app. I have made the VPN "always on". I even tapped the little lock symbol in my recents. It just dies (or, more likely the system kills it).

Every one of the DNS-based ad blocks behaves in exactly the same way so I'm guessing it must be something in my system. What else can I try?

Alacatel3T, Android 8.1

**Comment by itsnottakenme** [comment]
Get a new device probably. Locking the app usually works on my device but the rare time the dns66 process still gets killed. I guess this is because the device is hitting its ram limit and thus can't keep dns66 open

**Comment by julian-klode** [comment]
Switching devices seems like your best bet.
