### ISSUE TITLE
Do not filter Google translate

### ISSUE THREAD

**Issue by frdesfgddff** [julian-klode/dns66#323]
Offline language packs for Google translate are blocked for some reason. While this may be an issue with the filter list (I don't know), it may be better to allow the app by default. Google translate doesn't show adverts anyway.

**Comment by frdesfgddff** [comment]
I note that this is a dupe of issue 300

**Comment by greenbigfrog** [comment]
@frdesfgddff if you realize it's a duplicate, you might as well directly close this issue yourself :smile:

**Comment by frdesfgddff** [comment]
True, I will, but I'll leave a comment in #300 to indicate exactly what the problem is, it isn't clear.
