### ISSUE TITLE
Feature Request - Option to use Root when available and not VPN method

### ISSUE THREAD

**Issue by Stele77** [julian-klode/dns66#327]
Hi!
I am looking into options for FOSS DNS changer apps on Android.
AFAIK there are many options like DNS66 which use the non root VPN method (ofc many are copycats of DNS66 ;) ).
While this is great for the majority of casual users who dont have root, an option for those with root to use it instead of a VPN would be great.
I cant use it because i want to use other VPNs, but sadly the only (AFAIK) DNS-changer app that does uses root instead of VPN, DNS-Man is now abandoned, and the Github repo down.
DNS66 has a good UI IMHO (opposite of what you may think), good UX with the AFAIK best privacy minded DNS server build in.. So it would be the perfect base for an allround DNS solution on android.
Please consider the option for root users to change the hosts file with your app.. I am not a dev, but AFAIK it would "only" need to provide the option to edit the hosts file to the selected DNS servers.. So i hope this would be doable from a dev standpoint.
Thanks in advance for your consideration and all the best for you and this project!

**Comment by julian-klode** [comment]
Not interested.
