### ISSUE TITLE
Is Dns66 slowdowns simple AsyncTask ?

### ISSUE THREAD

**Issue by nithinkolekar** [julian-klode/dns66#330]
Having Moto x with Android 5.1.1 and dns66 installed it seems simple AsyncTask is taking too much of time ,i.e 10x more than when it is disabled.  I checked almost all available solutions in SO regarding "AsyncTask slow performance issues" but finally found it was happening only when dns66 is enabled. (even OkHttp was slow, which hints me to check in other way)
Is it a normal behavior?

Tested speed with https://github.com/dferreira-cvl/okhttp-vs-httpurlconnection-android 
but actual URL is changed from big jpeg to simple JSON which is just 396 Bytes
https://raw.githubusercontent.com/rt4914/Medium-Blog-Files/master/moviesData.json 

with dns66 enabled (too slow)
02-08 18:08:40.970 9166-9188/com.codavel.okhttp_vs_httpurlconnection I/data: httpurlconnection time 14046ms
02-08 18:08:46.312 9166-9191/com.codavel.okhttp_vs_httpurlconnection I/data: okhttp time: 19377ms

without dns66 (just paused via notification)
02-08 18:19:02.034 10261-10283/com.codavel.okhttp_vs_httpurlconnection I/data: httpurlconnection-log time 1069ms
02-08 18:19:02.035 10261-10286/com.codavel.okhttp_vs_httpurlconnection I/data: okhttp-log time: 1057ms

**Comment by julian-klode** [comment]
Consider updating your phone.
