### ISSUE TITLE
Adds not blocked

### ISSUE THREAD

**Issue by Grehgous** [julian-klode/dns66#331]
I just setup DNS66 mostly for use with YouTube and Spotify. I understood that adds will remain within their apps, so I tried using the browser versions via Chrome. I found that I still have ads with both of them in the browser.

Is this expected behavior, or did something go wrong?

Version: 0.6.0
Hosts: Steven Black, Adaway, Peter Lowe
DNS: Default

**Comment by PaulHermens** [comment]
As you could have found in other issues, this is a chrome caused issue. Some say disabling the data saver fixes it. However for me just chrome will always show ads. Other browsers like duckduckgo or kiwi browser will however not show ads and use the DNS66 dns. The common guess is chrome always forces it's own dns 8.8.8.8

**Comment by Grehgous** [comment]
Is it correct that the DNS filtering does not work for in-app advertisements?

**Comment by PaulHermens** [comment]
I can't say anything about official records of your question. However from my experience it does not. On that note my guess is as good as yours. I think most major companies are running the DNS either forced through Google servers or they are using the exact same DNS for the content itself. This way you can't really get around ads from a DNS perspective.

**Comment by PaulHermens** [comment]
I am sorry I was not totally correct.
https://www.androidsage.com/2018/01/25/how-to-fix-adhell-2-not-working-chrome/

Here you can find more information. Just disable async DNS and clear cache of chrome otherwise it doesn't really have any effects. Good luck.

**Comment by vmarchesin** [comment]
@PaulHermens This resolved the issue on Chrome using Android Pie. Thanks.

**Comment by Grehgous** [comment]
> I am sorry I was not totally correct.
> https://www.androidsage.com/2018/01/25/how-to-fix-adhell-2-not-working-chrome/
> 
> Here you can find more information. Just disable async DNS and clear cache of chrome otherwise it doesn't really have any effects. Good luck.


I set Async DNS option to disabled and cleared the DNS Cache. I have not found where to add the firewall rule yet.

However, after completing the first 2 steps internet does not work at all with DNS66. That seems odd that non-chrome apps would have internet connectivity problems. I will test again later on a different network.

**Comment by julian-klode** [comment]
It depends on the app and the way ads are served. We don't really know how things work precisely, so blocking might be spotty.

YouTube specifically. I cannot comment on Spotify, and with their recent TOS changes you very likely don't want to try anyway.

The Adaway and Pete Lowe's list are included in the other one AFAIUI, no need to include them again.
