### ISSUE TITLE
Add to a blacklist

### ISSUE THREAD

**Issue by Grehgous** [julian-klode/dns66#332]
In another issue I was directed to [this article](https://www.androidsage.com/2018/01/25/how-to-fix-adhell-2-not-working-chrome) but I have not figured out where to add to the blacklist. Is that in Chrome, DNS66, or my phone settings? 

Also, after disabling async-dns and clearing the DNS cache in chrome I'm unable to load web pages at all. Any thoughts on that?

**Comment by julian-klode** [comment]
Well, if it does not load web pages at all, it's probably working fsvo working. Can't say much else about it.
