### ISSUE TITLE
Dns66 is being silently blocked by firewall

### ISSUE THREAD

**Issue by notorand-it** [julian-klode/dns66#336]
The scenario I am facing is like this.
Dns66 correctly running and working.
If I disable Google Chrome asynchronous dns, I cannot browse any website: it times out. I suspect it's due to external firewalling.
If I enable it, it works but dns66 doesn't block the ads (of course).
I think Dns66 should detect such cases and disable itself.

**Comment by julian-klode** [comment]
NAK.
