### ISSUE TITLE
goole play store makes it bypass every time i open the app

### ISSUE THREAD

**Issue by PrabeshRajJk** [julian-klode/dns66#337]
i dont know whether it is usual or unusal 
in my setting i have made ''no app bypass by default ''
but
i noted that every time i open the dns66 
 google play store (com.android.vending)
is set to bypass  dns66?

**Comment by hiyan** [comment]
com.android.vending is whitelisted by default.

I've disabled it manually and so far no ill affects.

**Comment by demetry14** [comment]
Ill effect is that it doesn't stay disabled.

**Comment by julian-klode** [comment]
Play Store has to bypass, it does not work otherwise.
