### ISSUE TITLE
DNS66 Not Auto Starting

### ISSUE THREAD

**Issue by chuck43105** [julian-klode/dns66#339]
DNS66 does not auto start on boot even though that auto start option is selected. I have a BLU VIVO 5 and BLU VIVO 8 smartphones. It's doing the same on both phones. I have Android 6 Marshmallow on the VIVO 5 and Android 7 Nouget on VIVO 8. I tried shutting off IPV6 support without any luck - still doesn't auto start on boot. Also tried to turn off System Apps within the settings without any changes as well. 

Not sure what else to try. Hope you can figure out what's causing it to not auto start as I would prefer not to have to start it manually after every boot. 

Thank you.

**Comment by xmaysonnave** [comment]
Same issue here on redmi note 4 with miui 10.2.x

**Comment by chuck43105** [comment]
This issue is the same as #275. I tried everything that was suggested but DNS66 doesn't auto start on boot up. 

Any suggestions on anything I can try? 

Please help. Thank you.

**Comment by chuck43105** [comment]
This issue is the same as #275. I tried everything that was suggested but DNS66 doesn't auto start on boot up. 

Any suggestions on anything I can try? 

Please help. Thank you.

**Comment by chuck43105** [comment]
Please prompt for Issue Closure when pressing the Close and Comment button. I thought it meant to close the window ; not the issue 😀

**Comment by SeriousM** [comment]
I have a oneplus 3t and dns66 used to work really stable. Since the last os update of oxygenos to 9.0.5 the autostart after boot and connection change seems to be broken. I'm pretty sure this has to be correlated to the latest Android security patches.

**Comment by SeriousM** [comment]
I correct myself, the new update just reset all app optimizations. I will test if this issue is now solved.

**Comment by julian-klode** [comment]
Autostart is somewhat flaky IIRC. Not much that can be done about that.
