### ISSUE TITLE
Allow exempting apps from addblocking

### ISSUE THREAD

**Issue by julian-klode** [julian-klode/dns66#34]
We can exempt apps from adblocking using addDisallowedApplication() on the VpnService Builder.

**Comment by mirsadm** [comment]
How about doing the opposite? Use addAllowedApplication and let the user decide what apps get blocked? This way all the issue with Nougat would presumably be fixed by only blocking certain apps like Chrome.

**Comment by julian-klode** [comment]
I just thought I'd show a list of all installed applications and you can check which ones you don't want blocking for (for example, by setting a check box). Then the only difference is the default (as I show all values), basically, whether I call disallow or allow is a backend choice.

I still thinking blocking all by default (except known issues) is a good choice: There are a lot of apps that cause background requests to tracking servers, which you might not even know about.

**Comment by julian-klode** [comment]
Fixed in #44
