### ISSUE TITLE
Custom dns does not work

### ISSUE THREAD

**Issue by zippyside** [julian-klode/dns66#340]
Just like the title says; custom dns option is pretty much useless, especially with using cloudflare or adguard dns.

**Comment by redtux** [comment]
CloudflareDNS 1 (1.1.1.1) & 2 (1.0.0.1) are already there, but I can confirm that the slider to provide custom DNS servers is not working.

**Comment by julian-klode** [comment]
Sorry, but it works fine.

```
09-07 12:09:59.430  1842 11424 D AdVpnThread: doOne: Polling 2 file descriptors
09-07 12:09:59.430  1842 11424 D AdVpnThread: Read from device
09-07 12:09:59.433  1842 11424 D DnsPacketProxy: handleDnsRequest: Incoming packet to 192.0.2.2 AKA 0 AKA /1.1.1.1
09-07 12:09:59.434  1842 11424 I DnsPacketProxy: handleDnsRequest: DNS Name data.mistat.intl.xiaomi.com Blocked!
09-07 12:09:59.436  1842 11424 D AdVpnThread: doOne: Polling 2 file descriptors
09-07 12:09:59.437  1842 11424 D AdVpnThread: Write to device
```

**Comment by redtux** [comment]
@julian-klode: You are right. In my case it was related to #353. After having reinstalled the app everything including customized DNS servers works fine again.

**Comment by jiteshsingh** [comment]
custom does not work on android 10.
device is motorola one power. it's an android one certified device. do let me know I can provide logcat if needed.
