### ISSUE TITLE
Cloudflare DNS over HTTPS

### ISSUE THREAD

**Issue by ghost** [julian-klode/dns66#341]
With Cloudflare set in custom DNS http://1.1.1.1/help is showing:
`Connected to 1.1.1.1` - `Yes` 
BUT 
`DNS over HTTPS` - `No` - this should be yes?

**Comment by dynamicfire** [comment]
shouldn't

**Comment by bjpafa** [comment]
Very funny 🤔👍

**Comment by julian-klode** [comment]
No. #11 tracks encrypted DNS support. I'm not really interested in adding any support for it, as it is basically not really usable because it's way too slow.
