### ISSUE TITLE
Suggestion : Allow active app notification button

### ISSUE THREAD

**Issue by Zehirmahn** [julian-klode/dns66#343]
I don't know if there is another place to post suggestions so here it is:
A notification toggle button alongside the pause button that would allow/block ads for the currently active app. 

It would allow users to eventually allow ads for a specific app that require ads for some tasks without having to think to re-activate adblocking when they leave this app. And later, coming back to this app, easily re-block ads for this app if the user is not to do tasks that require ads.

It would be as easy as in our PC browser, instead of opening DNS66 and going through a potentially very long app list each time an app needs a toggle.

**Comment by julian-klode** [comment]
We don't have any ability to do on-demand per-app blocking atm.
