### ISSUE TITLE
Another failed to update host

### ISSUE THREAD

**Issue by EveryNameIsTakenAaaah** [julian-klode/dns66#344]
Today I'm getting the "failed to update host" for Malware domains.com and long-lived malware domains. Tried reinstalling. All hosts start with https. What do I do?

**Comment by livewire300** [comment]
I'm having the same problem of Not being able to update host files.  Hope for a fix soon. Thanks
Version 0.6.0

**Comment by julian-klode** [comment]
That's not a DNS66 problem. The default changed to use one hostfile hosted on GitHub for a reason.
