### ISSUE TITLE
Add a proxy possibility for convenient debugging

### ISSUE THREAD

**Issue by nodje** [julian-klode/dns66#351]
This is just a proposition, you may have a way to go about this already:
how do you debug what get caught by the blocking list and what doesn't?

I was just trying to check with mitmproxy some annoying ads that don't get blocked with DNS66 where they get caught with AdAway (in theory 2 methods that boils down to the same, only depends on the list of domain you want to block).
But couldn't see anything (of course as an afterthought!)

So I guess a proxy would be a cool feature. 
But maybe everything is clear when using Logcat? Haven't tried yet...

**Comment by julian-klode** [comment]
You can read the logcat, it tells you what was blocked and what not. #35 tracks a log UI where you can see requests in-app.
