### ISSUE TITLE
Android 10 issues

### ISSUE THREAD

**Issue by jj777** [julian-klode/dns66#352]
Has anyone just received the Android 10 update to their Pixel devices today? Looks like DNS66 is stopping some/all(?) DNS resolution on 10 when enabled. 

I'm trying to figure out what is stopping it now (it's not the chrome async issue from Android 9).

**Comment by jeffress** [comment]
Yes. Same. No connectivity. Have to disable DNS66 in order to get anywhere.

Glad to help with testing.

**Comment by ebuh** [comment]
Fix: Settings -> Network & Internet -> Advanced -> Private DNS -> Set to 'Automatic'

**Comment by dbaghdanov** [comment]
Did nothing for me:
> Settings -> Network & Internet -> Advanced -> Private DNS -> Set to 'Automatic'

I'm on a pixel 3a, android 10: 
I VpnService: Ignoring connectivity changed for our own network
E AdVpnThread: Network exception in vpn thread, reconnecting
E AdVpnThread: java.lang.IllegalArgumentException: arr is empty.

DNS66 0.6

**Comment by julian-klode** [comment]
master works on emulator, actual device tests will have to wait until Q's available on the OnePlus 6.

**Comment by julian-klode** [comment]
Just released 0.6.1 which is built against Android 10. Not sure if it improves anything for you.

**Comment by dbaghdanov** [comment]
Thanks, it's running now without errors.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by julian-klode** [comment]
I've also heard other reports of 0.6.0 running on Q, so going to close this.
