### ISSUE TITLE
Permanently crashing after having worked fine for years

### ISSUE THREAD

**Issue by redtux** [julian-klode/dns66#353]
Hi, I am a very intense user and a big fan of DNS66. Great work! 👍 Most probably this is just a coincidence, but since the Wikipedia DDOS yesterday the app keeps crashing all the time losing all its settings. When I want to change a setting, it freezes or immediately crashes again. I am on a Mi MIX 2 with MIUI Global 10.3 / Android 8.0.0 using DNS66 0.6.0 from F-Droid. (Logcat is not working.) There have been no OS updates so I do not know what could have changed since the last working run…

**Comment by julian-klode** [comment]
Maybe uninstall and reinstall I guess?

**Comment by redtux** [comment]
:smile_cat: This worked fine, thx! :+1:
