### ISSUE TITLE
Fail to establish VPN after update to Xiaomi MIUI 10.3.4

### ISSUE THREAD

**Issue by mavrothal** [julian-klode/dns66#354]
I had dns66 0.60 from F-droid running nicely for a month on my fist android phone, a Xiaomi Redmi  running Android 9, fitted with TWRP recovery and rooted with Magisk. After updating from MIUI 10.3.1 to 10.3.4 with android security patch 2019-08-01 the VPN failed to start. Reinstalling the app, clearing caches and settings, reinstating from a Titanium Backup and everything else sort of setting up the system from scratch, failed. 
As far as I can tell from Magisk, the app also fails to detect root and acquire root permission.
Of note other VPN-based adblockers still work fine.

Is conceivable that I somehow messed something up as a still fiddle with the system, though I search the repo and the forums and also looked at both the app and system log but nothing jumps out. 
So I attach the logs in case you pick something relevant.
If you need more extensive logs pls let me know.
Thanks

[DNS66.zip](https://github.com/julian-klode/dns66/files/3586878/DNS66.zip)

**Comment by julian-klode** [comment]
The log tells me it is working fine. It's certainly starting, and processing DNS lookups:

```
09-07 18:56:05.818 20250 21137 D AdVpnThread: Read from device
09-07 18:56:05.819 20250 21137 D DnsPacketProxy: handleDnsRequest: Incoming packet to 192.0.2.2 AKA 0 AKA /192.168.1.254
09-07 18:56:05.820 20250 21137 I DnsPacketProxy: handleDnsRequest: DNS Name f-droid.org Allowed, sending to /192.168.1.254
09-07 18:56:05.823 20250 21137 D AdVpnThread: doOne: Polling 3 file descriptors
09-07 18:56:05.878 20250 21137 D AdVpnThread: Read from DNS socketjava.net.DatagramSocket@400ea58
09-07 18:56:05.888 20250 21137 D AdVpnThread: doOne: Polling 2 file descriptors
09-07 18:56:05.889 20250 21137 D AdVpnThread: Write to device
```
However that's the only DNS lookup and the log continues for 30 seconds. Which I guess means MIUI stopped sending it domain lookups.

There's a lot of IPv6 related unknown packages, it might be worth trying to turn IPv6 support of.

**Comment by mavrothal** [comment]
Thank you for the fast response!
Indeed I have noticed the IPv6 connections and was the first thing I changed to no difference.
The app looks "happy" but no menubar sign of active VPN and more important, no filtering.
Actually blocking connection without VPN in android settings, blocks all internet activity.
Maybe I'll try a more verbal system logging for clues.
Thanks again.

**Comment by julian-klode** [comment]
This seemed to be working on the DNS66 side, so closing as to reduce bug clutter.
