### ISSUE TITLE
Killed in low memory situations

### ISSUE THREAD

**Issue by soenkegissel** [julian-klode/dns66#355]
In low memory situations the service is killed on every phone I tested. Emulator, Samsung S7, Wiko Lenny 4, Wiko Rainbow Jam.
I found a tutorial from a professional source that could maybe help:
https://fabcirablog.weebly.com/blog/creating-a-never-ending-background-service-in-android#

![WikoRainbowJam](https://user-images.githubusercontent.com/13346316/64946715-c6396680-d873-11e9-8a6c-079212bbe84e.gif)

**Comment by soenkegissel** [comment]
Sorry. Did not realise the service starts again, as soon as enough memory is available.
Am I right?

**Comment by julian-klode** [comment]
I don't know, I'm not aware of anything that could be done to improve this. Something needs to be killed in those situations and it's somewhat random. I suggest you get a phone with more ram.
