### ISSUE TITLE
Private DNS support?

### ISSUE THREAD

**Issue by bpkroth** [julian-klode/dns66#356]
Related to #352. Currently to get DNS66 to work I need to set the Private DNS feature to Automatic. According to the red box in the following that means that it won't be used:
https://developers.google.com/speed/public-dns/docs/using#android

Custom DNS servers for DNS66 don't specify whether or not they use TLS. Is there a way these features can be combined?

Thanks!

**Comment by rugk** [comment]
It seems this ap does not support neither DoT (dns over tls) nor DoH (DNs over HTTPS), which is quite sad.

**Comment by julian-klode** [comment]
I'm not really interested in doing that, it would require significant refactoring, and DNSoverTLS is incredibly slow to the point of being barely usable.

**Comment by julian-klode** [comment]
This is a duplicate of #11 anyway, as we can't magically support Android's private DNS servers.
