### ISSUE TITLE
R.mipmap.app_icon_large not shown after disconnect.

### ISSUE THREAD

**Issue by soenkegissel** [julian-klode/dns66#361]
In StartFragment line 144 the case statement for VPN_STATUS_STOPPED should be as following:
case AdVpnService.VPN_STATUS_STOPPED:
                stateImage.setImageAlpha(32);
                stateImage.setImageTintList(null);
                stateImage.setImageDrawable(context.getDrawable(R.mipmap.app_icon_large));
                startButton.setText(R.string.action_start);
                break;

With stateImage.setImageDrawable() in first line the image isn't shown. Tested with API 21 emulator.

**Comment by julian-klode** [comment]
Thank you, do you want to submit a pull request for that?
