### ISSUE TITLE
getContext().getPackageManager() on a null object reference

### ISSUE THREAD

**Issue by soenkegissel** [julian-klode/dns66#362]
In AppListAdapter extends RecyclerView.Adapter in function onBindViewHolder. packageManager is already in signature, initialize it!
I have exceptions caused by
getContext().getPackageManager() NPE in line 186

![image](https://user-images.githubusercontent.com/13346316/66715196-92912400-edc0-11e9-8697-e7458e5a2b1a.png)

The solution:
![image](https://user-images.githubusercontent.com/13346316/66715172-53fb6980-edc0-11e9-863c-b8514952115a.png)

**Comment by julian-klode** [comment]
Can you submit a pull request for this?

**Comment by julian-klode** [comment]
Nevermind
