### ISSUE TITLE
Error on Android 9

### ISSUE THREAD

**Issue by gocict** [julian-klode/dns66#363]
Hi!
I am using Samsung and it run on Android 9. When I run DNS66 and connect my phone to my WIFI, it has this error:
`09-28 11:46:49.334 19393 19448 I DnsPacketProxy: handleDnsRequest: Discarding unknown packet type [IPv6 Hop-by-Hop Options Header (6 bytes)]

09-28 11:46:49.334 19393 19448 I DnsPacketProxy:   Next Header: 58 (ICMPv6)
09-28 11:46:49.334 19393 19448 I DnsPacketProxy:   Hdr Ext Len: 0 (8 [bytes])
09-28 11:46:49.334 19393 19448 I DnsPacketProxy:   Options: 
09-28 11:46:49.334 19393 19448 I DnsPacketProxy:     [Option Type: 0x05 (Router Alert)] [Option Data Len: 2 bytes] [Option Data: 0x0000]
09-28 11:46:49.334 19393 19448 I DnsPacketProxy: [ICMPv6 Common Header (4 bytes)]
09-28 11:46:49.334 19393 19448 I DnsPacketProxy:   Type: 1 (Destination Unreachable)
09-28 11:46:49.334 19393 19448 I DnsPacketProxy:   Code: 0 (no route to destination)
09-28 11:46:49.334 19393 19448 I DnsPacketProxy:   Checksum: 0x8f00
09-28 11:46:49.334 19393 19448 I DnsPacketProxy: [ICMPv6 Destination Unreachable Header (4 bytes)]
09-28 11:46:49.334 19393 19448 I DnsPacketProxy:   Unused: -1425801216
09-28 11:46:49.334 19393 19448 I DnsPacketProxy: [Illegal Packet (22 bytes)]
09-28 11:46:49.334 19393 19448 I DnsPacketProxy:   Hex stream: 00 01 04 00 00 00 ff 02 00 00 00 00 00 00 00 00 00 01 ff a0 af 2e`
And DNS66 cant block any ads!

**Comment by dbaghdanov** [comment]
I'm getting this same error on Android 10 on a Pixel 3a

**Comment by julian-klode** [comment]
There does not seem to be an error here, just an unhandled routing alert message, which is normal.
