### ISSUE TITLE
DNS66 doesn't block anything with Google News app (Google Actualités)

### ISSUE THREAD

**Issue by LeZVince** [julian-klode/dns66#365]
Hello,
First thanks for this application DNS66 seems to be very usefull.
I try to use DNS66 to block the advertising with the Google News application (Google Actualités in French), but it doesn't work, the advertising are still visible.
- In HOSTS I have been checked the hosts lists (shield displayed) for all lists except "Malware Domain List".
- In APPS I have been checked Google News application
- In DNS I tried with or without activating the customised DNS Servers.
- The Application is started I have a shield with a check in it.
- I use the version 0.6.1 of DNS66
- Android 9 on Xiaomi Mi-9T.

What am I missing ? Why does it not work ?
Thanks per advance for your help :)

**Comment by julian-klode** [comment]
Go figure it out yourself, but this isn't something I'm interested in.
