### ISSUE TITLE
Issue blocking domains on Firefox

### ISSUE THREAD

**Issue by bbchann-el** [julian-klode/dns66#368]
I'm trying to block a specific domain (twitter).  
I refreshed the hosts files, manually restarted the DNS service, cleared Firefox's cache, force stopped Firefox, and restarted my phone, however I am still able to access twitter.com. 
Is this an issue with compatibility or am I missing something?

**Comment by freed00m** [comment]
@ghost - did it work? I facing the same issue, trying to block twitter with dns66 and firefox is not able to connect anywhere
