### ISSUE TITLE
DNS66 Does'nt block ads on Samsung Galaxy J6 Plus Android 9 

### ISSUE THREAD

**Issue by ayylmao61** [julian-klode/dns66#369]
![Screenshot_20191101-134127_One UI Home](https://user-images.githubusercontent.com/57266138/68040624-78ef4800-fcad-11e9-8ed4-6eb66c7ead0d.jpg)
![Screenshot_20191101-134134_Chrome](https://user-images.githubusercontent.com/57266138/68040625-7987de80-fcad-11e9-95c9-0b0f1533d337.jpg)
![Screenshot_20191101-134140_DNS66](https://user-images.githubusercontent.com/57266138/68040626-7987de80-fcad-11e9-8a17-a2b934fc0fd8.jpg)
![Screenshot_20191101-134144_DNS66](https://user-images.githubusercontent.com/57266138/68040627-7987de80-fcad-11e9-9386-4c49477a02f2.jpg)
![Screenshot_20191101-134148_DNS66](https://user-images.githubusercontent.com/57266138/68040628-7a207500-fcad-11e9-824d-03914d77dc12.jpg)
![Screenshot_20191101-134151_DNS66](https://user-images.githubusercontent.com/57266138/68040631-7a207500-fcad-11e9-9119-77ba9e7473cc.jpg)

**Comment by Gaspadlo** [comment]
This is not a DNS66's fault - Chrome has recently implemented inner DNS over https resolver - to get it working with chrome again - disable these in chrome://flags 
![Screenshot_2019-11-29-10-07-29-443_com android chrome](https://user-images.githubusercontent.com/4014669/69857338-19765f00-1290-11ea-856b-fdc12580a2b6.jpg)

**Comment by matthew-towers** [comment]
This doesn't work for me in Chrome (Android 9, Chrome 79, async dns resolver disabled, secure dns lookups disabled, lite mode off, private dns off, chrome dns cache cleared in net-internals) - no blocking at all. It does work in Firefox. Anything else I can try?

**Comment by julian-klode** [comment]
Not blocking is not a worthwhile bug report - it's likely misconfiguration or features in other software that don't make it work. If you get a logcat for DNS66 and see a backtrace in there, let me know, though.
