### ISSUE TITLE
Crash when adding hosts to block.

### ISSUE THREAD

**Issue by xEclypse** [julian-klode/dns66#372]
While creating a new host to block, I add the file, and when I click the check in the top right, it gives me an error stating that "Unfortunately, DNS66 has stopped working". It then proceeds to kick out of the app. I'm very new to this DNS stuff and I have very minimal programming experience, so please explain it to me like I'm 5.

**Comment by julian-klode** [comment]
I'm aware that it does not work on certain vendors, but there's not much I can do about that, sorry. Patches welcome, though.
