### ISSUE TITLE
Android 10 Private DNS not working with DNS66

### ISSUE THREAD

**Issue by ggebara** [julian-klode/dns66#374]
How to recreate:

1. Google Pixel 3a XL Android 10 (patch level Dec 5, 2019)
2. DNS66 v0.6.1 installed - NOT STARTED
3. Enable Android "Private DNS" using "Private DNS provider hostname" of 1dot1dot1dot1.cloudflare.com
4. Turn off "Custom DNS servers" in DNS66
5. Start DNS66
Result: all DNS lookups fail.  Net access only works with IP addresses.

Same result if set to ON at step 5.  Same result on LTE or WiFi.

**Comment by ggebara** [comment]
Private DNS does work on the device when using OpenVPN (Private Tunnel app).  Verified via  https://1.1.1.1/help

**Comment by ggebara** [comment]
If at step #3 set to "Automatic" then DNS lookups work with DNS66 enabled.  However https://1.1.1.1/help confirms that private DNS is not being used.

**Comment by julian-klode** [comment]
That's correct and there are no plans to do so really. #11 is tracking if anything happens in that area.
