### ISSUE TITLE
Galaxy note 10 plus updated Android 10, 6.1 not working

### ISSUE THREAD

**Issue by cocokola** [julian-klode/dns66#375]
I updated already to 6.1 after my note was upgraded to Android 10 and no connectivity is allowed when dns66 is enabled.   I found the closed issue that 6.1 should fix this, but even trying reset defaults network is still broke when enabled. Please advise.

**Comment by cocokola** [comment]
Gents, I updated the code, verified it is running latest version.   Why no replies for over a month?

**Comment by julian-klode** [comment]
It's not a useful bug and I don't really have time. Like I'm not going to buy an S10 to try to reproduce your issue.

If you have some useful log to contribute please do so, until then, I'll have to close this.

**Comment by cocokola** [comment]
I am available to help fix this,  it is not a S10,  it is a Note 10, but I highly doubt it has anything to do with the make/model.  When the Andriod was updated to 10, it stopped working completely.  

I followed your instructions for obtaining a Log, why would it be useless, or rather,  how about helping brainstorm how to make the logs useful?
You fixed this once for someone else.   Could you check if this is an issue for others - do you hafve stats from others that phone home to indicate it is working for them?

..   I am a QA tester, so just let me know what you need to isolate this.
