### ISSUE TITLE
0.6.1 Doesn't start automatically after restarting device (S10, Android 10)

### ISSUE THREAD

**Issue by Lavater** [julian-klode/dns66#376]
Hello,

with Android 8 DNS66 started automatically after restarting my device. With my new device - Android 10 / Samsung S10 and the 0.6.1 this doesn't work anymore. I have to open App after restarting und turn DNS66 on. Please could you fix this.

**Comment by julian-klode** [comment]
Works for me on my phone, and there's nothing else I can do, so not my problem.

**Comment by Lavater** [comment]
Do you have an S10?

**Comment by julian-klode** [comment]
No I have a OnePlus 6, but that's immaterial. I can't investigate or fix this, I'm doing everything I'm supposed to do.

Patches or otherwise concrete solutions welcome, though.
