### ISSUE TITLE
Nokia 6.1 with Android 10

### ISSUE THREAD

**Issue by txemaq** [julian-klode/dns66#377]
Here is a Nokia 6.1 with Android 10. There is no connectivity (data or wifi) when DNS66 (6.1 version) is activated. Error message example: UnknownHostException - Unable to resolve host "xxx.example.zzz": No address associated with hostname.

**Comment by julian-klode** [comment]
That's unfortunate, but not actionable without a logcat showing a concrete error message. Works for me.

**Comment by txemaq** [comment]
I found my problem: many time ago I had set up a Private DNS (Settings -> Network & Internet -> Advanced -> Private DNS). Today I set up this option to "Off", and DNS66 is working fine ;)
Sorry for the noise.
