### ISSUE TITLE
Doesn't work with IPv4 only

### ISSUE THREAD

**Issue by Lavater** [julian-klode/dns66#378]
Hello,

my S10 doesn't work in home WIFI with. With datanetwork it works fine. What can I do to access DNS66 with my Wifi?

**Comment by Lavater** [comment]
Sorry, have to verify my last posting. I activate IPv6 in my router but DNS66 doesn't work too. Always this error occours: Verbindung konnte nicht wiederhergestellt werden. What can I do?

**Comment by cocokola** [comment]
Not sure I follow, it works with your mobile data but not with wifi?

**Comment by Lavater** [comment]
At the moment it only works with mobile date not with wifi and IPv6 oder IPv4. Thought, IPv6 was the reason why ... But it's wifi in general.

**Comment by julian-klode** [comment]
It does work fine in ipv4 only. If it does not work for you, well, there isn't really much I can do about that.

**Comment by Lavater** [comment]
Ok. Thank you. Worked fine for a long time. Loved DNS66. Don't know why it has problems with One UI.
