### ISSUE TITLE
Connection was interrupted in Chrome

### ISSUE THREAD

**Issue by Jostian** [julian-klode/dns66#379]
Everytime I change websites I get this "connection was interrupted" pop up in Chrome, when I disable dns66 no problems,  please fix, thanks.

**Comment by julian-klode** [comment]
Works for me. Maybe something is wrong with your phone. I don't really care. If you have proof that something is wrong in DNS66, like a logcat that shows it crashing somewhere or reconnecting, I can reconsider, but without that, this is nothing actionable.

**Comment by Jostian** [comment]
If you don't care then I sure as hell don't!
