### ISSUE TITLE
Power button Issue in 7.1

### ISSUE THREAD

**Issue by BroadcastJunkie** [julian-klode/dns66#38]
Power button won't turn on in 7.1 on the Pixel

works fine on the 5X

**Comment by julian-klode** [comment]
Are you having an always-on vpn service? For example, Project Fi's WiFi assistant thing seems to block DNS66 (and other VPN service implementations) from working.

**Comment by BroadcastJunkie** [comment]
ahh, I am on project fi. 

just shut off the wifi assistant. its good now. Thanks for the quick reply bud. great app so far!

**Comment by julian-klode** [comment]
JTFR: I'll keep this bug open to remind me to add an error message.

**Comment by BroadcastJunkie** [comment]
Sounds good, I didn't even think to look haha. An message would be good. Thanks again Julian
