### ISSUE TITLE
DNS66 reverses the order of the system DNS servers

### ISSUE THREAD

**Issue by Platway** [julian-klode/dns66#382]
When my Android phone connects to my home WiFi, the primary DNS server is 192.168.1.1, and the secondary is 8.8.8.8. "Custom DNS servers" are disabled in DNS66.

According to the logcat, DNS66 uses 8.8.8.8 as DNS server prior to 192.168.1.1. This is unreasonable. Why does DNS66 reverses the order of the system DNS servers?

DNS66 version is 0.6.1.

**Comment by julian-klode** [comment]
It does not. It creates one virtual dns server for each system DNS server, it's up to Android to pick one. Android is fairly quick to switch it's DNS servers.

**Comment by julian-klode** [comment]
Yuck, so Android seems to have switched the order in which DNS servers are returned, I'm not sure what can be done here, but this needs more investigation.

02-28 20:58:01.080 10397 20220 I AdVpnThread: Got DNS servers = [/8.8.8.8, /2a02:908:2813:4180:d63f:cbff:fe85:ee4, /192.168.0.1]         
02-28 20:58:01.080 10397 20220 D AdVpnThread: configure: Adding IPv6 address/2001:db8::                                                       
02-28 20:58:01.081 10397 20220 I AdVpnThread: configure: Adding DNS Server /8.8.8.8 as 192.0.2.2                                
02-28 20:58:01.081 10397 20220 I AdVpnThread: configure: Adding DNS Server /2a02:908:2813:4180:d63f:cbff:fe85:ee4 as /2001:db8::3             
02-28 20:58:01.081 10397 20220 I AdVpnThread: configure: Adding DNS Server /192.168.0.1 as 192.0.2.4

**Comment by julian-klode** [comment]
Ah yikes, their in a HashSet, that's not ordered
