### ISSUE TITLE
Add DuckDuckGo's Tracker Radar List

### ISSUE THREAD

**Issue by rudolph4404** [julian-klode/dns66#385]
DuckDuckGo has come out with a new host list.
GitHub - duckduckgo/tracker-radar
https://github.com/duckduckgo/tracker-radar
Please add it to the app.

**Comment by julian-klode** [comment]
There is no host list there afaict

**Comment by WizADSL** [comment]
This blog post talks about the lists.  https://spreadprivacy.com/duckduckgo-tracker-radar/

**Comment by alexanderadam** [comment]
> There is no host list there afaict

Did you have a look at their repository?
For instance at [this host list of trackers](https://github.com/duckduckgo/tracker-radar/blob/master/build-data/static/categorized_trackers.csv)?

**Comment by julian-klode** [comment]
I've decided to add this list, enable it by default for new users, but keep it disabled for existing users. Or do we want to enable this for existing users by default too?

**Comment by julian-klode** [comment]
This change has been reverted, and the list will automatically be disabled for all users on upgrade to 0.6.8.

The list caused a lot of breakage in websites, see #435.

It will not be re-enabled at a later point either, given the privacy concerns about all the tracking blockada does, phoning home to them is not a good idea.
