### ISSUE TITLE
YouTube Is showing ads

### ISSUE THREAD

**Issue by GKid94** [julian-klode/dns66#388]
YouTube still shows ads

![Screenshot_2020-03-16-07-19-01](https://user-images.githubusercontent.com/18757054/76728336-b7fed100-6756-11ea-80b9-ddf86bbd0903.png)
![Screenshot_2020-03-16-07-19-09](https://user-images.githubusercontent.com/18757054/76728345-bc2aee80-6756-11ea-98d8-820308d9c596.png)
![Screenshot_2020-03-16-07-19-20](https://user-images.githubusercontent.com/18757054/76728349-c0570c00-6756-11ea-835e-1b8aa150958c.png)

**Comment by vatsalchandan** [comment]
yt, insta, fb serves ads via https from where content is served so you can't avoid those ads via this domain/host based blocking

**Comment by julian-klode** [comment]
Thanks @vatsalchandan
