### ISSUE TITLE
How to unblock a specific site

### ISSUE THREAD

**Issue by MasterPlexus** [julian-klode/dns66#390]
Hi,

Using dns66 now for a long time, but unfortunately one issue was not able to solve for me. I would like to unblock in generally some sites. For example heise.de will be blocked in chrome sometimes with DNS_PROBE_FINISHED_BAD_CONFIG
I've tried to made one whitelist with the domain heise.de, but this seems to be alsonnot working. So is there a clear description how to made a working whitelist? 
Thanks

**Comment by julian-klode** [comment]
If it's only inaccessible *sometimes* it's not blocked by dns66.

Apart from that, the documentation in the app is quite clear: the last entry wins. So if the last entry is a whitelist one for heise.de it would override any previous blocks of it.

**Comment by MasterPlexus** [comment]
I could not say what is the trigger that it is blocked, but it is blocked by dns66. In logcat it is mentioned:
`04-10 16:57:13.811  7588 10681 I DnsPacketProxy: handleDnsRequest: DNS Name heise.de Blocked!`

On the documentation I mean more, how the whitelist file should be build up. Is it enough to just write every whithelist host per line? Must there be also something before (an IP address maybe)? I'm asking that, as I try to understand the downloaded block lists and they are not clear for me...
