### ISSUE TITLE
using with orbot

### ISSUE THREAD

**Issue by 0142929** [julian-klode/dns66#391]
hello
i trying use dns66 with orbot, but it kick together from vpn connection, vpn cascsde not working too.
how possible redirect part or all traffic to orbot proxy server to unlock bloked resources? thanks

**Comment by julian-klode** [comment]
That does not work. Only one VPN can run at a time on Android. I do think that's somewhat tracked in #77

**Comment by julian-klode** [comment]
Ah no #96 / #188

**Comment by 0142929** [comment]
i see, so there are no way to use dns66 and orbot in non root vpn mode together.
thank you.
