### ISSUE TITLE
http://www.whatsmydnsserver.com/

### ISSUE THREAD

**Issue by compusolve-rsa** [julian-klode/dns66#394]
I keep getting google dns servers back from this site even when only one if the default non-us DNS server is selected in dns66.

Oh yeah, I got netguard running on the phone as well. Maybe a conflict?

Your DNS Server154.119.32.102Owner of this serverSnowball IP2Status of this serverEverything is fine | Your DNS Server | 154.119.32.102 | Owner of this server | Snowball IP2 | Status of this server | Everything is fine
-- | -- | -- | -- | -- | -- | --
Your DNS Server | 154.119.32.102
Owner of this server | Snowball IP2
Status of this server | Everything is fine
Your DNS Server74.125.181.5Owner of this serverGoogleStatus of this serverEverything is fine | Your DNS Server | 74.125.181.5 | Owner of this server | Google | Status of this server | Everything is fine
Your DNS Server | 74.125.181.5
Owner of this server | Google
Status of this server | Everything is fine
Your DNS Server172.253.215.8Owner of this serverGoogle LLCStatus of this serverEverything is fine | Your DNS Server | 172.253.215.8 | Owner of this server | Google LLC | Status of this server | Everything is fine
Your DNS Server | 172.253.215.8
Owner of this server | Google LLC
Status of this server | Everything is fine

**Comment by leaumar** [comment]
I don't work on this project, but please change this ticket's title to something that actually describes your issue. It's better that way for the maintainers, and for people like me trying to see if their issue already exists.

**Comment by julian-klode** [comment]
Yes, it is sort of expected that DNS requests can leak, we cannot block DNS requests to other servers, only add our own ones.
