### ISSUE TITLE
VPN refuses to work on roaming

### ISSUE THREAD

**Issue by NoahJelen** [julian-klode/dns66#395]
As the title says, the VPN refuses to work in roaming mode. Here is a screenshot of my issue and the logcat.
![Screenshot_20200521-191627_DNS66](https://user-images.githubusercontent.com/29718341/82624747-31bc9c00-9b98-11ea-9d12-bfdb0d396dd0.jpg)
[DNS66 Logcat.txt](https://github.com/julian-klode/dns66/files/4665742/DNS66.Logcat.txt)

**Comment by julian-klode** [comment]
I feel like this is a feature of the ROM:

`Caused by: android.system.ErrnoException: sendto failed: EPERM (Operation not permitted)`

Don't see anything to do on this side.
