### ISSUE TITLE
DNS66 doesn't filter WebRTC traffic ads

### ISSUE THREAD

**Issue by sambul13** [julian-klode/dns66#396]
Just tried v 0.6.5 in Android 10, and it doesn't filter ads coming through TextNow and similar VoIP apps using WebRT for voice and probably SMS and data. Anyone can suggest, how to filter the ads?  They show up in the TextNow GUI and also popups in Android System GUI.

**Comment by TheSimArchitect** [comment]
I was testing it around and I noticed that Freda also shows ads.

**Comment by julian-klode** [comment]
Not a bug in the app. I suggest you find out what stuff needs blocking by investigating logcat, and then get things blocked by the blocklist provider you use. If that's filterable at all.

**Comment by TheSimArchitect** [comment]
> Not a bug in the app. I suggest you find out what stuff needs blocking by investigating logcat, and then get things blocked by the blocklist provider you use. If that's filterable at all.

Thank you very much for the app and for the feedback. So far so good (as much as possible, of course, the fight with _"anti x 
 anti ad blocking"_ continues LOL)!
