### ISSUE TITLE
Photos in Google Inbox (gmail) apps don't load when connected

### ISSUE THREAD

**Issue by ethanhunt123** [julian-klode/dns66#40]
When a email is received with a photo attached, they wont show or load when connected to the dns66 vpn.

**Comment by julian-klode** [comment]
That's probably another instance of #31 ? That is, Nougat's DownloadManager being broken on the Android side.

**Comment by ethanhunt123** [comment]
Ah I think you might be correct

**Comment by julian-klode** [comment]
This should be "fixed" with the whitelisting in #31.
