### ISSUE TITLE
Logcat export is not working most of the time

### ISSUE THREAD

**Issue by alexanderadam** [julian-klode/dns66#404]
_Sometimes_ it's working but mostly it isn't.

Sometimes nothing happens and sometimes a notification appears (`Not supported: java.lang.RuntimeException: Failure from system`)

![Screenshot_20200702-184751_DNS66](https://user-images.githubusercontent.com/372620/86720712-92f3de00-c025-11ea-8b20-cf7ce47b358b.png)

It usually starts working again after a reboot.
This is a Samsung S9 on Android 10 (One UI 2.1, Kernel `4.9.118-18847185`, build `QP1A.190711.020.G960FXXU9ETF5`).

If you need more information, just tell me how I can get it.

**PS:** I'm not sure whether this is helpful but Samsung allows to use phones remotely if you make an user account: https://developer.samsung.com/remotetestlab/

**Comment by julian-klode** [comment]
Without a logcat I can't do much here, I guess even not then. Also I don't care much, I get too many logcats anyway - most are fine, so it's mostly noise at this point.
