### ISSUE TITLE
DNS over HTTPS

### ISSUE THREAD

**Issue by alexanderadam** [julian-klode/dns66#405]
It would be great if DNS66 would have support for DNS over HTTPS.
[It was asked earlier already](https://github.com/julian-klode/dns66/issues/27#issuecomment-531209917) and other blockers like [personaldnsfilter seem to support this](https://github.com/IngoZenz/personaldnsfilter/commit/fa7fb10062dde7b7ff34cd1f7d8681a0724afd85) as well (and [blokada has at least an open PR](https://github.com/blokadaorg/blokada/pull/558) for it).

This way it wouldn't be necessary to [turn DoH off on newer devices](https://github.com/julian-klode/dns66/wiki/How-to-debug-when-DNS66-isn't-blocking-ads-and-other-common-pitfalls).

**Comment by julian-klode** [comment]
#11 and no, you'd still have to turn off that setting anyway.

**Comment by alexanderadam** [comment]
I right. I'm sorry! I had a local http server in mind that could being pointed to. But this doesn't make any sense of course.
