### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by danithehuman** [julian-klode/dns66#407]
Today my phone (Samsung galaxy s10 plus) was suddenly and persistently unable to connect... No error message.
I tried to restore to default settings, and after that I also tried to reinstall completely, both to no avail...

**Comment by danithehuman** [comment]
I suppose it's because of the system upgrade with stricter safety measures. No idea how to get past that..

**Comment by fylim** [comment]
Not sure if it is related. I am trying to install and setup on my Nvidia Shield TV and it just says reconnecting. DNS66 still works on my S8+ running June security update.

**Comment by Kerish10** [comment]
> Today my phone (Samsung galaxy s10 plus) was suddenly and persistently unable to connect... No error message.
> I tried to restore to default settings, and after that I also tried to reinstall completely, both to no avail...

Same for me since the update it no longer works

**Comment by julian-klode** [comment]
I'm sorry, but there's nothing I can contribute here. If there's a logcat with a crash in it, please open a new issue.
