### ISSUE TITLE
Force closed after downloading a host then pressing start

### ISSUE THREAD

**Issue by zputnyq** [julian-klode/dns66#411]
Hello Julian,
I get a force closed on v 0.6.6 after downloading a host then pressing start, on v 0.6.5 it's fine, I'm on xperia m4 stock kernel & stock android 6.0.1. Logcat attached. I'm not really good at taking a log. Hope it could help
[logcat_09-24-2020_14-12-26.txt](https://github.com/julian-klode/dns66/files/5280704/logcat_09-24-2020_14-12-26.txt)

**Comment by julian-klode** [comment]
This is probably a regression in dnsjava

**Comment by julian-klode** [comment]
Upgraded dnsjava in git to 3.3.1, but not sure if it helps. Let me know if this is still a problem once 0.6.7 is out.

**Comment by Tiggy22** [comment]
I too have this problem with 0.6.6 and 0.6.7. I use a Nexus 10 tablet with Android 5.1.1. When I start dns66, I get a message 'Unfortunately dns66 has stopped'. V0.6.7 works with my Moto G5 using Android 8.1.0. Please let me know how I can give you more info. Thanks

**Comment by zputnyq** [comment]
Still crash @julian-klode 
Here's a new log
[logs-2021-02-17-16-45-44.zip](https://github.com/julian-klode/dns66/files/5994755/logs-2021-02-17-16-45-44.zip)

@Tiggy22 if your device is rooted you can use an app to take a logcat

**Comment by notNSANE** [comment]
this is happening to me too on a device running Android 6 as soon as I press start.

How do I take a logcat?

**Comment by tbertels** [comment]
Same here on Android 6.0.1, here's a logcat:
[logcat Android 6.txt](https://github.com/julian-klode/dns66/files/6180910/logcat.Android.6.txt)

**Comment by julian-klode** [comment]
Please test the 0.6.8 release and report back if that fixes the issue. I have reverted dnsjava from 3.2.2 to 3.0.0 but sticking to an old version is obviously not a long term solution.

**Comment by julian-klode** [comment]
If the consensus is that Android 8 works fine, it's probably worth raising the requirements to prevent installs on older releases. I don't think any Android version prior to 9 gets updates anyway.

**Comment by notNSANE** [comment]
it didn't crash on Android 5.1 :)

**Comment by Tiggy22** [comment]
I cannot find the download link for 0.6.8. Can you please help.Thanks

**Comment by notNSANE** [comment]
> I cannot find the download link for 0.6.8. Can you please help.Thanks

https://github.com/julian-klode/dns66/releases/tag/v0.6.8

**Comment by Tiggy22** [comment]
Thanks. How do I download the app after I extract the zip file

**Comment by notNSANE** [comment]
the .apk is the app... download that then install it

**Comment by Tiggy22** [comment]
I found it under Assets. It now works fine on my Nexus 10 with Android 5.1.1.
Many thanks Julian

**Comment by zputnyq** [comment]
Thank you @julian-klode 
It works fine with 0.6.8.
