### ISSUE TITLE
google play store bypassing dns

### ISSUE THREAD

**Issue by uncebobo** [julian-klode/dns66#412]
Google play is giving itself permission to bypass dns after app is closed and reopened. Set to No Apps Bypass By Default.
Play store and associated services have been disabled however, Play store is still getting permission to bypass dns66.
Looking for workaround or fix.

**Comment by julian-klode** [comment]
You can't have an empty list of exceptions, if it's empty, the play store is added. Because um, the list was empty, and then I had to add play store and roll it out to people because they were no longer getting any updates

**Comment by munchkinguy** [comment]
So if you make an exception for a different app, you can disable the exception for Google Play Store?

**Comment by uncebobo** [comment]
I don't want updates from google anything. At first DNS66 helped to block google. Then I noticed it kept allowing google play to bypass automatically. (my clue that google play was phoning home again was that data usage was going through the roof again for no aparant reason) Now however, after the last update of DNS66, it all seems to be working as expected again. IDK?
