### ISSUE TITLE
Version 0.6.6 crashes on Android 6.0.1

### ISSUE THREAD

**Issue by Gatienzo** [julian-klode/dns66#413]
DNS66 version 0.6.6 crashes on Android 6.0.1 Samsung J5 phone.
I had to uninstall and revert to v. 0.6.5

**Comment by AxelDominatoR** [comment]
I have the same issue on Android 5.0.1 on a Lenovo Yoga Tablet 2-1050F. I suspect it may be related to the commit: 35bfb3237aad3a4ff24b4abde1f4517c30d69a06

**Comment by shom13** [comment]
I have the same issue on my older devices running android 5.1.1 and 6 respectively, but i can confirm it works on android 7 and 10. As soon as i launch the app, it says unfortunately dns66 has stopped.

**Comment by julian-klode** [comment]
I assume this is a duplicate of #411 which is a regression in dnsjava. Given that there are no logfiles it's hard to say, but it certainly is a crash on 6.0.1
