### ISSUE TITLE
0.6.6. VPN gets queried but doesn't work

### ISSUE THREAD

**Issue by daniel-lo** [julian-klode/dns66#414]
Xiaomi Mi 9 T Pro MIUI 12 .. I get the VPN allow requst and the app shows active in the notifications but I don't get the VPM symbol in the top bar. Ultimately nothing is filtered.

**Comment by daniel-lo** [comment]
having picked up the phone again just now I see the VPN symbol .. but toggling the service to Off doesn't remove it. Very strange behaviour. Will probably take a while before it disappears.

**Comment by julian-klode** [comment]
I cannot provide any support for MIUI phones.
