### ISSUE TITLE
Stopped functioning after Android 10 update

### ISSUE THREAD

**Issue by boogarsugar** [julian-klode/dns66#416]
After tablet updated from android 9 to 10 it seems to have stopped functioning. Still works fine on 7. was going to let it go and wait to see if update would fix it but thought i should say something cause why not? Sorry if this has been addressed before I don't feel like searching to see if it's been brought up. Big fan byeeeee

**Comment by julian-klode** [comment]
This is not a support forum (that's http://forum.xda-developers.com/android/apps-games/app-dns66-source-host-ad-blocker-root-t3487497), and there are no log files provided, so this is not actionable.
