### ISSUE TITLE
[URGENT] App makes my wifi go berserk

### ISSUE THREAD

**Issue by abh-oss01** [julian-klode/dns66#421]
I ran into some serious problems after using this app.

Just a SECOND after I enabled it, it f#*ked my wifi router (idk how!)
but it did, and my wifi (and the router) completly shut itself down...

I had to first turn off dns66 on my phone, then forget the wifi on the phone and then restart my router, mind you though, all my other devices could **not** connect to that wifi as well, what happened?

It seemed like the router suddenly lost it's mind, **right** after turning on dns66.

 PLS HELP ASAP

Android version: 10
Dns66: v0.6.6
Dns66 downloaded from F-Droid

**Comment by julian-klode** [comment]
It seems silly to blame dns66 for your wifi going beserk, it's just a dns proxy.

**Comment by abh-oss01** [comment]
Pls, I'm serious...
