### ISSUE TITLE
[feature request] Hosts with asterisks

### ISSUE THREAD

**Issue by mtxadmin** [julian-klode/dns66#423]
Hello.

Will DNS66 support host file format with asterisk(s)?

For example, we need to block doubleclick.net and all its subdomains. For that we can use:

**Host rules with asterisks** (leading asterisks are supported by Blokada v4, at least. In case of uBlock Origin, you can write only domain, it will block all subdomains too. Maybe, pi-hole and some other tools):

doubleclick.net
*.doubleclick.net

**Classic host file format rules** - need to detect and list ALL subdomains. This drastically increase required RAM for app:

doubleclick.net
1016557.fls.doubleclick.net
1268402.fls.doubleclick.net
1295336.fls.doubleclick.net
1326154.fls.doubleclick.net
1330903.fls.doubleclick.net
1359940.fls.doubleclick.net
1412173.fls.doubleclick.net
1435575.fls.doubleclick.net
1513878.fls.doubleclick.net
1742177.fls.doubleclick.net
2013561.fls.doubleclick.net
2196503.fls.doubleclick.net
2332696.fls.doubleclick.net
2463678.fls.doubleclick.net
2499034.fls.doubleclick.net
2507573.fls.doubleclick.net
2542116.fls.doubleclick.net
2579983.fls.doubleclick.net
2793343.fls.doubleclick.net
2856095.fls.doubleclick.net
2859333.fls.doubleclick.net
2895566.fls.doubleclick.net
2896678.fls.doubleclick.net
2946702.fls.doubleclick.net
3130320.fls.doubleclick.net
3276817.fls.doubleclick.net
3300547.fls.doubleclick.net
3402806.fls.doubleclick.net
3474132.fls.doubleclick.net
3488627.fls.doubleclick.net
3501113.fls.doubleclick.net
3569344.fls.doubleclick.net
3642305.fls.doubleclick.net
3670816.fls.doubleclick.net
3738527.fls.doubleclick.net
3765329.fls.doubleclick.net
3773523.fls.doubleclick.net
3797690.fls.doubleclick.net
3879194.fls.doubleclick.net
3896619.fls.doubleclick.net
3941123.fls.doubleclick.net
3973258.fls.doubleclick.net
3975371.fls.doubleclick.net
3982178.fls.doubleclick.net
3ad.doubleclick.net
4017114.fls.doubleclick.net
4053494.fls.doubleclick.net
4177752.fls.doubleclick.net
4191036.fls.doubleclick.net
4191748.fls.doubleclick.net
4215108.fls.doubleclick.net
4216959.fls.doubleclick.net
4218562.fls.doubleclick.net
4228414.fls.doubleclick.net
4235225.fls.doubleclick.net
4236808.fls.doubleclick.net
4275977.fls.doubleclick.net
4292932.fls.doubleclick.net
4298961.fls.doubleclick.net
4299553.fls.doubleclick.net
4331660.fls.doubleclick.net
4338244.fls.doubleclick.net
4345210.fls.doubleclick.net
4360661.fls.doubleclick.net
4367576.fls.doubleclick.net
4368131.fls.doubleclick.net
4371920.fls.doubleclick.net
4375326.fls.doubleclick.net
4379742.fls.doubleclick.net
4385306.fls.doubleclick.net
4397448.fls.doubleclick.net
4402211.fls.doubleclick.net
4407048.fls.doubleclick.net
4441444.fls.doubleclick.net
4457442.fls.doubleclick.net
4480452.fls.doubleclick.net
4488142.fls.doubleclick.net
4488211.fls.doubleclick.net
4488352.fls.doubleclick.net
4490791.fls.doubleclick.net
4497209.fls.doubleclick.net
4514783.fls.doubleclick.net
4611243.fls.doubleclick.net
4625549.fls.doubleclick.net
4645703.fls.doubleclick.net
4684100.fls.doubleclick.net
4704202.fls.doubleclick.net
4711400.fls.doubleclick.net
4755428.fls.doubleclick.net
4846802.fls.doubleclick.net
4852758.fls.doubleclick.net
4898337.fls.doubleclick.net
4914190.fls.doubleclick.net
4923503.fls.doubleclick.net
4953227.fls.doubleclick.net
4953832.fls.doubleclick.net
5049321.fls.doubleclick.net
5118230.fls.doubleclick.net
5129396.fls.doubleclick.net
5217566.fls.doubleclick.net
5273478.fls.doubleclick.net
5291104.fls.doubleclick.net
5343463.fls.doubleclick.net
5362399.fls.doubleclick.net
5369020.fls.doubleclick.net
5504326.fls.doubleclick.net
5522463.fls.doubleclick.net
5582200.fls.doubleclick.net
5583432.fls.doubleclick.net
5617400.fls.doubleclick.net
5724437.fls.doubleclick.net
5987900.fls.doubleclick.net
5990802.fls.doubleclick.net
6059349.fls.doubleclick.net
6076607.fls.doubleclick.net
6100744.fls.doubleclick.net
6102726.fls.doubleclick.net
6204885.fls.doubleclick.net
6220880.fls.doubleclick.net
6284171.fls.doubleclick.net
6286727.fls.doubleclick.net
6494367.fls.doubleclick.net
6631903.fls.doubleclick.net
6679503.fls.doubleclick.net
6679518.fls.doubleclick.net
6763511.fls.doubleclick.net
6786204.fls.doubleclick.net
6901690.fls.doubleclick.net
690341.fls.doubleclick.net
7077341.fls.doubleclick.net
8048412.fls.doubleclick.net
8052794.fls.doubleclick.net
8076233.fls.doubleclick.net
8082370.fls.doubleclick.net
8086822.fls.doubleclick.net
8086983.fls.doubleclick.net
8102118.fls.doubleclick.net
8103035.fls.doubleclick.net
8140952.fls.doubleclick.net
8171830.fls.doubleclick.net
8208269.fls.doubleclick.net
8209809.fls.doubleclick.net
8211687.fls.doubleclick.net
8247166.fls.doubleclick.net
8250920.fls.doubleclick.net
8267269.fls.doubleclick.net
8296073.fls.doubleclick.net
8299733.fls.doubleclick.net
8372783.fls.doubleclick.net
8375926.fls.doubleclick.net
8386062.fls.doubleclick.net
8390061.fls.doubleclick.net
8392543.fls.doubleclick.net
8401466.fls.doubleclick.net
8464371.fls.doubleclick.net
8551706.fls.doubleclick.net
8555628.fls.doubleclick.net
8563148.fls.doubleclick.net
8671752.fls.doubleclick.net
8741445.fls.doubleclick.net
8760626.fls.doubleclick.net
8766361.fls.doubleclick.net
8775178.fls.doubleclick.net
8780911.fls.doubleclick.net
8810881.fls.doubleclick.net
8836830.fls.doubleclick.net
8865321.fls.doubleclick.net
8865694.fls.doubleclick.net
8882018.fls.doubleclick.net
8893231.fls.doubleclick.net
8918841.fls.doubleclick.net
8928768.fls.doubleclick.net
8930017.fls.doubleclick.net
8951737.fls.doubleclick.net
8954066.fls.doubleclick.net
8954315.fls.doubleclick.net
8993007.fls.doubleclick.net
9021372.fls.doubleclick.net
9035465.fls.doubleclick.net
9049143.fls.doubleclick.net
9057842.fls.doubleclick.net
9094272.fls.doubleclick.net
9105758.fls.doubleclick.net
9108332.fls.doubleclick.net
9115121.fls.doubleclick.net
9130649.fls.doubleclick.net
9147378.fls.doubleclick.net
9151807.fls.doubleclick.net
9168233.fls.doubleclick.net
9169260.fls.doubleclick.net
9227827.fls.doubleclick.net
9230979.fls.doubleclick.net
9234492.fls.doubleclick.net
9235530.fls.doubleclick.net
9240337.fls.doubleclick.net
9256301.fls.doubleclick.net
9264029.fls.doubleclick.net
9270163.fls.doubleclick.net
9273075.fls.doubleclick.net
9287494.fls.doubleclick.net
9289143.fls.doubleclick.net
9295353.fls.doubleclick.net
9298081.fls.doubleclick.net
9308589.fls.doubleclick.net
9308843.fls.doubleclick.net
9309192.fls.doubleclick.net
9317660.fls.doubleclick.net
9331818.fls.doubleclick.net
9332076.fls.doubleclick.net
9346212.fls.doubleclick.net
9369322.fls.doubleclick.net
9395210.fls.doubleclick.net
ad.3au.doubleclick.net
ad.ae.doubleclick.net
ad.ar.doubleclick.net
ad.at.doubleclick.net
ad.au.doubleclick.net
ad.be.doubleclick.net
ad.bg.doubleclick.net
ad.br.doubleclick.net
ad.ca.doubleclick.net
ad.ch.doubleclick.net
ad.cl.doubleclick.net
ad.cn.doubleclick.net
ad.co.doubleclick.net
ad.cz.doubleclick.net
ad.de.doubleclick.net
ad.dk.doubleclick.net
ad.doubleclick.net
ad.eg.doubleclick.net
ad.es.doubleclick.net
ad.fi.doubleclick.net
ad.fr.doubleclick.net
ad.gr.doubleclick.net
ad.gt.doubleclick.net
ad.hk.doubleclick.net
ad.hr.doubleclick.net
ad.hu.doubleclick.net
ad.ie.doubleclick.net
ad.il.doubleclick.net
ad.in.doubleclick.net
ad.is.doubleclick.net
ad.it.doubleclick.net
ad.jp.doubleclick.net
ad.kr.doubleclick.net
ad.kw.doubleclick.net
ad.ma.doubleclick.net
ad.mo.doubleclick.net
ad.mx.doubleclick.net
ad.my.doubleclick.net
ad.n2434.doubleclick.net
ad.nl.doubleclick.net
ad.no.doubleclick.net
ad.nz.doubleclick.net
ad.pe.doubleclick.net
ad.ph.doubleclick.net
ad.pl.doubleclick.net
ad.pt.doubleclick.net
ad.ro.doubleclick.net
ad.rs.doubleclick.net
ad.ru.doubleclick.net
ad.sa.doubleclick.net
ad.se.doubleclick.net
ad.sg.doubleclick.net
ad.si.doubleclick.net
ad.sk.doubleclick.net
ad.terra.doubleclick.net
ad.th.doubleclick.net
ad.tr.doubleclick.net
ad.tw.doubleclick.net
ad.uk.doubleclick.net
ad.us.doubleclick.net
ad.ve.doubleclick.net
ad.za.doubleclick.net
ad2.doubleclick.net
ad-ace.doubleclick.net
ad-apac.doubleclick.net
adclick.g.doubleclick.net
ad-emea.doubleclick.net
ad-g.doubleclick.net
ads-bid.l.doubleclick.net
advertisers.doubleclick.net
adx.g.doubleclick.net
ad-yt-bfp.doubleclick.net
amn.doubleclick.net
betaadvertisers.doubleclick.net
betareportcentral.doubleclick.net
bid.g.doubleclick.net
cm.g.doubleclick.net
creatives.doubleclick.net
dart.l.doubleclick.net
default.fls.doubleclick.net
dfp.doubleclick.net
dfpreports.doubleclick.net
dmp.doubleclick.net
dnb.doubleclick.net
dp.g.doubleclick.net
dsm.doubleclick.net
dsmreports.doubleclick.net
ebay.doubleclick.net
ebaycn.doubleclick.net
ebaytw.doubleclick.net
emea.doubleclick.net
exnjadgda1.doubleclick.net
exnjadgda2.doubleclick.net
exnjadgds1.doubleclick.net
exnjmdgda1.doubleclick.net
exnjmdgds1.doubleclick.net
feedads.g.doubleclick.net
fls.au.doubleclick.net
fls.doubleclick.net
fls.uk.doubleclick.net
g.doubleclick.net
g3.doubleclick.net
gan.doubleclick.net
gd1.doubleclick.net
gd10.doubleclick.net
gd11.doubleclick.net
gd12.doubleclick.net
gd13.doubleclick.net
gd14.doubleclick.net
gd15.doubleclick.net
gd16.doubleclick.net
gd17.doubleclick.net
gd18.doubleclick.net
gd19.doubleclick.net
gd2.doubleclick.net
gd20.doubleclick.net
gd21.doubleclick.net
gd22.doubleclick.net
gd23.doubleclick.net
gd24.doubleclick.net
gd25.doubleclick.net
gd26.doubleclick.net
gd27.doubleclick.net
gd28.doubleclick.net
gd29.doubleclick.net
gd3.doubleclick.net
gd30.doubleclick.net
gd31.doubleclick.net
gd4.doubleclick.net
gd5.doubleclick.net
gd7.doubleclick.net
gd8.doubleclick.net
gd9.doubleclick.net
googleads.g.doubleclick.net
googleads1.g.doubleclick.net
googleads2.g.doubleclick.net
googleads3.g.doubleclick.net
googleads4.g.doubleclick.net
help.doubleclick.net
ir.doubleclick.net
iv.doubleclick.net
jp.doubleclick.net
learn.doubleclick.net
ln.doubleclick.net
m.doubleclick.net
m1.doubleclick.net
m2.cn.doubleclick.net
m2.doubleclick.net
m3.doubleclick.net
m4.doubleclick.net
m5.doubleclick.net
m6.doubleclick.net
m7.doubleclick.net
m8.doubleclick.net
m9.doubleclick.net
mediavisor.doubleclick.net
mobile-displayads.l.doubleclick.net
motifcdn.doubleclick.net
motifcdn2.doubleclick.net
n3302ad.doubleclick.net
n3349ad.doubleclick.net
n4052ad.doubleclick.net
n4061ad.hk.doubleclick.net
n4403ad.doubleclick.net
n479ad.doubleclick.net
optimize.doubleclick.net
pagead.l.doubleclick.net
pagead46.l.doubleclick.net
partnerad.l.doubleclick.net
paypalssl.doubleclick.net
pubads.g.doubleclick.net
publisherportal.doubleclick.net
rd.intl.doubleclick.net
remarketing.doubleclick.net
reportcentral.doubleclick.net
reports.doubleclick.net
s0.doubleclick.net
s1.doubleclick.net
s2.video.doubleclick.net
salesmanager.doubleclick.net
search.doubleclick.net
secureframe.doubleclick.net
securepubads.g.doubleclick.net
sitedirectory.doubleclick.net
static.doubleclick.net
stats.g.doubleclick.net
stats.l.doubleclick.net
studio.doubleclick.net
survey.g.doubleclick.net
thngw1.doubleclick.net
thngw2.doubleclick.net
twx.doubleclick.net
uk.doubleclick.net
uunyadgda1.doubleclick.net
uunyadgds1.doubleclick.net
www.doubleclick.net
www2.doubleclick.net
www3.doubleclick.net

**Comment by julian-klode** [comment]
Support for wildcards is hard and requires fundamental changes to how the database is stored, which has unknown implications on memory and CPU usage. Someone has to write code to compile all the wildcards into a state machine that we can then follow, the requirement for lookup is that it's amortized O(1) and does not have too fragmented memory.

The easy hack is to concatenate everything into a regex and then compile that. That however has vast overhead for the conversion of wildcard to regex and compilation of the regex, with unknown performance characteristics for the execution, which is why I'd prefer a different solution.

Effectively, these patterns form a suffix tree. We build a trie and traverse it backwards with the given url. Each node may be flagged wildcard or final. Each character progresses to a child of the node and we are done when we have reached:

- Success: The current node is marked wildcard
- Success: The current node is marked final and we have no more characters left
- Failure: We still have characters left, but the node has no children
- Failure: We ran out of characters but the node is not marked final or wildcard.

How to optimally represent that trie is the question, and I've not really looked into it.

**Comment by julian-klode** [comment]
After some research, it seems we want a double-array trie. We could even compile that just once and then store it.

**Comment by julian-klode** [comment]
I'm not convinced it's feasible to implement this in the layered approach we have where later entries override previous entries. Because if you deny *.example but then want to allow a.example you need to split the node such that a.example is allowed, but subdomains of a.example are still denied, and every other subdomain of example is still denied.

It would be much simpler if we simply had allow and deny lists and allow lists overrode deny lists, but that does not allow for some clever rules like deny a bunch of stuff, allow a subset of them, and deny another subset of those. e.g. `deny a, b, c; allow b, c; deny b` should deny `a, b` and allow `c`, whereas a allow/denylist would deny `a` and allow `b, c`.

**Comment by julian-klode** [comment]
Oh well, we should track that back in #33.

**Comment by mtxadmin** [comment]
Just for information: this feature is implemented in Blokada:
https://github.com/blokadaorg/blokada/
