### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [julian-klode/dns66#424]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by Korb** [comment]
Still no screenshots

![Screenshot_2023_0428_192519_org fdroid fdroid](https://user-images.githubusercontent.com/3509797/235202225-347a7d71-3ab1-4868-9926-192bbe4ba030.jpg)
