### ISSUE TITLE
Crashing with OutOfMemory but enough RAM

### ISSUE THREAD

**Issue by PavelNL** [julian-klode/dns66#425]
Similar issue to https://github.com/julian-klode/dns66/issues/407

Last couple of days DNS66 became unstable and today broke completely: "DNS66 keeps stopping" OS message, list of applications (APPS tab) is failing to load, only status shown before crash is "Connecting".

If I believe to logcat ;-), the error is: AdVpnThread OutOfMemory.

Application takes about 140MB before crashing, available RAM is 2.1GB. 

All information/proof is attached.

Asus Zenfone 5 (2018) with latest stock Android 9. Latest vendor patch was more than month ago.

No  changes in last month, except of installing Google Home app. Uninstalling this app does not help.

Reboot does not help either.

Please let me know if any other info is needed, before I try to re-install it?

**Comment by PavelNL** [comment]
[logcat_01-07-2021_19-39-06.txt](https://github.com/julian-klode/dns66/files/5784009/logcat_01-07-2021_19-39-06.txt)
[logcat_01-07-2021_19-52-45.txt](https://github.com/julian-klode/dns66/files/5784010/logcat_01-07-2021_19-52-45.txt)
![Screenshot_20210107-194804734](https://user-images.githubusercontent.com/2729870/103945928-3ab5aa00-5136-11eb-9f22-0033d9dd3b94.jpg)
![Screenshot_20210107-194934373](https://user-images.githubusercontent.com/2729870/103945932-3be6d700-5136-11eb-8e17-b184f2cbacb1.jpg)

**Comment by PavelNL** [comment]
PS: Sorry, this phone is not rooted, but ADB is still available

**Comment by PavelNL** [comment]
Latest version from F-Droid - 0.6.6, as of 9/18/20

**Comment by PavelNL** [comment]
Configuration:
[dns66.json.txt](https://github.com/julian-klode/dns66/files/5784026/dns66.json.txt)

**Comment by PavelNL** [comment]
Logcat from within app
[DNS66 Logcat.txt](https://github.com/julian-klode/dns66/files/5784048/DNS66.Logcat.txt)

**Comment by julian-klode** [comment]
I don't see what I can do about this. If you have some analysis of a memory leak and a fix, fine, but there's nothing here.
