### ISSUE TITLE
Incompatible with Samsung Max / Opera Max

### ISSUE THREAD

**Issue by ballo** [julian-klode/dns66#426]
Is there a way to gang dns66 with Samsung/Opera Max so I get the bandwidth savings of Max with the ad removal of dns66?

**Comment by julian-klode** [comment]
I have no idea. Maybe someone in the xda thread - http://forum.xda-developers.com/android/apps-games/app-dns66-source-host-ad-blocker-root-t3487497 - has an idea, I suggest you ask there.

According to https://www.theverge.com/2018/2/23/17043684/samsung-opera-max-privacy-management-data-saving-app there's a DNS masking thing in that app that you probably have to toggle off for it to use the phone's DNS servers.

**Comment by ballo** [comment]
Only option is to turn the VPN on or off (have mine off but it doesn't appear to matter either way). I've posted on XDA and hope for the best

-------- Original Message --------
