### ISSUE TITLE
It just... stopped working

### ISSUE THREAD

**Issue by Welding-Torch** [julian-klode/dns66#429]
I didn't do a system update recently, didn't change any major settings. One day DNS66 just stopped working. I tried it with two Wifi networks and also with Mobile Data.  No idea what went wrong. I tried Blockada and even that didn't work. 
I have no idea what changed, is it just me or are others experiencing this problem too?

Help is appreciated.
Thank you.

`--------- beginning of main
02-10 19:33:37.273  6853  6853 D MainActivity: onNewIntent: Wee
02-10 19:33:39.795  6853  6853 E RecyclerView: No adapter attached; skipping layout
02-10 19:33:40.683  6853 15735 W jak_linux.dns6: resources.arsc in APK '/data/app/com.instagram.android-eeaKFYpR7LKsAYxhQR3VWQ==/base.apk' is compressed.
02-10 19:33:41.450  6853 15735 W jak_linux.dns6: Unknown chunk type '200'.
02-10 19:33:43.095  6853 15735 W jak_linux.dns6: resources.arsc in APK '/data/app/com.lenovo.anyshare.gps-GfaULqsMqOpTKfzksieoXA==/base.apk' is compressed.
02-10 19:33:43.209  6853  6853 W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
02-10 19:33:43.230  6853  6853 I chatty  : uid=10345(org.jak_linux.dns66) identical 10 lines
02-10 19:33:43.230  6853  6853 W StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1`

**Comment by hartmms** [comment]
Same here, but I have pixel 3 XL and I just upgraded to Feburary's OS updates. I ensured DNS security was off, but I'm still getting ads. I'm trying to install 0.6.7, but for some reason it's refusing to install. "something went wrong. The app was not installed"

**Comment by hartmms** [comment]
I had to uninstall old version to install 0.6.7.  I now have blocked ads again.  Yea!

**Comment by Welding-Torch** [comment]
I too, uninstalled the old version and installed the latest update. But still I get ads.

**Comment by julian-klode** [comment]
This is not really a user support forum. It works for me, that's all I can say here.
