### ISSUE TITLE
dns66 just closes on its own. android 10 go edition 

### ISSUE THREAD

**Issue by boreddude001** [julian-klode/dns66#433]
i have sky devices elite b55 phone running android 10 go edition. 

it works fine for a while until i open a google app. then it closes on its own. and there are other apps that do the similar things like pi network app, instagram, snapchat, vent, whisper, youtube, google files and playstore. but it appears rather random, like,. sometimes one of these apps will close the dna66, other times, it won't.  I asked in the original xda forum thread about it but no one has replied yet. has anyone else experienced a similar thing?

**Comment by julian-klode** [comment]
Maybe you ran out of memory? I don't know, look at the logcat. If so, you gotta get a phone with more ram. Sorry
