### ISSUE TITLE
DNS66 does not work with certain apps

### ISSUE THREAD

**Issue by Arbiter1479** [julian-klode/dns66#435]
I transferred to a new phone recently (LG V40 to OnePlus 8T) and installed DNS66 normally from F-Droid.

The weird thing is apps that previously used to function fine with DNS66 running no longer works on the new phone.

Examples of such instances are:
- Artworks not loading in Pixiv (A popular Japanese art site)
- User icon thumbnails on YouTube Vanced showing blank or the broken image icon
- Some websites on chrome failing to load correctly (UI or themes borked or outright doesn't load, only showing a blank page) 

The weird thing is I did not have such issues with my previous phone, DNS66 worked correctly on Pixiv, blocking ads while still allowing artwork to be loaded and I could browse the Web normally even after Google Chrome removed the experimental flag of using a custom DNS provider. 

As a result, the only way to use some apps is to outright add it to the bypass list or pause DNS66 for the duration of the usage. 

Things I've tried doing to fix it:
- Reinstalling DNS66
- Clearing cache and data
- Updating host lists and DNS servers
- Switching from mobile data to WiFi and vice versa

**Comment by julian-klode** [comment]
This is the bug in the DuckDuckGo tracker list that Blokada compiled and that was enabled by default.

**Comment by julian-klode** [comment]
0.6.8 no longer adds the list for new users, and disables it for existing users.
