### ISSUE TITLE
"Block connections without VPN" results in loss of internet access

### ISSUE THREAD

**Issue by fredddd1** [julian-klode/dns66#438]
Settings -> Network and Internet -> VPN -> DNS66 -> Settings

When "Block connections without VPN" is enabled, the device will lose internet access.

I understand with this setting enabled, all data will be routed through DNS66 and any connections trying to do it otherwise will fail?

I can no longer browse in my browser which is not white listed in DNS66.

![Screenshot_20210403-145920_Settings](https://user-images.githubusercontent.com/80743272/113480632-a5f0ed00-9495-11eb-8c24-f9c549831d42.png)

**Comment by julian-klode** [comment]
Well, duh, it only handles DNS.
