### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by konstantinoslazos** [julian-klode/dns66#440]
At a forum I have joined, certain images coming from ibb or postimage are not showing. Instead, I see a "link like" text that is flashing in a small silver background. 
When I turn off DNS66 things are OK, when I turn it back on the problem appears again.

This is a link to a post with 3 such images.
https://www.insomnia.gr/forums/topic/764723-%CE%BC%CE%B7%CE%BD-%CF%80%CE%B5%CF%84%CE%AC%CF%84%CE%B5-%CF%84%CE%AF%CF%80%CE%BF%CF%84%CE%B1-%CF%87%CE%B1%CF%81%CE%AF%CF%83%CF%84%CE%B5-%CF%84%CE%BF-%CE%B5%CE%B4%CF%8E-v4/page/33/?tab=comments#comment-58564794

I'll upload a screenshot from firefox, same thing happens to chrome
![Screenshot_2021-04-07-22-05-53-517_org mozilla firefox](https://user-images.githubusercontent.com/82117297/113920710-d0bca780-97ed-11eb-8910-2cb8c98e267c.jpg)

**Comment by julian-klode** [comment]
That seems to be more of a question of which filters (host files) you have enabled than a DNS66 issue.
