### ISSUE TITLE
UI suggestion: "Follow system theme" setting for light or dark theme

### ISSUE THREAD

**Issue by fredddd1** [julian-klode/dns66#445]
Many apps these days are just configured by default to the follow the global system setting of dark or light theme.

In DNS66 you still have to manually configure this.

Would be great to support for those who use adaptive styling.

**Comment by julian-klode** [comment]
System theme was introduced in Android 10, and DNS66 automatically uses it since 0.6.3, released in February 2020. There is not even an option to change it anymore.
