### ISSUE TITLE
Vibrating and pop-up ads

### ISSUE THREAD

**Issue by jerryn70** [julian-klode/dns66#45]
Is there any way to block pop up ads and vibrating ads? I mean when i try to download files from some sites my phone starts vibrating and a pop up will come like saying your phone is in danger or phn got virus scan now/install antivirus or maybe install this app to remove virus from your phone, click here to download games and movies etc like pop up and vibrations.

●DNS66 version : 0.1.3
●Operating system : Android Marshmallow 6.0.1

●Below i listed some of that kind of sites●

https://dropapk.com/munh0ciu8h89

http://ul.to/9mfxlw6x

https://dailyuploads.net/ifsksrv94c1r

https://filescdn.com/fwy5vrgsysq7

https://uplod.ws/ny5w868j53k7

https://userscloud.com/7ww5ltgaf6kt

http://hugefiles.net/4o2sy9b5gxnx

Try to download files from that pages you will get vibrating and pop-up ads

**Comment by julian-klode** [comment]
You can, if you find out which host the ads are served from and if that host can be blocked entirely (that is, if it does not contain anything useful). Sadly I'm not in the business of actually maintaining ad blocking lists, so there's not anything I can do here.

**Comment by Salmanfarisy** [comment]
To find out which host the ads are served from, you can use this tool: https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture
