### ISSUE TITLE
Internet speed is showing down when using all DNS filters

### ISSUE THREAD

**Issue by jerryn70** [julian-klode/dns66#46]
I'm on the latest version, the internet connectivity speed is too slow when I enable all the DNS filters. Apps are taking long time to load pages. Browsing died is decreased.
When I enable  ISC (US) DNS and disable all other DNS everything is back to normal.

**Comment by julian-klode** [comment]
These are not filters, but custom servers. It only makes sense to enable servers close to you. I now disabled them by default, I think that's a better approach.

**Comment by mrjgguy** [comment]
What do you mean by "servers that are close to you"? Im extremely ignorant about this topic...
