### ISSUE TITLE
Slow Connecting & Reconnecting

### ISSUE THREAD

**Issue by jerryn70** [julian-klode/dns66#47]
When I switch on the internet connection DNS66 takes about  25 sec to start is VPN (time checked using timer) . Reconnecting also takes that much time. In between that time gap ads are shown. Try to make it start at the time  of switching ON the net connecting on the phone.

**Comment by julian-klode** [comment]
Yeah, well, the host files are huge (especially hosts-file.net). I would not recommend enabling them all. I don't think there's much that can be done here - it even takes 10/15 seconds or so on my OnePlus 3 to load all of them.

I can have a closer look at the parser soon, though, and see if it can be improved a bit.

**Comment by julian-klode** [comment]
There was also a bug with reconnecting - the retry time out was increased every time a failure caused a reconnect, and never reset, which means that the service might wait up to 2 minutes at some point. In cb259fa84c80f8b68d07fde1696f2f5c9e957315 I changed that to reset the retry timeout before waiting if the service worked for one minute without errors.

**Comment by julian-klode** [comment]
OK. The hostdb branch in theory takes care of that. In practice, Android has a bug and if you reconnect too quickly, any packets to your VPN end up in the void. So, we are going to get as close as possible to the optimum in 0.4, but I think we likely need at least a 2 second wait before establishing a new VPN connection. But at least that's an idle wait and we don't need to reparse the host files anymore.

We'll still read all host files on initial start of the VPN connection. But I think that's a good trade off: Once it's running, we'll only have to re-read changed host files. If the app is completely stopped, we have to re-read all. The alternative would have been to store the hosts in an sqlite database that is updated when refreshing hosts. Then starting would be instant all the time, but I'm unsure how this would affect performance, especially memory use, or correctness (what if the database gets corrupted - in the current model, you can just restart the app and all problems are solved); and I don't really want to fiddle with SQL that much - it's a rather painful experience.

**Comment by julian-klode** [comment]
Moving to 0.5. It's quite a bit of rework, and I want to get the IPv6 support and user interface tweaks out now, and not mix them with other changes that might potentially break stuff.

**Comment by julian-klode** [comment]
I created a survey about performance considerations, I'd appreciate everyone's opinions: 

https://goo.gl/forms/qtX0eRokt1hfhHYf1

**Comment by julian-klode** [comment]
It's 13 times faster now in commit 2649a0de11d37ae120fc4daa1986d5cf129615d9. 

I'll leave it open for now so we can see if it is fast enough, or really migrate to an SQLite 3 database.

**Comment by julian-klode** [comment]
@jerryn70 What's your opinion on performance now? Is it fast enough for you now?

**Comment by jerryn70** [comment]
@julian-klode Yes now its okey . You can close this issue.
