### ISSUE TITLE
Reconnecting error with firefox (DNS66 v0.1.3)

### ISSUE THREAD

**Issue by melib** [julian-klode/dns66#48]
DNS66 (v0.1.3) always have 'recconnecting error' when I use firefox with wifi connection. It alway occur when I load a webpage.

(However, DNS66 run normally when I use 4g connection or other web browsers.)

My device is Note5 on Marshmallow.

**Comment by julian-klode** [comment]
Confirmed. Firefox seems to be sending weird packets.
