### ISSUE TITLE
App not connecting when DNS66 is enabled

### ISSUE THREAD

**Issue by jerryn70** [julian-klode/dns66#49]
My net gear genie app is not connecting when Dns66 is enabled. When I disable dns66 the app will connect.  I tried default settings of dns66 but the result was same.

Below is the screenshot of error message  I got when I try to connect . 

Dns66 version : Latest build

Screenshot : http://imgur.com/p4W6VTV

**Comment by jerryn70** [comment]
I have turned off domain filter and dns option and tried but getting the same error. If I disable  vpn the app is working. 
And when I use adguard vpn this app works .

Genie app is not working when dns66 vpn is working .
Julian Any idea what the problem is ?

**Comment by julian-klode** [comment]
Sure. The app takes over all traffic to the DNS servers, but ignores any non-DNS traffic. Which means other stuff hosted on the same IP as the DNS server won't work.

There are two reasons it currently does that:

1. It (should) prevent Android from bypassing the service
2. It allows us to use Android's default behaviour if one DNS server becomes unresponsive, so we don't have to deal with it.

The alternative is to create one fake IP address for each DNS server and then map the fake IP addresses to DNS servers when performing lookups. This fixes this bug but opens up the loop hole in 1 - Android might fall back to the real DNS servers if there is some issue.

**Comment by jerryn70** [comment]
Sorry I didn't understand what you said.

What happen if I don't use any dns in dns66 app ?

Is this a common problem ?
