### ISSUE TITLE
Support host files containing only one column

### ISSUE THREAD

**Issue by julian-klode** [julian-klode/dns66#5]
The host file parser currently requires "127.0.0.1 host" or "0.0.0.0 host" with varying amounts of spaces, and some comments. It should also support lists that do not contain IP addresses.

Of the default configuration, http://mirror1.malwaredomains.com/files/justdomains is such a file, although it defaults to ignored.

**Comment by aggsol** [comment]
The Readme still refers to issuea as open.

**Comment by julian-klode** [comment]
@aggsol Not anymore :D
