### ISSUE TITLE
Unable to turn change from "stopped" on 7.1.1 (Pixel)

### ISSUE THREAD

**Issue by kevinmneal** [julian-klode/dns66#50]
Hi,

I was using DNS66 on my previous phone just fine. On Google Pixel, I tried DNS66 0.1.2 and the long press on the power button does nothing. I feel a little vibration with the longpress but it still says "stopped." Same thing with 0.1.2 and 0.1.3 on 7.1.1. I've tried refreshing, activating/reactivating DNS servers and block lists, restoring to default, reinstalling the app, but nothing. Also tried turning off battery optimization in android settings but no luck. If I turn on "start on boot" and restart phone and go into the app it just says "Reconnecting..." without changing; long press again does nothing. Force-close app and it goes back to the normal "stopped" behavior described above.

**Comment by julian-klode** [comment]
What versions did you try it on? You mentioned 0.1.2 and "same thing with 0.1.2 and 0.1.3", so I'm a bit confused if you tried 0.2.0 yet. 

Pixel probably runs Google WiFi assistant in always-on mode which prevents DNS66 from configuring a VPN service.

**Comment by kevinmneal** [comment]
Ah, I hadn't tried 0.2.0 yet. But it was the WiFi assistant that was preventing it from working, thank you for that.
