### ISSUE TITLE
Show notification

### ISSUE THREAD

**Issue by VonRubrik** [julian-klode/dns66#52]
It's just me or show notification flag does not work?
S7 edge 6.0.1
![screenshot_20161215-145455](https://cloud.githubusercontent.com/assets/18470939/21226640/9fe56f3e-c2d6-11e6-82de-e0006cb2261f.png)

**Comment by julian-klode** [comment]
The key icon is not a notification. And on stock Android it's on the right side. It's shown by Android when a VPN is active.

The option hides the notification which says DNS66 active.

**Comment by VonRubrik** [comment]
My bad
