### ISSUE TITLE
Dns66 not working with proxy on

### ISSUE THREAD

**Issue by ghost** [julian-klode/dns66#54]
When I try to use privoxy and dns66 at the same time, to go to a webpage, the VPN goes down and only uses the proxy.

Is it possible to use the vpn and a proxy at the SAME time?

**Comment by julian-klode** [comment]
Privoxy on Android? Sure, that _should_ work. If the VPN crashes, a logcat / (or a bugreport from developer options) is helpful (note that it may contain personal information, you might not want to share this publicly or at all and just extract stuff with dns66 or advpn in it).

**Comment by julian-klode** [comment]
Closing this, as there has been no further updates from the submitter.
