### ISSUE TITLE
Scrollable view changes state on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [julian-klode/dns66#64]
When I perform this sequence of events, the scrollable view on screen goes back to the top:

1. Click on ...
2. Click on Whitelisted Apps
3. Scroll Down the app list
4. Orientation Change

**Comment by julian-klode** [comment]
Sure, it resets. That's what lists do when the orientation change. But that's a minor issue in a part that is not even that visible or nicely integrated yet, it does not really affect the functionality all that much (it's not really a bug, more like an enhancement that we could probably add).
