### ISSUE TITLE
Issues over LTE?

### ISSUE THREAD

**Issue by tvoa90** [julian-klode/dns66#66]
Is there a reason the adblocking doesn't work over LTE unless the custom DNS servers are enabled? Over wifi I have no issues.

**Comment by julian-klode** [comment]
No. It should work. Although: Maybe your LTE connection only has IPv6 DNS servers, then it would explain it. All traffic to your IPv4 DNS servers will be redirected to DNS66 and filtered there before forwarding it to your real DNS servers.

You might want to gather the list of name servers for your LTE connection. I think you can see that somewhere in the SIM status thingy in about phone. Optimally you'd also provide a logcat after starting DNS66, but the server list is a good start.

**Comment by tvoa90** [comment]
I think it is fast.t-mobile.com. under the APN protocol it does say ipv6

**Comment by Zazie-Lavender** [comment]
I'm curious, is there any reason programmatically that dns66 does not properly support IPV6?

**Comment by julian-klode** [comment]
Yes, of course: I have to add special IPv6 packet parsing and generation support and duplicate some code for that. I also do not have access to any IPv6 network.

**Comment by julian-klode** [comment]
OK, that should be fixed with the IPv6 support in master, see #4 and #68. There will be a release in the next days, so you can verify it yourself :)
