### ISSUE TITLE
Cannot use Netflix while DNS66 is running

### ISSUE THREAD

**Issue by SebasJoustra** [julian-klode/dns66#69]
First issue was when I was trying to log in. I got error code -3:

> Please make sure that your device has network connection and the date and time setting are accurate. (-3)

Then I tried turning the dns off, and I was able to log in again. But it won't play anything (error code 12001). Works again if I turn it off.

Is it not possible to use Netflix while running DNS66 or is there someway around this?

**Comment by julian-klode** [comment]
Closing this bug as there was no further details.
