### ISSUE TITLE
Visualise current state of on/off button

### ISSUE THREAD

**Issue by ghost** [julian-klode/dns66#7]
Thank you for making this app.  A VPN connection is the only way I can use alternate DNS servers for whatever odd reason that might be.

However would it be possible to change the power icon to make it easier to determine if the service is running?  For example, change the color to green if it is running and red for off?

**Comment by julian-klode** [comment]
Yes, I'd love to improve the icon button thing. I'm not sure colouring it green for on is the right choice though: It can easily be misunderstood as a power-on button then.

It might also be nice to have another visual difference apart from colour to also make things easier for colour blind people.

And maybe something for when it's starting.

Suggestions welcome.

**Comment by weikinhuang** [comment]
Perhaps the git fork icon with a indicator on one side?
