### ISSUE TITLE
Stock email app doesn't connect to Gmail when DNS66 is active / add stock email app to default exceptions

### ISSUE THREAD

**Issue by fschrader** [julian-klode/dns66#71]
Problem occurs on an Xperia X Compact @ Nougat. Pretty sure this didn't happen on Marshmallow. See [here](http://android.stackexchange.com/questions/166093/cant-connect-to-gmail-on-stock-email-app-using-wifi-works-on-mobile-data) for more info. 

I think adding the stock mail app to the default list of exceptions in the next version should solve the problem.

No idea why this doesn't happen on mobile data, though? (Home WiFi is from Vodafone/Kabel Deutschland, mobile data via O2, if it matters)

**Comment by julian-klode** [comment]
A few questions:

 a. Do you have an IPv6 setup at home?
 b. Are other apps affected?
 c. Does blacklisting fix this now

**Comment by julian-klode** [comment]
Oops, sorry about the closing bit.

**Comment by fschrader** [comment]
a) No idea honestly. Sorry, I'm pretty much a plug-and-play guy when it comes to networking. My router/modem thing does show both an IPv4 and IPv6 address in the LAN settings.
b) Not directly from the email problems, no. Another app that could use a default exception is Audible (doesn't show ads, but the Audible Store throws an error on every page if it's not blacklisted in DNS66). But maybe this should just be mentioned prominently at the first start of DNS66 (not sure if is right now); for me it was pretty much the last thing I thought of. Otherwise you're just adding and adding more apps to the default list.
c) Yes, receiving emails works fine now. 

Thanks for working on this.

**Comment by fschrader** [comment]
FYI this also causes problems with Sony's OTA update function not working properly. No idea which app to whitelist though, I only got it to work after disabling DNS66 completely.

**Comment by julian-klode** [comment]
System apps (except browsers) are bypassing by default (you can also toggle to Bypass All, or None) since 0.5, hence closing this.
