### ISSUE TITLE
More obvious indicator for on/off status in "Start/Stop" tab

### ISSUE THREAD

**Issue by atomicknight** [julian-klode/dns66#72]
On version 0.2.1, the "Start/Stop" tab shows the same image regardless of the on/off status. The only indication of whether the service is actually running is the caption underneath, which is easy to miss at a glance because of the font size and text color.

This screen might be more usable with a more obvious indicator of whether the service is running. Some possible ideas:
* Different icons for running versus not (e.g. checkmark for "running" and exclamation point inside a triangle for "stopped")
* Larger text above the image that reads something like "Status: RUNNING" or "Status: STOPPED"
* Different colors for the different states

**Comment by Madis0** [comment]
Something that looks like a built-in switch would make the most sense. Either just make a huge switch or use the home view more efficiently, like showing about info or app whitelist.

**Comment by julian-klode** [comment]
This is a duplicate of #7.

**Comment by julian-klode** [comment]
And yes, it's horrible. Ideas are always welcome there, pull requests even more :)
