### ISSUE TITLE
DNS function not working properly

### ISSUE THREAD

**Issue by jerryn70** [julian-klode/dns66#73]
Hi, i just tried Adguard family protection DNS that blocks ads and pron sites. ( 176.103.130.132 and 176.103.130.134 ) 
 I visited pronhub.com via chorme browser and found that, the site is not blocked by the DNS server. 

Then I tried the same DNS server in DNS changer app and visited the site, this time the site is blocked by the DNS server. 

@julian-klode

**Comment by julian-klode** [comment]
I assume you mean pornhub.com? That works for me:

before:

```
$ busybox nslookup pornhub.com
Server:    0.0.0.0
Address 1: 0.0.0.0

Name:      pornhub.com
Address 1: 31.192.120.36
```

after:

```$ busybox nslookup pornhub.com
Server:    0.0.0.0
Address 1: 0.0.0.0

Name:      pornhub.com
Address 1: 176.103.130.130 176-103-130-130.flops.ru
```

The DNS server tab is a bit confusing. The servers must be 
1. at the top of the list
2. set to allow/green

as the green servers are added top to bottom to the list of DNS servers known.
