### ISSUE TITLE
Impossible to see which apps are affected by dns66

### ISSUE THREAD

**Issue by zuglufttier** [julian-klode/dns66#76]
Hi,

dns66 is a really good idea in my opinion since we don't need to root our devices and it works pretty good on my Nexus 5x.
But it can be very problematic if you're not able to see whether your app is affected by the settings in dns66 or not. Just think about security updates for the OS.

So, would it be possible to add a list of those apps whose content gets filtered?

**Comment by julian-klode** [comment]
All apps are listed in the whitelist (in the ... menu), and you can whitelist apps there. What's not whitelisted there is filtered.

**Comment by ashketchupandmustard** [comment]
Does dns66 also block system apps which aren't shown in the whitelist? It seems like only apps present in the launcher (app draw) are shown.

**Comment by julian-klode** [comment]
@ashketchupandmustard It blocks everything, and you can whitelist more starting with 0.3.0. I wonder if I should just whitelist all apps with an uid < 2000. From reading the netguard code, these seem to be the the system apps like system update and stuff.
