### ISSUE TITLE
[REQUEST] Add proxy chaining.

### ISSUE THREAD

**Issue by jpdasma** [julian-klode/dns66#77]
With how DNS66 works, it overrides the system setting for proxy. For example, you set a manual proxy in your WiFi network. When DNS66 is activated, it does not use the proxy. Based on my observation, the traffic goes to DNS66.

If DNS66 is disabled. The proxy set in the WiFi settings is working correctly.

A quick test to see that DNS66 overrides the system setting is to add a non-existing proxy in the WiFi settings. Notice that your apps can still connect to the internet even though a non-existing proxy is set.

**Comment by julian-klode** [comment]
No, it does not override the proxy setting. It does not even use a proxy. All it does is configure DNS servers and redirect them through the VPN. And it only redirects requests to the DNS servers, and nothing else.

If your proxy settings don't work, that's a bit unfortunate, but outside of my control.

**Comment by jpdasma** [comment]
Hello, it seems that I worded my sentence wrong. I think DNS66 is ignoring the system proxy. From what I understand, DNS66 only "processes" the DNS request and let normal traffic through (without touching it). So the data still passes through DNS66. However it seems that DNS66 ignores the system proxy. Android application can ignore system proxy if it is coded that way. (I said this based on this: http://stackoverflow.com/questions/24417242/do-android-proxy-settings-apply-to-all-apps-on-the-device)

Please reconsider. (If I'm wrong though, please ignore this).
