### ISSUE TITLE
Option to prevent the key symbol from showing all the time

### ISSUE THREAD

**Issue by amo13** [julian-klode/dns66#78]
Hey dude,
thank you a lot for this truly amazing application! Finally there is an effective ad-blocker on f-droid, which does not require root.
I would like to install the app on some phones currently running 6.0.1 (CM13), but I must admit that I find the key symbol appearing all the time in the statusbar rather annoying. 
I would therefore love a little feature to hide it. Or did I already miss it somewhere?
Cheers
Amo

**Comment by julian-klode** [comment]
It is automatically shown by Android and can not be hidden :(
