### ISSUE TITLE
Can't establish VPN connection

### ISSUE THREAD

**Issue by amo13** [julian-klode/dns66#79]
Hey dude,
I installed DNS66 on two sony devices running 6.0.1 CM13 and unfortunately I get the same problem on both devices: the vpn connection can't be established. Of course, I downloaded the hosts files before activating. You can find attached a log of one device.
[dns66log.txt](https://github.com/julian-klode/dns66/files/729248/dns66log.txt)
Did I miss something? I already got the app to work on other devices and it is pretty sweet!
Cheers
Amo

**Comment by julian-klode** [comment]
Your system has 0.0.0.0 configured as a DNS server. Re-adding this to the pseudo-VPN does not work - Android rejects it as an invalid address, and throws an exception. In the commit I just added I just tell the code to ignore any exception when adding existing servers (and well, log them).

**Comment by julian-klode** [comment]
Released in v0.2.2 (if you are using f-droid, you should get the update around tomorrow).

**Comment by amo13** [comment]
Amazing! Thank you a lot for looking into this. Looking forward to install in shortly.
PS: Solution commited in just a few minutes?! You just blew my mind!
