### ISSUE TITLE
Improve accessibility for item status

### ISSUE THREAD

**Issue by julian-klode** [julian-klode/dns66#8]
Currently we just show a circle that is either red, grey, or green. This is bad in two ways:
## Red-Green Color blindness

Red-Green color blindness is fairly common, so I think this makes it unnecessarily hard for affected people to see if something is allowed or denied. 

Suggested Improvement: Make it more like a switch. So, instead of only having coloured circles, have them positioned in a pill-like oval form. Left=red=denied, Center=grey=ignored, Right=green=allowed.
## Vision loss

We don't provide any textual information what that button is, rendering it useless to people with vision loss. 

Suggested improvement: Set the standard Android attributes for descriptive texts.

**Comment by ckuethe** [comment]
While you're at it, could you add some text that explains what the control does? A red blob to me says that this hosts source is somehow failing, or not doing what it's supposed to.
