### ISSUE TITLE
Host blocking not working

### ISSUE THREAD

**Issue by jerryn70** [julian-klode/dns66#81]
I have added one site url to the domain filter. 
Action set to deny (red colour) and refreshed host and restarted vpn connection . But it's not blocking that site.

**Comment by julian-klode** [comment]
You do not have to write things here and on the XDA thread. Anyway, did you block the same host?

Or did you block something like example.com but are using www.example.com?

**Comment by jerryn70** [comment]
I have tried example.com , www.example.com and http://example.com 


Issue closed
Reason : issue already posted on xda thread
