### ISSUE TITLE
Google Play?

### ISSUE THREAD

**Issue by soaringowl2145** [julian-klode/dns66#82]
I think I already know the answer to this but is it possible to get this app on Google Play or does it violate the terms?

**Comment by SMed79** [comment]
Hi, 
apps which interfered with the traffic of other Android apps, in violation of the Android Marketplace terms.

**Google Play Developer Distribution Agreement** / section 4.4
>4.4 Prohibited Actions. You agree that you will not engage in any activity with the Store, including the development or distribution of Products, that interferes with, disrupts, damages, or accesses in an unauthorized manner the devices, servers, networks, or other properties or services of any third party including, but not limited to, Android users, Google or any mobile network operator. You may not use customer information obtained from the Store to sell or distribute Products outside of the Store. https://play.google.com/about/developer-distribution-agreement.html

I think for that raison [ABP](https://adblockplus.org/) was discontinued their Adblock Plus for Android (Proxy app) (...in additional has a lot a bug). Now replaced by [Adblock Browser](https://adblockbrowser.org/).

![https://adblockbrowser.org/](https://adblockbrowser.org/images/adblock-browser-logo.png)

Read 
* https://adblockplus.org/blog/adblock-plus-for-android-removed-from-google-play-store
* http://lifehacker.com/5990448/google-has-started-removing-ad-blockers-from-the-play-store

**Comment by soaringowl2145** [comment]
Thanks!
