### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by 717998477** [julian-klode/dns66#84]
Add their own DNS address on the Google market does not work, the same DNS address software pure DNS this application will be able to access the Google market, I am Chinese

**Comment by julian-klode** [comment]
I'm a bit confused what you mean. Do you mean that if you configure a custom DNS server, this one is not used when trying to access the Play Store? This may well be true.

**Comment by julian-klode** [comment]
It's been 1.5 months since my last comment, so I'm closing this now.
