### ISSUE TITLE
Cannot block ads from adMarketplace

### ISSUE THREAD

**Issue by magic95vert** [julian-klode/dns66#85]
I am pretty sure that this is in the PeterLowes list, but it ads still appear. 

I have added both admarketplace.net and admarketplace.com to the domain list and marked it as deny.

How can get these ads to stop?

Thanks.

**Comment by julian-klode** [comment]
PeterLowes list works for me:

```
$ busybox nslookup admarketplace.net
Server:    0.0.0.0
Address 1: 0.0.0.0

nslookup: can't resolve 'admarketplace.net': No address associated with hostname
```

Real ads might be served from a subdomain or something, so you might want to update the lists (and make sure it's marked as deny/red). But if the lists are not up to date, I can't help.

**Comment by julian-klode** [comment]
Also note that apps are free to hardcode their own DNS servers - we do not hijack that.

**Comment by SMed79** [comment]
@magic95vert admarketplace known hosts:
```
0.0.0.0 admarketplace.net
0.0.0.0 www.admarketplace.net
0.0.0.0 adtag.admarketplace.net
0.0.0.0 bridge1.admarketplace.net
0.0.0.0 tracking.admarketplace.net
0.0.0.0 bridge.sf.admarketplace.net
0.0.0.0 bridge.ame.admarketplace.net
0.0.0.0 service.pca.admarketplace.net
0.0.0.0 bridge2.lga1.admarketplace.net
0.0.0.0 bridge2.sfo1.admarketplace.net
```
