### ISSUE TITLE
Can't get VOIP calls to work

### ISSUE THREAD

**Issue by akanter** [julian-klode/dns66#88]
I can't seem to figure out what settings to use to allow Google Hangouts and Facebook Messenger VOIP calls to work. When I go to join the call, it drops my LTE connection if I have the DNS66 proxy running even with those apps whitelisted. This is on my Google Pixel.

Any idea how to make this work?

**Comment by julian-klode** [comment]
No sorry. DNS66 just routes DNS traffic differently, it should have no effect on VoIP apps, let alone on your method of connectivity. You might want to get a logcat around that time, that might be vastly useful.

**Comment by ds20** [comment]
I ran into the same issues. Here are more reports:

https://www.reddit.com/r/androidapps/comments/5xpbq0/blokada_vs_dns66/

The poster is right - the LTE drops momentarily when initiating a Hangouts call when DNS66 is running. There seems to be no entry to logcat when this is happening .

**Comment by ds20** [comment]
This was on Nexus 5x, SPrint network (FreedomPop). May be related to it being CDMA somehow?

**Comment by RailRanger** [comment]
Yeah for some reason I can't hear anything when I call with hangouts with dns66. I can recieve calls fine though.
