### ISSUE TITLE
[Suggestion] Log DNS like Adaway

### ISSUE THREAD

**Issue by labors89** [julian-klode/dns66#90]
I really love DNS66 and it's great to see the app evolution. The only feature I miss from my root (adaway) days regarding adblock is the option to (temporarily) log dns request as way to find ads that bypass my default list.

When I used adaway and found an ads in a random app I would open adaway and temporarily log dns requests to find the offending address, long press the address and set it to block.

It would be great if dns66 could do something similar as adaway is also open source, so far my method has been using dns66 as my default adblock and using netguard to discover rogue dns requests.

Anyway, just a suggestion. Thank you for the effort you put in the app

**Comment by SMed79** [comment]
Hi,
such feature will useful if added to DNS66.

currently i use [tPacketCapture](https://play.google.com/store/apps/details?id=jp.co.taosoftware.android.packetcapture) to creates a **[pcap](https://en.wikipedia.org/wiki/Pcap)** file and read it using [Wireshark](https://www.wireshark.org/).

@labors89 see http://stackoverflow.com/questions/9555403/capturing-mobile-phone-traffic-on-wireshark

**Comment by julian-klode** [comment]
I agree, that's why I opened up #35 October last year. Let's discuss it there, and close this one :)
