### ISSUE TITLE
Confused about rules screen (red, gray, green) 

### ISSUE THREAD

**Issue by magowiz** [julian-klode/dns66#99]
I'm starting to use in these days the application and I really don't understand what colour I should choose to block all hosts taken from a list. 
On top the indication is ambiguous "red rules blocks, green rules allow". 
Allow or block what? The use of the lists (red disable list /green enable list) or the hosts contained in the list? If I whish to block all hosts from all lists, should I set the screen to "all green" or "all red"?

**Comment by julian-klode** [comment]
Not sure if real or April fools. Anyway, if you want to block hosts with a rule (an entry in the list), you mark that rule as blocking.

**Comment by magowiz** [comment]
No April fools, I really didn't know, so all red rules should mean take all these lists and block traffic involving hosts contained. Thanks.
